window.__addPassage({
  "date": "2026-07-16",
  "level": "600",
  "theme": "ビジネス基礎（オフィス・取引）",
  "title": "A Reply to a Customer Inquiry",
  "words": ["invoice","itinerary","reimburse","warranty","inquiry","estimate","shipment","postpone","accommodate","merchandise","appliance","expire","refund","supervisor","complimentary"],
  "passage": "Dear Mr. Carter,\n\nThank you for your [[inquiry]] about the kitchen [[appliance]] you purchased last month. I am sorry to hear that the [[merchandise]] arrived with a damaged door. Because the item is still under [[warranty]], you are entitled to a free repair or a full [[refund]].\n\nOur records show that the original [[shipment]] was delayed, so we would like to [[accommodate]] you by offering a [[complimentary]] extended service plan. If you prefer a replacement, we can send a new unit, though the current promotional price will [[expire]] at the end of this week.\n\nPlease note that any travel costs related to returning the product will be [[reimbursed]] once you submit the [[invoice]] and receipt to your assigned [[supervisor]]. If you would like a technician to visit, we can provide a written [[estimate]] of the repair time and prepare an [[itinerary]] for the service team. Should the necessary parts be unavailable, we may need to [[postpone]] the visit by a few days, and we will inform you immediately.\n\nBest regards,\nCustomer Support",
  "passageJa": "カーター様\n\n先月ご購入いただいた台所用家電に関するお問い合わせ、ありがとうございます。商品がドアの破損した状態で届いたとのこと、申し訳ございません。当該商品はまだ保証期間中ですので、無償修理または全額返金を受ける権利がございます。\n\n記録によりますと、当初の発送が遅れておりましたため、お詫びとして無料の延長サービスプランをご提供し、ご要望にお応えしたく存じます。交換をご希望の場合は新品をお送りできますが、現在の特別価格は今週末で期限切れとなります。\n\n商品返送にかかる交通費は、請求書と領収書を担当の上司にご提出いただいた時点で払い戻されますのでご了承ください。技術者の訪問をご希望でしたら、修理時間の見積書を書面でご用意し、サービスチームの訪問日程表を作成いたします。必要な部品が入手できない場合は、訪問を数日延期する必要が生じることがありますが、その際は直ちにご連絡いたします。\n\n何卒よろしくお願い申し上げます。\nカスタマーサポート",
  "questions": [
    {"q": "Why is the customer entitled to a free repair or refund?", "choices": ["Because the price has expired.", "Because the appliance is still under warranty.", "Because the supervisor approved it.", "Because the shipment was complimentary."], "answer": 1, "expl": "第1段落。商品がまだ warranty(保証)期間中であるため、無償修理または全額返金の権利があります。"},
    {"q": "What must the customer submit to be reimbursed for travel costs?", "choices": ["The itinerary and warranty.", "The estimate and a photo.", "The invoice and receipt.", "The appliance and its box."], "answer": 2, "expl": "第3段落。交通費の払い戻しには invoice(請求書)と receipt(領収書)を上司に提出する必要があります。"},
    {"q": "In this passage, the word \"accommodate\" is closest in meaning to", "choices": ["meet the request of", "postpone the visit of", "charge a fee to", "keep a record of"], "answer": 0, "expl": "ここでの accommodate は「(要望に)応える」の意味です。「収容する」の意味もありますが、文脈では顧客の要望に応じる意味で使われています。"}
  ]
});
window.__addPassage({
  "date": "2026-07-17",
  "level": "600",
  "theme": "採用・人事",
  "title": "Filling a Vacancy in the Sales Team",
  "words": ["candidate","applicant","recruit","hire","résumé","qualification","orientation","personnel","promote","retire","vacancy","benefits","punctual","absent","temporary"],
  "passage": "When the sales manager decided to [[retire]] after twenty years, the [[personnel]] department announced a [[vacancy]] and began to [[recruit]] a replacement. More than sixty people applied, and each [[applicant]] was asked to submit a detailed [[résumé]] describing their work history and [[qualifications]].\n\nAfter reviewing the documents, the team invited eight promising [[candidates]] for interviews. The company hoped to [[hire]] someone who was reliable, [[punctual]], and rarely [[absent]]. Strong communication skills mattered more than experience, because the firm prefers to [[promote]] staff from within whenever possible.\n\nThe successful [[candidate]] will first join on a [[temporary]] contract for three months. During this period, she will attend an [[orientation]] session to learn about company policies and the [[benefits]] package, which includes health insurance and paid holidays. If her performance is strong, the [[temporary]] role will become permanent.",
  "passageJa": "営業部長が20年の勤務を経て退職することを決めたため、人事部は欠員を告知し、後任の採用を始めました。60人以上が応募し、各応募者は職歴と資格を記した詳細な履歴書の提出を求められました。\n\n書類を審査した後、チームは有望な8人の候補者を面接に招きました。会社が採用したかったのは、信頼でき、時間を守り、めったに欠勤しない人物でした。この会社は可能な限り社内から昇進させることを好むため、経験よりも高いコミュニケーション能力が重視されました。\n\n採用された候補者は、まず3か月間の臨時契約で入社します。この期間中、彼女は会社の方針と、健康保険や有給休暇を含む福利厚生パッケージについて学ぶオリエンテーションに参加します。勤務成績が良好であれば、その臨時の役職は正社員のものになります。",
  "questions": [
    {"q": "Why did the personnel department announce a vacancy?", "choices": ["Because a manager was absent.", "Because the sales manager decided to retire.", "Because sixty people applied.", "Because the company changed its benefits."], "answer": 1, "expl": "第1段落。営業部長が retire(退職)を決めたため、人事部は欠員(vacancy)を告知して後任の募集を始めました。"},
    {"q": "What quality did the company most want in a new employee?", "choices": ["Many years of experience.", "A university degree in sales.", "Being reliable and punctual.", "A willingness to work overseas."], "answer": 2, "expl": "第2段落。会社は信頼でき、punctual(時間を守る)、めったに absent(欠勤)しない人物を求めており、経験よりコミュニケーション能力を重視しました。"},
    {"q": "How will the successful candidate start working?", "choices": ["On a permanent contract.", "As a part-time volunteer.", "On a temporary three-month contract.", "As an outside consultant."], "answer": 2, "expl": "第3段落。採用者はまず3か月の temporary(臨時)契約で入社し、成績が良ければ正社員になります。"}
  ]
});
window.__addPassage({
  "date": "2026-07-18",
  "level": "600",
  "theme": "経理・財務",
  "title": "Closing the Fiscal Year",
  "words": ["budget","expense","receipt","deposit","balance","transaction","fund","revenue","deduct","installment","overdue","audit","fiscal","asset","statement"],
  "passage": "At the end of each [[fiscal]] year, our accounting team prepares a financial [[statement]] that summarizes the company's income and spending. Last year, total [[revenue]] rose by twelve percent, mainly because we reduced unnecessary [[expenses]] and kept every department within its [[budget]].\n\nEvery [[transaction]] must be recorded carefully. Employees are required to keep each [[receipt]] so that the finance office can [[deduct]] business costs correctly and prepare for the annual [[audit]]. When a customer pays a large sum, we usually ask for a [[deposit]] first and allow the remainder to be paid in monthly [[installments]].\n\nThe auditor also checks whether any invoice is [[overdue]] and confirms that the account [[balance]] matches the bank records. Thanks to steady cash flow, the company was able to [[fund]] a new project without borrowing money. Management now considers the office building one of its most valuable [[assets]].",
  "passageJa": "各会計年度の終わりに、当社の経理チームは会社の収入と支出をまとめた財務諸表を作成します。昨年は、不要な経費を削減し、各部門を予算内に収めたことが主な要因となって、総収益が12パーセント増加しました。\n\nすべての取引は慎重に記録しなければなりません。従業員は各領収書を保管するよう求められており、これは経理部が事業費を正しく控除し、年次監査に備えるためです。顧客が高額を支払う場合は、通常まず手付金を求め、残額は毎月の分割払いで支払えるようにしています。\n\n監査人はまた、期限切れの請求書がないかを確認し、口座残高が銀行の記録と一致することを確かめます。安定した資金の流れのおかげで、会社は借入をせずに新規プロジェクトへ資金を提供することができました。経営陣は現在、その社屋を最も価値ある資産の一つと見なしています。",
  "questions": [
    {"q": "Why did total revenue rise last year?", "choices": ["Because the company borrowed money.", "Because expenses were reduced and budgets were kept.", "Because the audit was postponed.", "Because customers paid in installments."], "answer": 1, "expl": "第1段落。総収益(revenue)が増えた主因は、不要な expenses(経費)を削減し、各部門が budget(予算)内に収まったことです。"},
    {"q": "Why must employees keep every receipt?", "choices": ["To pay in monthly installments.", "To increase the company's revenue.", "So that business costs can be deducted and the audit prepared.", "So that the building can be sold."], "answer": 2, "expl": "第2段落。領収書(receipt)を保管するのは、事業費を正しく deduct(控除)し、年次 audit(監査)に備えるためです。"},
    {"q": "In this passage, the word \"overdue\" is closest in meaning to", "choices": ["already paid", "past the due date", "recently issued", "carefully checked"], "answer": 1, "expl": "overdue は「(支払い・期限が)過ぎた」の意味で、past the due date に相当します。invoice(請求書)とともに頻出します。"}
  ]
});
window.__addPassage({
  "date": "2026-07-19",
  "level": "600",
  "theme": "物流・在庫",
  "title": "A Day at the Regional Warehouse",
  "words": ["warehouse","inventory","carrier","freight","distributor","wholesale","retailer","dispatch","procurement","supplier","backorder","customs","consignment","courier","replenish"],
  "passage": "Our regional [[warehouse]] plays a central role in the supply chain. Every morning, the staff check the [[inventory]] system to see which products need to be [[replenished]]. When stock runs low, the [[procurement]] team contacts a trusted [[supplier]] and places a new order.\n\nBecause we buy in large quantities at [[wholesale]] prices, we can offer competitive rates to each [[retailer]] we serve. Once goods arrive, workers prepare them for [[dispatch]] and hand them to a [[carrier]] for delivery. Small, urgent packages are sent by [[courier]], while heavier [[freight]] travels by truck or ship.\n\nInternational shipments must clear [[customs]] before they can continue, which sometimes causes delays. If a popular item is temporarily unavailable, it is placed on [[backorder]] until the next [[consignment]] arrives. As the main [[distributor]] for this area, our goal is to keep every shelf full and every [[retailer]] satisfied.",
  "passageJa": "当社の地域倉庫はサプライチェーンの中心的な役割を担っています。毎朝、スタッフは在庫システムを確認し、どの商品を補充する必要があるかを調べます。在庫が少なくなると、調達チームが信頼できる仕入先に連絡し、新たに発注します。\n\n当社は卸売価格で大量に仕入れているため、取引する各小売店に競争力のある価格を提供できます。商品が到着すると、作業員はそれらを発送用に準備し、配送業者に引き渡します。小さく急ぎの荷物は宅配便で送られ、より重い貨物はトラックや船で運ばれます。\n\n国際輸送の荷物は先に進む前に通関を通過しなければならず、これが時に遅延を招きます。人気商品が一時的に品切れの場合は、次の入荷分が届くまで取り寄せ注文として登録されます。この地域の主要な流通業者として、私たちの目標はすべての棚を満たし、すべての小売店に満足してもらうことです。",
  "questions": [
    {"q": "What do the staff check every morning?", "choices": ["The customs paperwork.", "The inventory system.", "The wholesale prices.", "The courier's schedule."], "answer": 1, "expl": "第1段落。スタッフは毎朝 inventory(在庫)システムを確認し、補充(replenish)が必要な商品を把握します。"},
    {"q": "How are small, urgent packages sent?", "choices": ["By ship as freight.", "By the procurement team.", "By courier.", "On backorder."], "answer": 2, "expl": "第2段落。小さく急ぎの荷物は courier(宅配便)で送られ、重い freight(貨物)はトラックや船で運ばれます。"},
    {"q": "What happens to a popular item that is temporarily unavailable?", "choices": ["It is sold at wholesale.", "It is placed on backorder until the next consignment arrives.", "It is returned to the retailer.", "It is held at customs."], "answer": 1, "expl": "第3段落。品切れの人気商品は、次の consignment(入荷分)が届くまで backorder(取り寄せ注文)として登録されます。"}
  ]
});
window.__addPassage({
  "date": "2026-07-20",
  "level": "600",
  "theme": "マーケティング・広告",
  "title": "Planning the Summer Product Launch",
  "words": ["advertisement","campaign","consumer","demographic","endorse","feedback","impression","launch","loyalty","publicity","slogan","sponsor","survey","target","audience"],
  "passage": "When our company decided to [[launch]] a new line of eco-friendly water bottles, the marketing department began by conducting a [[survey]] of two thousand shoppers. The results helped us understand our [[target]] [[audience]]: most interested buyers belonged to a younger [[demographic]] of urban professionals. Based on this [[consumer]] data, we designed an advertising [[campaign]] built around a single, memorable [[slogan]]: \"Refresh the planet.\"\n\nTo increase [[publicity]], we placed an [[advertisement]] in several online magazines and asked a well-known athlete to [[endorse]] the product. Her support made a strong first [[impression]] on viewers and generated thousands of comments within a day. We also partnered with a local music festival, agreeing to [[sponsor]] the main stage in exchange for banner space.\n\nAfter the first month, we collected customer [[feedback]] through a short questionnaire. Many buyers praised the design and said they would recommend the bottle to friends, which is exactly the kind of brand [[loyalty]] we hoped to build. The positive response confirmed that understanding the [[consumer]] before spending money on advertising is the smartest way to reach the right [[audience]].",
  "passageJa": "当社が環境に優しい水筒の新シリーズを発売することを決めたとき、マーケティング部はまず2,000人の買い物客への調査から着手しました。その結果、当社のターゲット層が見えてきました。関心を示した購入者の多くは、都市部の若手社会人という比較的若い層に属していたのです。この消費者データをもとに、私たちは覚えやすい一つのスローガン「地球をリフレッシュしよう」を軸にした広告キャンペーンを設計しました。\n\n宣伝効果を高めるため、いくつかのオンライン雑誌に広告を掲載し、有名なスポーツ選手にその製品を推奨してもらうよう依頼しました。彼女の支持は視聴者に強い第一印象を与え、1日のうちに何千ものコメントを生み出しました。また地元の音楽フェスティバルと提携し、バナー掲載と引き換えにメインステージのスポンサーになることに合意しました。\n\n最初の1か月が過ぎた後、私たちは短いアンケートを通じて顧客からのフィードバックを集めました。多くの購入者がデザインを称賛し、友人にこの水筒を勧めたいと答えました。これはまさに私たちが築きたかったブランドへの愛顧です。この好意的な反応は、広告にお金をかける前に消費者を理解することこそが、適切な聴衆に届く最も賢い方法だと裏付けました。",
  "questions": [
    {"q": "What did the marketing department do first?", "choices": ["It placed an advertisement in magazines.", "It conducted a survey of shoppers.", "It sponsored a music festival.", "It created a new slogan."], "answer": 1, "expl": "第1段落。マーケティング部は最初に2,000人の買い物客への survey(調査)を実施しました。広告掲載・スポンサー・スローガン作成はいずれもその後の工程です。"},
    {"q": "Why was a famous athlete asked to endorse the product?", "choices": ["To design the water bottle.", "To conduct the customer survey.", "To increase publicity for the product.", "To reduce the advertising budget."], "answer": 2, "expl": "第2段落。宣伝効果(publicity)を高めるために有名選手に推奨を依頼し、それが強い第一印象につながりました。"},
    {"q": "In this passage, the word \"endorse\" is closest in meaning to", "choices": ["publicly support", "secretly criticize", "carefully measure", "quickly deliver"], "answer": 0, "expl": "endorse は「(公に)支持する・推奨する」の意味で、support / recommend に言い換えられます。Part 7 の同義語問題で頻出です。"}
  ]
});
window.__addPassage({
  "date": "2026-07-21",
  "level": "600",
  "theme": "施設・オフィス管理",
  "title": "Notice: Upcoming Building Renovation",
  "words": ["maintenance","renovation","premises","facility","tenant","occupancy","inspection","lease","vendor","relocate","spacious","adjacent","utility","custodian","corridor"],
  "passage": "To all [[tenant]]s of the Brookfield Business Center:\n\nWe are pleased to announce that a major [[renovation]] of our [[premises]] will begin next month. The goal is to modernize the building and improve every shared [[facility]], from the reception area to the meeting rooms. During this period, our [[custodian]] and a licensed [[vendor]] will work together to complete the upgrades with as little disruption as possible.\n\nPlease note the following. Routine [[maintenance]] of the heating system will take place during the first week, and a safety [[inspection]] of all floors is scheduled for the second week. To keep everyone safe, please do not store any items in the main [[corridor]], since it must remain clear at all times. There may be brief interruptions to certain [[utility]] services, such as water and electricity, but these will be announced in advance.\n\nOnce the work is finished, the building will offer more [[spacious]] offices and a new lounge [[adjacent]] to the lobby. Because [[occupancy]] has grown steadily, several teams will [[relocate]] to the newly opened fifth floor. Tenants who wish to expand their current space should contact the management office before their [[lease]] comes up for renewal. We appreciate your patience and look forward to welcoming you to an improved workplace.",
  "passageJa": "ブルックフィールド・ビジネスセンターの入居者の皆様へ:\n\n当ビルの大規模な改装を来月開始することをお知らせします。目的は建物を近代化し、受付エリアから会議室まで、共用のあらゆる設備を改善することです。この期間中、当ビルの用務員と免許を持つ業者が協力し、できるだけ支障の少ない形で改修を完了させます。\n\n以下にご注意ください。暖房システムの定期保守は第1週に行われ、全フロアの安全点検は第2週に予定されています。皆様の安全のため、正面の廊下には物を置かないでください。常に通路を確保しておく必要があるためです。水道や電気など一部の公共設備サービスに短時間の中断が生じる場合がありますが、これらは事前にお知らせします。\n\n工事が完了すると、ビルはより広々としたオフィスと、ロビーに隣接した新しいラウンジを提供します。入居率が着実に伸びているため、いくつかのチームは新たに開放される5階へ移転します。現在のスペースを拡張したい入居者は、賃貸契約の更新時期を迎える前に管理事務所へご連絡ください。ご辛抱に感謝するとともに、改善された職場に皆様をお迎えできることを楽しみにしています。",
  "questions": [
    {"q": "What is the main purpose of this notice?", "choices": ["To announce a rent increase", "To inform tenants about an upcoming renovation", "To advertise office space for new tenants", "To report the results of a customer survey"], "answer": 1, "expl": "第1段落で「大規模な改装を来月開始する」と告知し、以降で作業内容を説明しています。よって正解は1。0の家賃値上げ、2の新規入居者向けの宣伝、3の顧客調査結果はいずれも本文で触れられていません。"},
    {"q": "The word \"premises\" in paragraph 1 is closest in meaning to", "choices": ["employees", "building", "equipment", "schedule"], "answer": 1, "expl": "premisesは「建物・敷地」を意味し、ここでは改装対象の当ビルを指します。したがってbuilding(建物)が最も近い意味です。0のemployees(従業員)、2のequipment(設備)、3のschedule(予定)は語義が異なります。"},
    {"q": "Why are tenants asked not to store items in the corridor?", "choices": ["It is reserved for the vendor", "It must remain clear at all times", "It is being repainted this week", "It has no lighting during the work"], "answer": 1, "expl": "第2段落に「常に通路を確保しておく必要があるため物を置かないでください」とあり、安全確保が理由です。よって正解は1。0の業者専用、2の塗り直し、3の照明なしは本文に記載がありません。"}
  ]
});
window.__addPassage({
  "date": "2026-07-23",
  "level": "600",
  "theme": "出張・旅行（交通と宿泊）",
  "title": "Business Trip Arrangements for the Chicago Branch",
  "words": ["reservation", "confirm", "departure", "board", "luggage", "terminal", "layover", "fare", "lodging", "amenity", "concierge", "shuttle", "voucher", "reception", "delay"],
  "passage": "Dear Mr. Tanaka,\n\nThis email is to [[confirm]] the arrangements for your business trip to the Chicago branch next week. Your flight [[departure]] is scheduled for 8:00 a.m. from [[terminal]] 2. The company has already paid the [[fare]], so you do not need to buy a ticket. There will be a short [[layover]] in Denver, so please [[board]] your connecting flight promptly. In case of a [[delay]], the airline will send a message to your phone, and you may wait in the lounge. Please keep your [[luggage]] with you at all times.\n\nWe have made a [[reservation]] for you at the Lakeside Inn, and your [[lodging]] covers three nights. A free hotel [[shuttle]] runs from the airport, so you will not need a taxi. When you arrive, go to the [[reception]] desk and give your booking number to check in. A [[voucher]] for breakfast is included with your stay.\n\nThe hotel offers several [[amenity]] options, such as a fitness center and free Wi-Fi in every room. If you would like restaurant recommendations or help planning your evenings, the [[concierge]] in the lobby will be glad to assist you. Please review these details and reply if anything needs to be changed. We hope you have a smooth and productive trip.\n\nBest regards,\nThe Travel Desk",
  "passageJa": "田中様\n\nこのメールは、来週のシカゴ支店への出張の手配を確認するためのものです。ご搭乗便の出発は午前8時、ターミナル2からの予定です。運賃はすでに会社が支払っていますので、チケットを購入する必要はありません。デンバーで短い乗り継ぎ待ちがありますので、乗り継ぎ便には速やかにご搭乗ください。遅延が生じた場合は航空会社からお電話にメッセージが届きますので、ラウンジでお待ちいただけます。手荷物は常に身につけておいてください。\n\nレイクサイド・インにご予約を入れており、宿泊は3泊分が含まれます。空港からは無料のホテル送迎バスが運行していますので、タクシーは不要です。到着されましたら受付へ行き、予約番号を伝えてチェックインしてください。ご滞在には朝食の引換券が含まれます。\n\nホテルにはフィットネスセンターや全室無料Wi-Fiなど、いくつかの設備がございます。レストランのご紹介や夜の予定づくりのお手伝いが必要でしたら、ロビーのコンシェルジュが喜んで対応いたします。これらの詳細をご確認のうえ、変更が必要な点があればご返信ください。快適で実り多いご出張となりますよう。\n\n敬具\n出張手配デスク",
  "questions": [
    {"q": "What does Mr. Tanaka NOT need to do for this trip?", "choices": ["Buy a plane ticket", "Keep his luggage with him", "Give his booking number at the hotel", "Board the connecting flight quickly"], "answer": 0, "expl": "本文に「The company has already paid the fare, so you do not need to buy a ticket」とあり、チケット購入は不要。よって(0)が正解。(1)は「keep your luggage with you at all times」、(3)は「board your connecting flight promptly」、(2)は受付で予約番号を伝えるよう求められており、いずれも必要な行動なので誤り。"},
    {"q": "How will Mr. Tanaka get from the airport to the hotel?", "choices": ["By taxi", "By a free hotel shuttle", "By a rental car", "By train"], "answer": 1, "expl": "「A free hotel shuttle runs from the airport, so you will not need a taxi」とあり、無料の送迎バスで移動する。よって(1)が正解。(0)はタクシー不要と明記されているため誤り。(2)(3)は本文に記述がない。"},
    {"q": "The word \"delay\" in paragraph 1 is closest in meaning to", "choices": ["cancellation", "discount", "late departure", "upgrade"], "answer": 2, "expl": "delay は「遅延・遅れ」の意味で、ここでは便の出発が遅れることを指す。最も近いのは(2)late departure。(0)cancellation は「欠航・取り消し」で意味が異なる。(1)discount(割引)、(4相当)upgrade(格上げ)はいずれも遅延の意味とは無関係で誤り。"}
  ]
});
