window.__addPassage({
  "date": "2026-07-18",
  "level": "600",
  "theme": "ビジネス基礎（オフィス・取引）",
  "title": "A Reply to a Customer Inquiry",
  "words": ["invoice","itinerary","reimburse","warranty","inquiry","estimate","shipment","postpone","accommodate","merchandise","appliance","expire","refund","supervisor","complimentary"],
  "passage": "Dear Mr. Carter,\n\nThank you for your [[inquiry]] about the kitchen [[appliance]] you purchased last month. I am sorry to hear that the [[merchandise]] arrived with a damaged door. Because the item is still under [[warranty]], you are entitled to a free repair or a full [[refund]].\n\nOur records show that the original [[shipment]] was delayed, so we would like to [[accommodate]] you by offering a [[complimentary]] extended service plan. If you prefer a replacement, we can send a new unit, though the current promotional price will [[expire]] at the end of this week.\n\nPlease note that any travel costs related to returning the product will be [[reimbursed]] once you submit the [[invoice]] and receipt to your assigned [[supervisor]]. If you would like a technician to visit, we can provide a written [[estimate]] of the repair time and prepare an [[itinerary]] for the service team. Should the necessary parts be unavailable, we may need to [[postpone]] the visit by a few days, and we will inform you immediately.\n\nBest regards,\nCustomer Support",
  "passageJa": "カーター様\n\n先月ご購入いただいた台所用家電に関するお問い合わせ、ありがとうございます。商品がドアの破損した状態で届いたとのこと、申し訳ございません。当該商品はまだ保証期間中ですので、無償修理または全額返金を受ける権利がございます。\n\n記録によりますと、当初の発送が遅れておりましたため、お詫びとして無料の延長サービスプランをご提供し、ご要望にお応えしたく存じます。交換をご希望の場合は新品をお送りできますが、現在の特別価格は今週末で期限切れとなります。\n\n商品返送にかかる交通費は、請求書と領収書を担当の上司にご提出いただいた時点で払い戻されますのでご了承ください。技術者の訪問をご希望でしたら、修理時間の見積書を書面でご用意し、サービスチームの訪問日程表を作成いたします。必要な部品が入手できない場合は、訪問を数日延期する必要が生じることがありますが、その際は直ちにご連絡いたします。\n\n何卒よろしくお願い申し上げます。\nカスタマーサポート",
  "questions": [
    {"q": "Why is the customer entitled to a free repair or refund?", "choices": ["Because the price has expired.", "Because the appliance is still under warranty.", "Because the supervisor approved it.", "Because the shipment was complimentary."], "answer": 1, "expl": "第1段落。商品がまだ warranty(保証)期間中であるため、無償修理または全額返金の権利があります。"},
    {"q": "What must the customer submit to be reimbursed for travel costs?", "choices": ["The itinerary and warranty.", "The estimate and a photo.", "The invoice and receipt.", "The appliance and its box."], "answer": 2, "expl": "第3段落。交通費の払い戻しには invoice(請求書)と receipt(領収書)を上司に提出する必要があります。"},
    {"q": "In this passage, the word \"accommodate\" is closest in meaning to", "choices": ["meet the request of", "postpone the visit of", "charge a fee to", "keep a record of"], "answer": 0, "expl": "ここでの accommodate は「(要望に)応える」の意味です。「収容する」の意味もありますが、文脈では顧客の要望に応じる意味で使われています。"}
  ]
});
window.__addPassage({
  "date": "2026-07-19",
  "level": "600",
  "theme": "採用・人事",
  "title": "Filling a Vacancy in the Sales Team",
  "words": ["candidate","applicant","recruit","hire","résumé","qualification","orientation","personnel","promote","retire","vacancy","benefits","punctual","absent","temporary"],
  "passage": "When the sales manager decided to [[retire]] after twenty years, the [[personnel]] department announced a [[vacancy]] and began to [[recruit]] a replacement. More than sixty people applied, and each [[applicant]] was asked to submit a detailed [[résumé]] describing their work history and [[qualifications]].\n\nAfter reviewing the documents, the team invited eight promising [[candidates]] for interviews. The company hoped to [[hire]] someone who was reliable, [[punctual]], and rarely [[absent]]. Strong communication skills mattered more than experience, because the firm prefers to [[promote]] staff from within whenever possible.\n\nThe successful [[candidate]] will first join on a [[temporary]] contract for three months. During this period, she will attend an [[orientation]] session to learn about company policies and the [[benefits]] package, which includes health insurance and paid holidays. If her performance is strong, the [[temporary]] role will become permanent.",
  "passageJa": "営業部長が20年の勤務を経て退職することを決めたため、人事部は欠員を告知し、後任の採用を始めました。60人以上が応募し、各応募者は職歴と資格を記した詳細な履歴書の提出を求められました。\n\n書類を審査した後、チームは有望な8人の候補者を面接に招きました。会社が採用したかったのは、信頼でき、時間を守り、めったに欠勤しない人物でした。この会社は可能な限り社内から昇進させることを好むため、経験よりも高いコミュニケーション能力が重視されました。\n\n採用された候補者は、まず3か月間の臨時契約で入社します。この期間中、彼女は会社の方針と、健康保険や有給休暇を含む福利厚生パッケージについて学ぶオリエンテーションに参加します。勤務成績が良好であれば、その臨時の役職は正社員のものになります。",
  "questions": [
    {"q": "Why did the personnel department announce a vacancy?", "choices": ["Because a manager was absent.", "Because the sales manager decided to retire.", "Because sixty people applied.", "Because the company changed its benefits."], "answer": 1, "expl": "第1段落。営業部長が retire(退職)を決めたため、人事部は欠員(vacancy)を告知して後任の募集を始めました。"},
    {"q": "What quality did the company most want in a new employee?", "choices": ["Many years of experience.", "A university degree in sales.", "Being reliable and punctual.", "A willingness to work overseas."], "answer": 2, "expl": "第2段落。会社は信頼でき、punctual(時間を守る)、めったに absent(欠勤)しない人物を求めており、経験よりコミュニケーション能力を重視しました。"},
    {"q": "How will the successful candidate start working?", "choices": ["On a permanent contract.", "As a part-time volunteer.", "On a temporary three-month contract.", "As an outside consultant."], "answer": 2, "expl": "第3段落。採用者はまず3か月の temporary(臨時)契約で入社し、成績が良ければ正社員になります。"}
  ]
});
window.__addPassage({
  "date": "2026-07-20",
  "level": "600",
  "theme": "経理・財務",
  "title": "Closing the Fiscal Year",
  "words": ["budget","expense","receipt","deposit","balance","transaction","fund","revenue","deduct","installment","overdue","audit","fiscal","asset","statement"],
  "passage": "At the end of each [[fiscal]] year, our accounting team prepares a financial [[statement]] that summarizes the company's income and spending. Last year, total [[revenue]] rose by twelve percent, mainly because we reduced unnecessary [[expenses]] and kept every department within its [[budget]].\n\nEvery [[transaction]] must be recorded carefully. Employees are required to keep each [[receipt]] so that the finance office can [[deduct]] business costs correctly and prepare for the annual [[audit]]. When a customer pays a large sum, we usually ask for a [[deposit]] first and allow the remainder to be paid in monthly [[installments]].\n\nThe auditor also checks whether any invoice is [[overdue]] and confirms that the account [[balance]] matches the bank records. Thanks to steady cash flow, the company was able to [[fund]] a new project without borrowing money. Management now considers the office building one of its most valuable [[assets]].",
  "passageJa": "各会計年度の終わりに、当社の経理チームは会社の収入と支出をまとめた財務諸表を作成します。昨年は、不要な経費を削減し、各部門を予算内に収めたことが主な要因となって、総収益が12パーセント増加しました。\n\nすべての取引は慎重に記録しなければなりません。従業員は各領収書を保管するよう求められており、これは経理部が事業費を正しく控除し、年次監査に備えるためです。顧客が高額を支払う場合は、通常まず手付金を求め、残額は毎月の分割払いで支払えるようにしています。\n\n監査人はまた、期限切れの請求書がないかを確認し、口座残高が銀行の記録と一致することを確かめます。安定した資金の流れのおかげで、会社は借入をせずに新規プロジェクトへ資金を提供することができました。経営陣は現在、その社屋を最も価値ある資産の一つと見なしています。",
  "questions": [
    {"q": "Why did total revenue rise last year?", "choices": ["Because the company borrowed money.", "Because expenses were reduced and budgets were kept.", "Because the audit was postponed.", "Because customers paid in installments."], "answer": 1, "expl": "第1段落。総収益(revenue)が増えた主因は、不要な expenses(経費)を削減し、各部門が budget(予算)内に収まったことです。"},
    {"q": "Why must employees keep every receipt?", "choices": ["To pay in monthly installments.", "To increase the company's revenue.", "So that business costs can be deducted and the audit prepared.", "So that the building can be sold."], "answer": 2, "expl": "第2段落。領収書(receipt)を保管するのは、事業費を正しく deduct(控除)し、年次 audit(監査)に備えるためです。"},
    {"q": "In this passage, the word \"overdue\" is closest in meaning to", "choices": ["already paid", "past the due date", "recently issued", "carefully checked"], "answer": 1, "expl": "overdue は「(支払い・期限が)過ぎた」の意味で、past the due date に相当します。invoice(請求書)とともに頻出します。"}
  ]
});
window.__addPassage({
  "date": "2026-07-21",
  "level": "600",
  "theme": "物流・在庫",
  "title": "A Day at the Regional Warehouse",
  "words": ["warehouse","inventory","carrier","freight","distributor","wholesale","retailer","dispatch","procurement","supplier","backorder","customs","consignment","courier","replenish"],
  "passage": "Our regional [[warehouse]] plays a central role in the supply chain. Every morning, the staff check the [[inventory]] system to see which products need to be [[replenished]]. When stock runs low, the [[procurement]] team contacts a trusted [[supplier]] and places a new order.\n\nBecause we buy in large quantities at [[wholesale]] prices, we can offer competitive rates to each [[retailer]] we serve. Once goods arrive, workers prepare them for [[dispatch]] and hand them to a [[carrier]] for delivery. Small, urgent packages are sent by [[courier]], while heavier [[freight]] travels by truck or ship.\n\nInternational shipments must clear [[customs]] before they can continue, which sometimes causes delays. If a popular item is temporarily unavailable, it is placed on [[backorder]] until the next [[consignment]] arrives. As the main [[distributor]] for this area, our goal is to keep every shelf full and every [[retailer]] satisfied.",
  "passageJa": "当社の地域倉庫はサプライチェーンの中心的な役割を担っています。毎朝、スタッフは在庫システムを確認し、どの商品を補充する必要があるかを調べます。在庫が少なくなると、調達チームが信頼できる仕入先に連絡し、新たに発注します。\n\n当社は卸売価格で大量に仕入れているため、取引する各小売店に競争力のある価格を提供できます。商品が到着すると、作業員はそれらを発送用に準備し、配送業者に引き渡します。小さく急ぎの荷物は宅配便で送られ、より重い貨物はトラックや船で運ばれます。\n\n国際輸送の荷物は先に進む前に通関を通過しなければならず、これが時に遅延を招きます。人気商品が一時的に品切れの場合は、次の入荷分が届くまで取り寄せ注文として登録されます。この地域の主要な流通業者として、私たちの目標はすべての棚を満たし、すべての小売店に満足してもらうことです。",
  "questions": [
    {"q": "What do the staff check every morning?", "choices": ["The customs paperwork.", "The inventory system.", "The wholesale prices.", "The courier's schedule."], "answer": 1, "expl": "第1段落。スタッフは毎朝 inventory(在庫)システムを確認し、補充(replenish)が必要な商品を把握します。"},
    {"q": "How are small, urgent packages sent?", "choices": ["By ship as freight.", "By the procurement team.", "By courier.", "On backorder."], "answer": 2, "expl": "第2段落。小さく急ぎの荷物は courier(宅配便)で送られ、重い freight(貨物)はトラックや船で運ばれます。"},
    {"q": "What happens to a popular item that is temporarily unavailable?", "choices": ["It is sold at wholesale.", "It is placed on backorder until the next consignment arrives.", "It is returned to the retailer.", "It is held at customs."], "answer": 1, "expl": "第3段落。品切れの人気商品は、次の consignment(入荷分)が届くまで backorder(取り寄せ注文)として登録されます。"}
  ]
});
window.__addPassage({
  "date": "2026-07-22",
  "level": "600",
  "theme": "マーケティング・広告",
  "title": "Planning the Summer Product Launch",
  "words": ["advertisement","campaign","consumer","demographic","endorse","feedback","impression","launch","loyalty","publicity","slogan","sponsor","survey","target","audience"],
  "passage": "When our company decided to [[launch]] a new line of eco-friendly water bottles, the marketing department began by conducting a [[survey]] of two thousand shoppers. The results helped us understand our [[target]] [[audience]]: most interested buyers belonged to a younger [[demographic]] of urban professionals. Based on this [[consumer]] data, we designed an advertising [[campaign]] built around a single, memorable [[slogan]]: \"Refresh the planet.\"\n\nTo increase [[publicity]], we placed an [[advertisement]] in several online magazines and asked a well-known athlete to [[endorse]] the product. Her support made a strong first [[impression]] on viewers and generated thousands of comments within a day. We also partnered with a local music festival, agreeing to [[sponsor]] the main stage in exchange for banner space.\n\nAfter the first month, we collected customer [[feedback]] through a short questionnaire. Many buyers praised the design and said they would recommend the bottle to friends, which is exactly the kind of brand [[loyalty]] we hoped to build. The positive response confirmed that understanding the [[consumer]] before spending money on advertising is the smartest way to reach the right [[audience]].",
  "passageJa": "当社が環境に優しい水筒の新シリーズを発売することを決めたとき、マーケティング部はまず2,000人の買い物客への調査から着手しました。その結果、当社のターゲット層が見えてきました。関心を示した購入者の多くは、都市部の若手社会人という比較的若い層に属していたのです。この消費者データをもとに、私たちは覚えやすい一つのスローガン「地球をリフレッシュしよう」を軸にした広告キャンペーンを設計しました。\n\n宣伝効果を高めるため、いくつかのオンライン雑誌に広告を掲載し、有名なスポーツ選手にその製品を推奨してもらうよう依頼しました。彼女の支持は視聴者に強い第一印象を与え、1日のうちに何千ものコメントを生み出しました。また地元の音楽フェスティバルと提携し、バナー掲載と引き換えにメインステージのスポンサーになることに合意しました。\n\n最初の1か月が過ぎた後、私たちは短いアンケートを通じて顧客からのフィードバックを集めました。多くの購入者がデザインを称賛し、友人にこの水筒を勧めたいと答えました。これはまさに私たちが築きたかったブランドへの愛顧です。この好意的な反応は、広告にお金をかける前に消費者を理解することこそが、適切な聴衆に届く最も賢い方法だと裏付けました。",
  "questions": [
    {"q": "What did the marketing department do first?", "choices": ["It placed an advertisement in magazines.", "It conducted a survey of shoppers.", "It sponsored a music festival.", "It created a new slogan."], "answer": 1, "expl": "第1段落。マーケティング部は最初に2,000人の買い物客への survey(調査)を実施しました。広告掲載・スポンサー・スローガン作成はいずれもその後の工程です。"},
    {"q": "Why was a famous athlete asked to endorse the product?", "choices": ["To design the water bottle.", "To conduct the customer survey.", "To increase publicity for the product.", "To reduce the advertising budget."], "answer": 2, "expl": "第2段落。宣伝効果(publicity)を高めるために有名選手に推奨を依頼し、それが強い第一印象につながりました。"},
    {"q": "In this passage, the word \"endorse\" is closest in meaning to", "choices": ["publicly support", "secretly criticize", "carefully measure", "quickly deliver"], "answer": 0, "expl": "endorse は「(公に)支持する・推奨する」の意味で、support / recommend に言い換えられます。Part 7 の同義語問題で頻出です。"}
  ]
});
window.__addPassage({
  "date": "2026-07-23",
  "level": "600",
  "theme": "施設・オフィス管理",
  "title": "Notice: Upcoming Building Renovation",
  "words": ["maintenance","renovation","premises","facility","tenant","occupancy","inspection","lease","vendor","relocate","spacious","adjacent","utility","custodian","corridor"],
  "passage": "To all [[tenant]]s of the Brookfield Business Center:\n\nWe are pleased to announce that a major [[renovation]] of our [[premises]] will begin next month. The goal is to modernize the building and improve every shared [[facility]], from the reception area to the meeting rooms. During this period, our [[custodian]] and a licensed [[vendor]] will work together to complete the upgrades with as little disruption as possible.\n\nPlease note the following. Routine [[maintenance]] of the heating system will take place during the first week, and a safety [[inspection]] of all floors is scheduled for the second week. To keep everyone safe, please do not store any items in the main [[corridor]], since it must remain clear at all times. There may be brief interruptions to certain [[utility]] services, such as water and electricity, but these will be announced in advance.\n\nOnce the work is finished, the building will offer more [[spacious]] offices and a new lounge [[adjacent]] to the lobby. Because [[occupancy]] has grown steadily, several teams will [[relocate]] to the newly opened fifth floor. Tenants who wish to expand their current space should contact the management office before their [[lease]] comes up for renewal. We appreciate your patience and look forward to welcoming you to an improved workplace.",
  "passageJa": "ブルックフィールド・ビジネスセンターの入居者の皆様へ:\n\n当ビルの大規模な改装を来月開始することをお知らせします。目的は建物を近代化し、受付エリアから会議室まで、共用のあらゆる設備を改善することです。この期間中、当ビルの用務員と免許を持つ業者が協力し、できるだけ支障の少ない形で改修を完了させます。\n\n以下にご注意ください。暖房システムの定期保守は第1週に行われ、全フロアの安全点検は第2週に予定されています。皆様の安全のため、正面の廊下には物を置かないでください。常に通路を確保しておく必要があるためです。水道や電気など一部の公共設備サービスに短時間の中断が生じる場合がありますが、これらは事前にお知らせします。\n\n工事が完了すると、ビルはより広々としたオフィスと、ロビーに隣接した新しいラウンジを提供します。入居率が着実に伸びているため、いくつかのチームは新たに開放される5階へ移転します。現在のスペースを拡張したい入居者は、賃貸契約の更新時期を迎える前に管理事務所へご連絡ください。ご辛抱に感謝するとともに、改善された職場に皆様をお迎えできることを楽しみにしています。",
  "questions": [
    {"q": "What is the main purpose of this notice?", "choices": ["To announce a rent increase", "To inform tenants about an upcoming renovation", "To advertise office space for new tenants", "To report the results of a customer survey"], "answer": 1, "expl": "第1段落で「大規模な改装を来月開始する」と告知し、以降で作業内容を説明しています。よって正解は1。0の家賃値上げ、2の新規入居者向けの宣伝、3の顧客調査結果はいずれも本文で触れられていません。"},
    {"q": "The word \"premises\" in paragraph 1 is closest in meaning to", "choices": ["employees", "building", "equipment", "schedule"], "answer": 1, "expl": "premisesは「建物・敷地」を意味し、ここでは改装対象の当ビルを指します。したがってbuilding(建物)が最も近い意味です。0のemployees(従業員)、2のequipment(設備)、3のschedule(予定)は語義が異なります。"},
    {"q": "Why are tenants asked not to store items in the corridor?", "choices": ["It is reserved for the vendor", "It must remain clear at all times", "It is being repainted this week", "It has no lighting during the work"], "answer": 1, "expl": "第2段落に「常に通路を確保しておく必要があるため物を置かないでください」とあり、安全確保が理由です。よって正解は1。0の業者専用、2の塗り直し、3の照明なしは本文に記載がありません。"}
  ]
});
window.__addPassage({
  "date": "2026-07-24",
  "level": "600",
  "theme": "出張・旅行（交通と宿泊）",
  "title": "Business Trip Arrangements for the Chicago Branch",
  "words": ["reservation", "confirm", "departure", "board", "luggage", "terminal", "layover", "fare", "lodging", "amenity", "concierge", "shuttle", "voucher", "reception", "delay"],
  "passage": "Dear Mr. Tanaka,\n\nThis email is to [[confirm]] the arrangements for your business trip to the Chicago branch next week. Your flight [[departure]] is scheduled for 8:00 a.m. from [[terminal]] 2. The company has already paid the [[fare]], so you do not need to buy a ticket. There will be a short [[layover]] in Denver, so please [[board]] your connecting flight promptly. In case of a [[delay]], the airline will send a message to your phone, and you may wait in the lounge. Please keep your [[luggage]] with you at all times.\n\nWe have made a [[reservation]] for you at the Lakeside Inn, and your [[lodging]] covers three nights. A free hotel [[shuttle]] runs from the airport, so you will not need a taxi. When you arrive, go to the [[reception]] desk and give your booking number to check in. A [[voucher]] for breakfast is included with your stay.\n\nThe hotel offers several [[amenity]] options, such as a fitness center and free Wi-Fi in every room. If you would like restaurant recommendations or help planning your evenings, the [[concierge]] in the lobby will be glad to assist you. Please review these details and reply if anything needs to be changed. We hope you have a smooth and productive trip.\n\nBest regards,\nThe Travel Desk",
  "passageJa": "田中様\n\nこのメールは、来週のシカゴ支店への出張の手配を確認するためのものです。ご搭乗便の出発は午前8時、ターミナル2からの予定です。運賃はすでに会社が支払っていますので、チケットを購入する必要はありません。デンバーで短い乗り継ぎ待ちがありますので、乗り継ぎ便には速やかにご搭乗ください。遅延が生じた場合は航空会社からお電話にメッセージが届きますので、ラウンジでお待ちいただけます。手荷物は常に身につけておいてください。\n\nレイクサイド・インにご予約を入れており、宿泊は3泊分が含まれます。空港からは無料のホテル送迎バスが運行していますので、タクシーは不要です。到着されましたら受付へ行き、予約番号を伝えてチェックインしてください。ご滞在には朝食の引換券が含まれます。\n\nホテルにはフィットネスセンターや全室無料Wi-Fiなど、いくつかの設備がございます。レストランのご紹介や夜の予定づくりのお手伝いが必要でしたら、ロビーのコンシェルジュが喜んで対応いたします。これらの詳細をご確認のうえ、変更が必要な点があればご返信ください。快適で実り多いご出張となりますよう。\n\n敬具\n出張手配デスク",
  "questions": [
    {"q": "What does Mr. Tanaka NOT need to do for this trip?", "choices": ["Buy a plane ticket", "Keep his luggage with him", "Give his booking number at the hotel", "Board the connecting flight quickly"], "answer": 0, "expl": "本文に「The company has already paid the fare, so you do not need to buy a ticket」とあり、チケット購入は不要。よって(0)が正解。(1)は「keep your luggage with you at all times」、(3)は「board your connecting flight promptly」、(2)は受付で予約番号を伝えるよう求められており、いずれも必要な行動なので誤り。"},
    {"q": "How will Mr. Tanaka get from the airport to the hotel?", "choices": ["By taxi", "By a free hotel shuttle", "By a rental car", "By train"], "answer": 1, "expl": "「A free hotel shuttle runs from the airport, so you will not need a taxi」とあり、無料の送迎バスで移動する。よって(1)が正解。(0)はタクシー不要と明記されているため誤り。(2)(3)は本文に記述がない。"},
    {"q": "The word \"delay\" in paragraph 1 is closest in meaning to", "choices": ["cancellation", "discount", "late departure", "upgrade"], "answer": 2, "expl": "delay は「遅延・遅れ」の意味で、ここでは便の出発が遅れることを指す。最も近いのは(2)late departure。(0)cancellation は「欠航・取り消し」で意味が異なる。(1)discount(割引)、(4相当)upgrade(格上げ)はいずれも遅延の意味とは無関係で誤り。"}
  ]
});
window.__addPassage({
  "date": "2026-07-25",
  "level": "600",
  "theme": "会議・イベント運営（社内会議とカンファレンス）",
  "title": "Notice: Annual Sales Conference on September 12",
  "words": ["agenda", "attendee", "venue", "keynote", "registration", "session", "handout", "moderator", "refreshments", "auditorium", "brochure", "exhibit", "badge", "catering", "workshop"],
  "phrases": ["sign up for", "take part in", "hand out", "take place", "refrain from -ing"],
  "passage": "To: All Sales Staff\nFrom: Ellen Park, Events Office\nSubject: Annual Sales Conference on September 12\n\nThis year's sales conference will [[take place]] on Friday, September 12. The [[venue]] has been moved to the Fairmont Center on Third Avenue, which is much larger than our old meeting hall. The full [[agenda]] is attached to this message, and a [[brochure]] with floor maps and room numbers will be mailed to every office next week.\n\n[[Registration]] opens at 8:30 a.m. in the lobby. Each [[attendee]] must pick up a name [[badge]] there, because staff members without one cannot enter the main [[auditorium]]. The [[keynote]] starts at 9:00 and will be given by our regional director. Ms. Diaz will serve as [[moderator]] and will introduce each speaker.\n\nIn the afternoon you may choose one discussion [[session]] and one hands-on [[workshop]]. You need to [[sign up for]] the workshop in advance, since each one is limited to twenty people. Volunteers will [[hand out]] folders at the door, and a [[handout]] for every talk is inside, so you do not have to print anything yourself. Ten partner companies will also [[exhibit]] their newest software in Room B, and everyone is welcome to [[take part in]] the demonstrations there.\n\nLight [[refreshments]] will be served at 10:30 and again at 3:00, and the [[catering]] for the evening banquet has been arranged with a restaurant next to the center. Please [[refrain from bringing]] outside food into the meeting rooms. If you have any questions about travel or schedules, contact the Events Office by August 29.",
  "passageJa": "宛先: 営業部の皆さん\n差出人: エレン・パーク（イベント事務局）\n件名: 9月12日の年次営業会議について\n\n今年の営業会議は9月12日（金）に開催されます。会場は3番街のフェアモント・センターに変更になりました。以前の会議ホールよりずっと広い場所です。全体の議題はこのメッセージに添付しており、フロアマップと部屋番号が載ったパンフレットを来週各オフィスに郵送します。\n\n受付は午前8時30分にロビーで開始します。出席者は各自そこで名札を受け取ってください。名札のない社員はメインの講堂に入れません。基調講演は9時に始まり、地域統括ディレクターが行います。ディアスさんが司会を務め、各講演者を紹介します。\n\n午後は、討論の分科会を1つと実践形式の研修会を1つ選べます。研修会は各回20名までのため、事前に申し込む必要があります。入口で係の者がフォルダーを配布し、その中に各講演の配布資料が入っていますので、ご自身で印刷する必要はありません。また、提携企業10社がB室で最新のソフトウェアを展示します。どなたでもその実演に参加できます。\n\n軽食は10時30分と午後3時に提供します。夜の宴会の仕出しは、センター隣のレストランに手配済みです。外部から持ち込んだ食べ物を会議室に持ち込むのはお控えください。移動や日程についてご質問があれば、8月29日までにイベント事務局までご連絡ください。",
  "questions": [
    {"q": "What must staff members do before entering the main auditorium?", "choices": ["Pay a registration fee", "Pick up a name badge in the lobby", "Send an email to Ms. Diaz", "Print their own handouts"], "answer": 1, "expl": "第2段落に「Each attendee must pick up a name badge there, because staff members without one cannot enter the main auditorium」とあり、ロビーで名札を受け取る必要がある。よって(1)が正解。(0)参加費の記述はない。(2)ディアスさんは司会者で、連絡先はイベント事務局なので誤り。(3)配布資料はフォルダーに入っており自分で印刷する必要はないと述べられているため誤り。"},
    {"q": "The word \"venue\" in paragraph 1 is closest in meaning to", "choices": ["location", "deadline", "budget", "audience"], "answer": 0, "expl": "venue は「会場・開催地」で、ここでは会議を行う場所を指す。最も近いのは(0)location。(1)deadline は「締切」、(2)budget は「予算」、(3)audience は「聴衆」で、いずれも場所を表す語ではないため誤り。"},
    {"q": "The phrase \"refrain from bringing\" in paragraph 4 is closest in meaning to", "choices": ["remember to bring", "be allowed to bring", "avoid bringing", "insist on bringing"], "answer": 2, "expl": "refrain from -ing は「～するのを控える」という丁寧な禁止表現で、(2)avoid bringing が同義。(0)は「持って来るのを忘れずに」で逆の意味。(1)は「持ち込んでよい」で許可の意味になり誤り。(3)は「持ち込むと言い張る」で意味が通らない。"}
  ]
});
window.__addPassage({
  "date": "2026-07-26",
  "level": "600",
  "theme": "顧客対応・クレーム処理（カスタマーサービス）",
  "title": "Memo: New Steps for Handling Customer Complaints",
  "words": ["complaint", "apologize", "defective", "replacement", "courteous", "representative", "inconvenience", "satisfaction", "resolve", "exchange", "prompt", "compensation", "dissatisfied", "policy", "assistance"],
  "phrases": ["apologize for -ing", "deal with", "get in touch with", "free of charge", "look into"],
  "passage": "To: All Front Desk Staff\nFrom: Daniel Okoye, Customer Care Manager\nSubject: New Steps for Handling Customer Complaints\n\nLast month we received forty-two [[complaints]] about our home appliance line, twice as many as in April. Most callers were [[dissatisfied]] not with the products but with how slowly we answered them. Starting Monday, every [[representative]] will follow the steps below.\n\nFirst, listen to the whole story before you speak, and stay [[courteous]] even when the caller is angry. Always [[apologize]] for the [[inconvenience]] first, since a short apology often [[resolves]] a call before it grows into a bigger problem. If a customer reports a [[defective]] item, do not argue. Offer to [[exchange]] it or send a [[replacement]], and explain that shipping is [[free of charge]] under our warranty [[policy]].\n\nSecond, promise only what you can deliver. If you cannot answer at once, say that you will [[look into]] the matter and then [[get in touch with]] the customer within one business day. A [[prompt]] callback matters more to most people than a long explanation.\n\nThird, record every case in the online system. Our support team [[deals with]] repeat cases each week, and your notes help them decide whether [[compensation]] is appropriate. When we miss a promised delivery date, please also [[apologize for missing]] it in writing, not only by phone.\n\nWe would like your [[assistance]] in testing these steps for one month. The training slides are on the shared drive, and I will visit each floor on Wednesday afternoon. Our goal is a [[satisfaction]] score above ninety percent by December.",
  "passageJa": "宛先: フロント対応スタッフの皆さん\n差出人: ダニエル・オコエ（カスタマーケア部長）\n件名: 顧客からの苦情対応の新しい手順について\n\n先月、当社の家庭用電化製品ラインについて42件の苦情が寄せられました。4月の2倍の件数です。多くのお客様は、製品そのものではなく、こちらの回答が遅いことに不満を持っていました。月曜から、担当者は全員、以下の手順に従ってください。\n\n第一に、話し始める前に事情を最後まで聞き、相手が怒っていても丁寧な態度を保つこと。まず必ずご迷惑をおかけしたことをおわびしてください。短い謝罪の一言で、問題が大きくなる前に解決する電話は少なくありません。お客様が不良品だと伝えてきた場合は、言い返さないこと。交換するか交換品を送ることを申し出て、保証規定により送料は無料である旨を説明してください。\n\n第二に、実行できることだけを約束すること。その場で答えられない場合は、この件は調査したうえで、1営業日以内にこちらから連絡すると伝えてください。多くのお客様にとっては、長い説明よりも迅速な折り返しの連絡のほうが重要です。\n\n第三に、すべての案件をオンラインシステムに記録すること。サポートチームは毎週、繰り返し発生している案件に対処しており、皆さんの記録は補償が妥当かどうかを判断する助けになります。約束した納品日に間に合わなかったときは、電話だけでなく書面でもおわびしてください。\n\n1か月間、この手順の試行に協力をお願いします。研修用のスライドは共有ドライブにあり、水曜の午後に各フロアを回ります。12月までに満足度90パーセント超えを目標とします。",
  "questions": [
    {"q": "What should staff do if they cannot answer a customer's question immediately?", "choices": ["Transfer the call to Mr. Okoye", "Send a written apology the same day", "Contact the customer again within one business day", "Offer compensation right away"], "answer": 2, "expl": "第3段落に「say that you will look into the matter and then get in touch with the customer within one business day」とあり、1営業日以内に折り返し連絡すると伝えるよう指示されている。よって(2)が正解。(0)電話を転送する記述はない。(1)書面でのおわびは納品日に間に合わなかった場合の話で、条件が異なる。(3)補償はサポートチームが記録をもとに判断するものなので、その場で申し出るのは誤り。"},
    {"q": "The word \"prompt\" in paragraph 3 is closest in meaning to", "choices": ["quick", "polite", "detailed", "unexpected"], "answer": 0, "expl": "prompt は「迅速な、即座の」の意味で、ここでは折り返しの連絡が速いことを表す。最も近いのは(0)quick。(1)polite は「礼儀正しい」で、この文では速さが論点なので誤り。(2)detailed は「詳細な」だが、直後で「長い説明よりも重要」と対比されており逆の内容。(3)unexpected は「予期しない」で意味が通らない。"},
    {"q": "The phrase \"look into\" in paragraph 3 is closest in meaning to", "choices": ["glance at", "investigate", "take care of", "postpone"], "answer": 1, "expl": "look into は「～を調査する、詳しく調べる」の意味で、(1)investigate が同義。(0)glance at は「ちらりと見る」で、視線を向ける look at に近く意味が浅い。(2)take care of は「世話をする、処理する」で look after に近く、調査の意味はない。(3)postpone は「延期する」で、1営業日以内に連絡するという文脈と矛盾する。"}
  ]
});
window.__addPassage({
  "date": "2026-07-27",
  "level": "600",
  "theme": "製造・品質管理（工場と品質保証）",
  "title": "Memo: Results of the June Quality Review at the Riverton Plant",
  "words": ["manufacture", "assembly", "component", "plant", "output", "productivity", "specification", "durable", "malfunction", "flaw", "certify", "streamline", "shift", "quota", "compliance"],
  "phrases": ["comply with", "be equipped with", "result in", "keep track of", "shut down"],
  "passage": "To: All Production Staff\nFrom: Helena Cruz, Quality Assurance Director\nSubject: Results of the June Quality Review\n\nOur Riverton [[plant]] now [[manufactures]] more than nine thousand portable heaters a month, and total [[output]] rose eleven percent in June. Even so, last week's review found a small [[flaw]] in the plastic housing of Model 40, and three units began to [[malfunction]] during final testing.\n\nEngineering traced the trouble to a single [[component]] delivered by a new vendor. The part did not match the [[specification]] listed in our purchase order, and the vendor has been asked to [[comply with]] our written standards before the next delivery. From this week, every incoming box is weighed and measured at the gate, and our inspectors [[keep track of]] each lot in a shared file.\n\nStarting Monday, the second [[shift]] will move to the redesigned [[assembly]] station, which [[is equipped with]] two new torque meters. The change should [[streamline]] the line and raise [[productivity]] without a longer workday. We do not expect the new checks to [[result in]] a lower monthly [[quota]]; in fact, managers plan to raise the figure slightly in September once the meters are in regular use.\n\nPlease remember that a [[durable]] product protects our name. Any lot that fails two checks must be held aside, and the line will [[shut down]] until the cause is found. Our heaters are [[certified]] by the national safety board, and continued [[compliance]] with those rules depends on the care each of you takes at every step. I will visit both shifts on Thursday to answer questions.",
  "passageJa": "宛先: 製造部門の皆さん\n差出人: ヘレナ・クルーズ（品質保証部長）\n件名: 6月の品質レビュー結果について\n\nリバートン工場では現在、携帯用暖房器具を月9,000台超製造しており、6月の総生産高は11パーセント増加しました。それでも先週のレビューで、モデル40の樹脂製ケースに小さな欠陥が見つかり、最終試験中に3台が正常に作動しない状態になりました。\n\n技術部門は、その原因を新しい業者から納入された1つの部品にあると特定しました。この部品は当社の注文書に記載された仕様と一致しておらず、次回納入までに当社の定めた基準に従うよう業者に要請済みです。今週から、入荷する箱はすべて入り口で重量と寸法を測定し、検査員が共有ファイルで各ロットを記録・把握します。\n\n月曜からは、第2交代勤務の担当者が、トルク計2台を新たに備えた改良版の組立作業台に移ります。この変更により、勤務時間を延ばすことなくラインを効率化し、生産性を高められるはずです。新しい検査が月間ノルマの引き下げにつながることはないと考えています。むしろ管理職は、トルク計が本格運用に入る9月には数値をやや引き上げる予定です。\n\n耐久性のある製品こそが当社の名前を守るということを忘れないでください。検査に2回不合格となったロットは必ず隔離し、原因が判明するまでラインは停止します。当社の暖房器具は国の安全委員会の認証を受けており、その規則を守り続けられるかどうかは、皆さん一人ひとりの各工程での注意にかかっています。木曜には両方の交代勤務を回り、質問にお答えします。",
  "questions": [
    {"q": "What did the June review reveal about Model 40?", "choices": ["Its price was higher than planned", "A part from a new vendor did not match the specification", "The assembly station was too small for the second shift", "The national safety board withdrew its approval"], "answer": 1, "expl": "第1段落で樹脂製ケースの欠陥と作動不良が報告され、第2段落で「Engineering traced the trouble to a single component delivered by a new vendor. The part did not match the specification listed in our purchase order」と原因が示されている。よって(1)が正解。(0)価格の話は本文にない。(2)組立作業台は改良されて第2交代勤務が移るという内容で、狭さの指摘はない。(3)認証は現在も有効で、取り消しの記述はない。"},
    {"q": "The word \"output\" in paragraph 1 is closest in meaning to", "choices": ["production", "profit", "delivery", "demand"], "answer": 0, "expl": "output は「生産高、産出量」の意味で、月9,000台超という生産数量の話をしている。最も近いのは(0)production。(1)profit は「利益」で金額の話になり、本文は台数の増加を述べているので誤り。(2)delivery は「配送」で、出荷ではなく生産量が論点。(3)demand は「需要」で、売れ行きの話は出てこない。"},
    {"q": "The phrase \"keep track of\" in paragraph 2 is closest in meaning to", "choices": ["speed up", "monitor", "give up", "pay for"], "answer": 1, "expl": "keep track of は「～を把握する、記録し続ける」の意味で、検査員が各ロットを共有ファイルで管理していることを表す。よって(1)monitor が同義。(0)speed up は「加速する」で、記録の意味はない。(2)give up は「あきらめる」で、むしろ lose track of とも異なる。(3)pay for は「代金を払う」で文脈に合わない。"}
  ]
});
window.__addPassage({
  "date": "2026-07-28",
  "level": "600",
  "theme": "IT・システム（社内システムとサポート）",
  "title": "Notice: Weekend Work on the Company Portal",
  "words": ["install", "upgrade", "compatible", "access", "technician", "troubleshoot", "downtime", "glitch", "restore", "migrate", "implement", "authorize", "subscription", "outage", "secure"],
  "phrases": ["log in to", "back up", "be compatible with", "take effect", "in advance"],
  "passage": "To: All Employees\nFrom: Dana Whitfield, IT Services Manager\nSubject: Weekend Work on the Company Portal\n\nOver the weekend our team will [[upgrade]] the company portal and [[migrate]] every department's files to a faster machine. The work starts at 8:00 P.M. on Saturday, and the change will [[take effect]] on Monday morning. Please [[back up]] any document you are editing [[in advance]], because the system will not be available while the transfer runs.\n\nWe expect about six hours of [[downtime]]. During that period no one will be able to [[log in to]] the portal, and remote [[access]] to the shared drives will be turned off as well. This is a planned pause, not an unexpected [[outage]], so there is no need to call the help desk about it. If service is not [[restored]] by 6:00 A.M. on Sunday, we will post a notice on the front page of the intranet.\n\nOn Monday a short list of steps will be waiting in your inbox. You will need to [[install]] a small update before the portal opens, and you should check that your browser [[is compatible with]] the new design. Some older tablets may not run it, but a [[compatible]] model can be borrowed from the equipment room on the third floor. A [[technician]] will be on each floor until noon to [[troubleshoot]] any [[glitch]] that appears.\n\nFinally, the new portal is far more [[secure]] than the old one. Only managers are [[authorized]] to approve accounts for outside guests, and every team's software [[subscription]] will be reviewed before we [[implement]] the next set of security rules in September.",
  "passageJa": "宛先: 社員の皆さん\n差出人: ダナ・ホイットフィールド（ITサービス課長）\n件名: 週末の社内ポータル作業について\n\n今週末、当チームは社内ポータルを更新し、全部門のファイルをより高速な機器へ移行します。作業は土曜の午後8時に開始し、変更は月曜の朝から効力を生じます。転送中はシステムを利用できないため、編集中の文書は前もってバックアップを取っておいてください。\n\n停止時間は約6時間を見込んでいます。その間はポータルにログインできず、共有ドライブへの遠隔からの接続も遮断されます。これは計画された停止であり、予期しない停止ではありませんので、ヘルプデスクへの連絡は不要です。日曜の午前6時までにサービスが復旧しない場合は、社内サイトのトップページにお知らせを掲示します。\n\n月曜には、手順をまとめた短い一覧が受信箱に届いています。ポータルを開く前に小さな更新プログラムを導入する必要があり、使用中のブラウザーが新しい画面設計と互換性があるかを確認してください。古いタブレットの中には動作しないものもありますが、互換性のある機種を3階の備品室で借りられます。技術者が正午まで各フロアに待機し、発生した不具合を診断して解決します。\n\n最後に、新しいポータルは以前のものよりはるかに安全です。社外の来訪者用アカウントを承認できるのは管理職だけであり、各チームのソフトウェア契約についても、9月に次の安全規則を実施する前に見直します。",
  "questions": [
    {"q": "What are employees asked to do before the work begins?", "choices": ["Return older tablets to the equipment room", "Save copies of the documents they are editing", "Report the planned pause to the help desk", "Renew their software subscription"], "answer": 1, "expl": "第1段落最後に「Please back up any document you are editing in advance」とあり、作業前に編集中の文書のバックアップを取るよう求めている。よって(1)が正解。(0)古いタブレットは返却ではなく、互換性のある機種を借りられるという話。(2)本文は「計画された停止なのでヘルプデスクへの連絡は不要」と述べており逆。(3)契約の見直しは9月にIT側が行うことで、社員への依頼ではない。"},
    {"q": "The word \"restored\" in paragraph 2 is closest in meaning to", "choices": ["brought back", "canceled", "delayed", "reduced"], "answer": 0, "expl": "restore は「復旧する、元に戻す」の意味で、ここでは停止していたサービスが再び使える状態に戻ることを指す。最も近いのは(0)brought back。(1)canceled は「中止された」で、サービスが戻る意味はない。(2)delayed は「遅れた」で、6時までに復旧しない場合という条件の内容とずれる。(3)reduced は「削減された」で、量の話になり文脈に合わない。"},
    {"q": "The phrase \"in advance\" in paragraph 1 is closest in meaning to", "choices": ["beforehand", "in person", "free of charge", "by mistake"], "answer": 0, "expl": "in advance は「前もって、事前に」の意味で、システム停止より前にバックアップを取るよう求めている。よって(0)beforehand が同義。(1)in person は「直接会って」で、方法の話ではない。(2)free of charge は「無料で」、(3)by mistake は「誤って」で、いずれも時期を表す語ではないため誤り。"}
  ]
});
window.__addPassage({
  "date": "2026-07-29",
  "level": "600",
  "theme": "契約・交渉",
  "title": "Memo: Renewal of the Harborline Logistics Agreement",
  "words": ["contract", "negotiate", "clause", "provision", "amend", "renew", "obligation", "valid", "draft", "extension", "attorney", "binding", "breach", "confidential", "mutual"],
  "phrases": ["on behalf of", "be subject to", "in accordance with", "enter into", "agree to do"],
  "passage": "MEMORANDUM\nTo: All Department Managers\nFrom: Elena Ruiz, Legal Affairs\nDate: 29 July\n\nOur five-year service [[contract]] with Harborline Logistics will expire on 31 October. Since May, the Legal Affairs team has [[negotiated]] new terms [[on behalf of]] the entire company, and last week our outside [[attorney]] finished reviewing the second [[draft]] of the renewal document. The current agreement remains [[valid]] until the expiration date, so daily shipping operations will not be affected in any way this quarter.\n\nThe revised text [[amends]] three areas. First, the delivery [[clause]] now requires Harborline to notify us within two hours of any delay at a port or warehouse. Second, a new [[provision]] limits annual price increases to three percent. Third, all pricing information is treated as [[confidential]] and may not be shared with third parties. These changes reflect a [[mutual]] effort to reduce risk: in return for the price cap, we accept the [[obligation]] to submit shipping forecasts at the start of each quarter.\n\nIf we [[renew]] the agreement, the final text will [[be subject to]] approval by both boards, and every shipment must then be handled [[in accordance with]] the updated safety standards described in Appendix B. Once the document is signed, it becomes legally [[binding]] on both companies, and any [[breach]] may result in termination with thirty days' notice.\n\nIf the board decides not to [[enter into]] another long-term arrangement, we will instead request a six-month [[extension]] of the current terms while we invite bids from other carriers. Managers who [[agree to adopt]] the new forecasting format should send written confirmation to Legal Affairs by 5 August.",
  "passageJa": "社内連絡\n宛先: 各部門管理職各位\n差出人: 法務部 エレナ・ルイス\n日付: 7月29日\n\nハーバーライン物流との5年間の業務契約は10月31日で満了します。5月以降、法務部のチームが全社を代表して新しい条件を交渉してきました。先週には社外の弁護士が更新書類の第2稿の確認を終えています。現行の合意は満了日まで有効ですので、今四半期の日々の出荷業務に影響はありません。\n\n改訂版では3つの箇所が修正されています。第一に、配送条項では、港や倉庫での遅延が生じた場合、ハーバーラインは2時間以内に当社へ通知することが必要になりました。第二に、新しい条項が年間の値上げを3パーセントまでに制限します。第三に、価格情報はすべて機密として扱われ、第三者と共有することはできません。これらの変更はリスクを減らそうとする相互の努力を反映したものです。価格の上限と引き換えに、当社は各四半期の初めに出荷予測を提出する義務を負います。\n\n合意を更新する場合、最終的な文面は両社の取締役会の承認の対象となり、その後はすべての出荷を付属書Bに記載された最新の安全基準に従って扱う必要があります。書類に署名がなされれば、それは両社に対して法的な拘束力を持ち、いかなる違反も30日前の通知による契約解除につながる可能性があります。\n\n取締役会が新たな長期の取り決めを結ばないと決めた場合は、代わりに現行条件の6か月の延長を要請し、その間に他の運送業者から入札を募ります。新しい予測の提出形式の採用に同意する管理職は、8月5日までに法務部へ書面で確認を送ってください。",
  "questions": [
    {"q": "What is the main purpose of the memo?", "choices": ["To announce that a supplier has been replaced", "To explain the status and content of a contract renewal", "To report a safety accident at a warehouse", "To invite managers to a training session on shipping"], "answer": 1, "expl": "第1段落で契約の満了時期と交渉の進捗を伝え、第2段落以降で修正点と今後の手続きを説明しています。よって「契約更新の状況と内容の説明」が目的です。(A)は他社への切り替えは延長時の入札募集として仮定の話に留まるため不可。(C)の事故の記述はありません。(D)の研修の案内もありません。"},
    {"q": "In paragraph 1, the word \"valid\" is closest in meaning to", "choices": ["popular", "in force", "flexible", "expensive"], "answer": 1, "expl": "ここでの valid は「(契約が)効力を持っている」という意味で、満了日まで効力が続くことを述べています。したがって in force(効力がある)が最も近い意味です。(A) popular は「人気がある」、(C) flexible は「柔軟な」、(D) expensive は「高価な」で、いずれも効力の有無を表しません。"},
    {"q": "What does the phrase \"be subject to\" mean in paragraph 3?", "choices": ["to be exempt from something", "to require or depend on something", "to be written in a formal style", "to be delivered ahead of schedule"], "answer": 1, "expl": "be subject to ~ は「～の対象となる、～次第である」の意味で、ここでは最終文面が両社の取締役会の承認を必要とすることを表します。よって「必要とする・依存する」が正解です。(A)は逆の意味の「免除される」。(C)は文体の話で無関係。(D)は納品時期の話で本文に対応しません。"}
  ]
});
window.__addPassage({
  "date": "2026-07-30",
  "level": "600",
  "theme": "環境・サステナビリティ",
  "title": "Notice: The Green Desk Program Begins in September",
  "words": ["recycle", "conserve", "sustainable", "initiative", "dispose", "waste", "reduce", "renewable", "efficiency", "packaging", "emission", "container", "awareness", "contribute", "donate"],
  "phrases": ["dispose of A", "be committed to -ing", "cut down on A", "be aware of A", "in an effort to do"],
  "passage": "NOTICE\nTo: All Staff\nFrom: Facilities Management, Halverson Industries\nDate: 30 July\n\nBeginning on 1 September, Halverson Industries will launch a [[sustainable]] office program called Green Desk. This [[initiative]] is designed to [[reduce]] the amount of [[waste]] our offices produce each year and to [[conserve]] energy in all six buildings on the Riverside campus. Senior management [[is committed to lowering]] the company's environmental impact, and every department is expected to take part.\n\nUnder Green Desk, employees will [[recycle]] paper, plastic, and glass in the blue [[containers]] placed on every floor. Batteries and old electronics must not go into these bins. Instead, please [[dispose of used batteries]] at the collection point near the loading dock. Confidential documents will continue to be [[disposed]] of by our shredding service, as they are today. The cafeteria will also [[cut down on the use of]] single-use [[packaging]]; washable dishes and cups will be provided at no cost to staff.\n\nTo improve energy [[efficiency]], the maintenance team will install motion sensors in the meeting rooms and hallways during the last week of August. In addition, the company has signed an agreement to buy forty percent of its electricity from a [[renewable]] source, which should lower our annual carbon [[emissions]] considerably. [[In an effort to raise]] [[awareness]], Facilities Management will hold a thirty-minute briefing on 20 August at 10:00 A.M. in the main auditorium. All staff should [[be aware of the new sorting rules]] before the program begins.\n\nEmployees who want to [[contribute]] more may join the Green Desk committee, which meets on the first Friday of each month. For every department that reaches its yearly target, the company will [[donate]] five hundred dollars to a local tree-planting fund. Please send any questions to facilities@halverson-ind.example.",
  "passageJa": "お知らせ\n宛先: 全職員\n差出人: Halverson Industries 施設管理部\n日付: 7月30日\n\n9月1日より、Halverson Industries は Green Desk という持続可能なオフィスプログラムを開始します。この取り組みは、当社のオフィスが毎年出す廃棄物の量を減らし、Riverside キャンパスの6棟すべてでエネルギーを節約することを目的としています。経営陣は当社の環境負荷を下げることに全力で取り組んでおり、全部署が参加することを想定しています。\n\nGreen Desk のもとで、従業員は各階に置かれた青い容器で紙、プラスチック、ガラスをリサイクルします。電池や古い電子機器はこれらの箱に入れないでください。使用済み電池は、搬入口近くの回収場所で処分してください。機密書類はこれまでどおり当社の細断サービスによって処分されます。カフェテリアも使い捨て包装の使用を減らします。洗って使える食器とカップが職員に無料で提供されます。\n\nエネルギー効率を高めるため、施設管理部は8月最終週に会議室と廊下へ人感センサーを設置します。さらに当社は電力の40パーセントを再生可能な電源から購入する契約を締結しており、これにより年間の炭素排出量が大幅に下がる見込みです。意識を高めようと、施設管理部は8月20日午前10時からメインホールで30分の説明会を開きます。全職員はプログラム開始前に新しい分別ルールを承知しておいてください。\n\nさらに貢献したい従業員は、毎月第1金曜日に開かれる Green Desk 委員会に参加できます。年間目標を達成した部署ごとに、当社は地元の植樹基金へ500ドルを寄付します。質問は facilities@halverson-ind.example までお送りください。",
  "questions": [
    {"q": "What is the main purpose of the notice?", "choices": ["To announce a new environmental program", "To report the results of an energy audit", "To ask employees for donations", "To introduce a new cafeteria menu"], "answer": 0, "expl": "第1段落で「9月1日より Green Desk という持続可能なオフィスプログラムを開始する」と述べ、以降で内容を説明しているため(A)が正解です。(B)監査の結果は述べられていません。(C)寄付をするのは会社であり、従業員に求めてはいません。(D)カフェテリアの記述は包装の削減と食器の提供であり、新メニューの案内ではありません。"},
    {"q": "In paragraph 1, the word \"conserve\" is closest in meaning to", "choices": ["expand", "save", "inspect", "announce"], "answer": 1, "expl": "conserve は「(資源を)節約する」で、ここでは6棟でエネルギーを節約する文脈です。したがって save が最も近い意味になります。(A)expand は「拡大する」で逆方向です。(C)inspect は「点検する」、(D)announce は「発表する」で、いずれもエネルギーを減らすという意味を持ちません。"},
    {"q": "In paragraph 2, the phrase \"cut down on\" is closest in meaning to", "choices": ["pay for", "search for", "reduce the use of", "deliver"], "answer": 2, "expl": "cut down on A は「～を減らす、切り詰める」という意味です。直後に「洗って使える食器を提供する」とあることからも、使い捨て包装の使用を減らす流れだと分かります。(A)pay for は「～の代金を払う」、(B)search for は「～を探す」、(D)deliver は「配達する」で、いずれも削減の意味を持ちません。なお cut down A(木を切り倒す)とは意味が異なる点にも注意します。"}
  ]
});
window.__addPassage({
  "date": "2026-07-31",
  "level": "600",
  "theme": "研修・能力開発",
  "title": "Memo: The Autumn Skills Program",
  "words": ["seminar", "instructor", "enroll", "mandatory", "curriculum", "proficiency", "evaluate", "assignment", "participant", "lecture", "trainee", "objective", "acquire", "optional", "conduct"],
  "phrases": ["be eligible for A", "take advantage of A", "participate in A", "consist of A", "no later than A"],
  "passage": "MEMORANDUM\nTo: All Branch Staff\nFrom: Rina Delgado, Learning and Development\nDate: 31 July\nSubject: The Autumn Skills Program\n\nLearning and Development will [[conduct]] a new training program at every branch office this autumn. The main [[objective]] of the program is to help staff [[acquire]] the practical skills our clients now expect, especially in written communication and basic data analysis.\n\nThe [[curriculum]] [[consists of]] three parts. The first part is a two-day [[seminar]] led by an outside [[instructor]], Mr. Haruki Sato, who has trained employees at several regional banks. The second part is a series of short online [[lectures]] that each [[participant]] may watch at any time. The third part is a written [[assignment]] based on a real customer case. Every [[trainee]] must submit this work [[no later than]] 30 November, and department managers will [[evaluate]] it using the standard company rubric.\n\nThe two-day [[seminar]] is [[mandatory]] for all client-facing employees. The online [[lectures]] are [[optional]], but we strongly encourage you to [[take advantage of]] them, because they cover the language [[proficiency]] topics that appear most often in customer complaints. Staff members who have completed one full year of service [[are eligible for]] the advanced module in January as well.\n\nTo [[enroll]], please open the Learning Portal and select Autumn Skills from the course menu. Employees who cannot [[participate in]] the November sessions may join the March group instead. Please contact me at extension 4120 if you have any questions.",
  "passageJa": "社内連絡\n宛先: 全支店スタッフ\n差出人: リナ・デルガード(人材開発部)\n日付: 7月31日\n件名: 秋期スキルプログラム\n\n人材開発部は、この秋、全支店で新しい研修プログラムを実施します。このプログラムの主な目標は、とくに文書によるコミュニケーションと基礎的なデータ分析の分野で、顧客が今求めている実務的な技能をスタッフが習得できるようにすることです。\n\nカリキュラムは3つの部分から成ります。第1部は、外部講師の佐藤春樹氏が担当する2日間のセミナーです。同氏は複数の地方銀行で従業員を指導してきました。第2部は短いオンライン講義のシリーズで、各参加者は好きな時間に視聴できます。第3部は、実際の顧客事例に基づく書面の課題です。研修生は全員、遅くとも11月30日までにこの課題を提出しなければならず、部門の管理職が社の標準評価基準を用いて評価します。\n\n2日間のセミナーは、顧客と直接接する従業員全員にとって必須です。オンライン講義は任意ですが、ぜひ活用してください。顧客からの苦情に最も多く現れる言語運用力の項目を扱っているためです。勤続1年を満了したスタッフは、1月の上級モジュールを受講する資格もあります。\n\n登録するには、ラーニングポータルを開き、コースメニューから Autumn Skills を選んでください。11月の回に参加できない従業員は、代わりに3月のグループに加わることができます。質問がある場合は内線4120まで連絡してください。",
  "questions": [
    {"q": "According to the memo, which part of the program is NOT required?", "choices": ["The two-day seminar", "The online lectures", "The written assignment", "The advanced module in January"], "answer": 1, "expl": "第3段落に The online lectures are optional とあり、オンライン講義だけが任意です。(A)のセミナーは同じ段落で mandatory と明記されています。(C)の課題は第2段落で Every trainee must submit と義務が示されています。(D)の1月の上級モジュールは「必須でない」とは書かれておらず、勤続1年という受講資格の条件が述べられているだけなので、本文の記述から必須・任意の判断はできません。"},
    {"q": "In paragraph 1, the word \"acquire\" is closest in meaning to", "choices": ["purchase", "obtain", "replace", "postpone"], "answer": 1, "expl": "ここでは acquire the practical skills(実務的な技能を習得する)の意味なので、obtain(得る)が最も近い言い換えです。(A) purchase は「金銭で購入する」で、acquire に「買収する」の意味はあっても skills には使えません。(C) replace は「取り替える」、(D) postpone は「延期する」で、いずれも文脈に合いません。"},
    {"q": "What does the phrase \"take advantage of\" mean in paragraph 3?", "choices": ["to make use of something", "to complain about something", "to pay extra for something", "to be excused from something"], "answer": 0, "expl": "take advantage of A は「Aを利用する、活用する」で、make use of A と同義です。ここでは任意のオンライン講義を活用するよう勧める文脈です。(B)は苦情を述べる意味で、本文では苦情は講義が扱う話題として触れられているだけです。(C)の追加料金や(D)の免除に相当する記述は本文にありません。"}
  ]
});
window.__addPassage({
  "date": "2026-08-01",
  "level": "600",
  "theme": "飲食・接客サービス（レストラン運営）",
  "title": "Harborview Bistro: A New Favorite on Maple Street",
  "words": ["cuisine", "ingredient", "beverage", "appetizer", "patron", "banquet", "hospitality", "specialty", "atmosphere", "greet", "dine", "serve", "rave", "reasonable", "seasonal"],
  "phrases": ["be known for A", "rave about A", "a variety of A", "upon arrival", "in addition to A"],
  "passage": "Since it opened last spring, Harborview Bistro [[is known for]] two things: warm [[hospitality]] and a quiet, comfortable [[atmosphere]]. The restaurant [[serves]] regional [[cuisine]] made with [[ingredients]] from farms within thirty kilometers of the city, and the [[seasonal]] menu is rewritten four times a year.\n\n[[Upon arrival]], guests are [[greeted]] at the door by a host who describes the evening's [[specialty]]. The kitchen offers [[a variety of]] [[appetizers]] that are designed to be shared, and [[in addition to]] the wine list, the bar keeps more than twenty non-alcoholic [[beverages]]. Prices are [[reasonable]] for the neighborhood: most main dishes cost between fourteen and nineteen dollars, and the set lunch is only eleven.\n\nRegular [[patrons]] [[rave about]] the seafood stew, and local food writers have [[raved]] about the bread as well. On weekends, families [[dine]] in the garden room at the back, where children are welcome until nine o'clock. The hall on the second floor can be booked for a [[banquet]] of up to sixty guests, and the owner reports that corporate customers now reserve it several months ahead for year-end parties.\n\nHarborview Bistro is open Tuesday through Sunday, from 11:30 A.M. to 10:00 P.M. Tables may be reserved online or by telephone. Groups of eight or more are asked to call at least three days in advance so that the kitchen can prepare. Parking is available behind the building for a small fee.",
  "passageJa": "ハーバービュー・ビストロは、昨年の春に開店して以来、二つのことで知られています。温かいもてなしと、静かで居心地のよい雰囲気です。この店は市内から30キロ以内の農場の材料で作った郷土料理を提供しており、季節のメニューは年に4回書き換えられます。\n\n到着すると、お客様は入口で接客係に出迎えられ、その晩の名物料理の説明を受けます。厨房は取り分けて食べられるさまざまな前菜を用意しており、ワインリストに加えて、バーには20種類以上のノンアルコール飲料が置かれています。価格はこの界隈としては手頃で、主菜のほとんどは14ドルから19ドルの間、ランチのセットは11ドルだけです。\n\n常連客は海鮮のシチューを絶賛しており、地元の料理ライターたちはパンについても絶賛しています。週末には、家族連れが奥のガーデンルームで食事をします。そこでは9時まで子どもの入店が歓迎されています。2階のホールは最大60名の宴会用に予約でき、店主によれば、企業の顧客が年末のパーティーのために数か月前から押さえているとのことです。\n\nハーバービュー・ビストロは火曜から日曜まで、午前11時30分から午後10時まで営業しています。席はオンラインまたは電話で予約できます。8名以上の団体は、厨房が準備できるよう、少なくとも3日前に電話するよう求められています。建物の裏手には有料の駐車場があります。",
  "questions": [
    {"q": "In paragraph 2, the word \"reasonable\" is closest in meaning to", "choices": ["strict", "affordable", "logical", "temporary"], "answer": 1, "expl": "第2段落の reasonable は直後に「主菜は14〜19ドル、ランチセットは11ドル」と具体的な価格が示されており、値段が手頃であることを述べています。したがって affordable（手頃な）が最も近い意味です。(1) strict は「厳格な」で価格の話に合いません。(2) logical は reasonable の別の意味である「理にかなった」に対応しますが、ここは人の判断や意見ではなく価格の文脈なので不適切です。(3) temporary は「一時的な」で無関係です。"},
    {"q": "The expression \"rave about\" in paragraph 3 most likely means", "choices": ["to complain loudly about something", "to ask detailed questions about something", "to praise something enthusiastically", "to pay extra for something"], "answer": 2, "expl": "rave about A は「Aを絶賛する」という意味の句動詞です。第3段落では常連客が海鮮のシチューについて、地元の料理ライターがパンについてそう述べており、店を好意的に紹介する記事全体の流れとも一致します。(0) は正反対の「苦情を言う」で、好意的な文脈に矛盾します。(1) の「詳しく質問する」や (3) の「追加料金を払う」は rave の意味とは関係がありません。なお rave は自動詞なので、目的語の前に about または over が必要です。"},
    {"q": "What is indicated about the hall on the second floor?", "choices": ["It is open only on weekends.", "It can be reserved for large gatherings.", "It offers a menu separate from the main dining room.", "It was renovated earlier this year."], "answer": 1, "expl": "第3段落に「2階のホールは最大60名の宴会用に予約でき、企業の顧客が数か月前から押さえている」とあるので、大人数の集まりのために予約できることが分かります。(0) の「週末のみ営業」は、週末について述べられているのは1階奥のガーデンルームであり、ホールの話ではありません。(2) の別メニューについては本文に記述がありません。(3) の改装についても本文に一切触れられていません。"}
  ]
});
window.__addPassage({
  "date": "2026-08-02",
  "level": "600",
  "theme": "メディア・出版（新聞社・編集業務）",
  "title": "Memo: The Riverside Weekly Goes Digital",
  "words": ["publish", "submit", "article", "subscriber", "edition", "editor", "deadline", "issue", "broadcast", "column", "circulation", "journalist", "release", "coverage", "quarterly"],
  "phrases": ["come out", "keep up with A", "as of A", "be responsible for A", "in response to A"],
  "passage": "To: All editorial staff\nFrom: Grace Whitman, Managing [[Editor]]\nSubject: Fall schedule and the new digital [[edition]]\n\n[[As of]] October 1, the Riverside Weekly will [[publish]] two versions of the paper: the printed one you already know, and a digital [[edition]] for phones and tablets. Our print [[circulation]] has grown slowly for three years, but the habits of our readers are changing, and we have to [[keep up with]] them. The digital [[issue]] will [[come out]] every Thursday at 6:00 A.M., a full day before the printed paper reaches stores.\n\nEvery [[journalist]] on staff is asked to [[submit]] at least one [[article]] each week to the digital desk. Because the digital [[deadline]] falls earlier than the print one, please send your files by Tuesday at noon. Ms. Alvarez will [[be responsible for]] the weekly opinion [[column]], and Mr. Tanaka will manage our [[coverage]] of the city council. [[In response to]] requests from readers, we will also add a [[quarterly]] report on local businesses.\n\nCurrent [[subscribers]] will receive the digital [[edition]] at no extra cost, so no one will have to pay twice. The marketing team will [[release]] a short announcement about the change on Monday, and a local station will [[broadcast]] an interview with me on Wednesday morning.\n\nIf you have questions about the new schedule, please speak with your section [[editor]] before Friday. I know that autumn is our busiest season, and I am grateful for the extra effort this month.",
  "passageJa": "宛先: 編集部員各位\n差出人: グレース・ホイットマン（編集長）\n件名: 秋の日程と新しいデジタル版について\n\n10月1日付けで、リバーサイド・ウィークリーは2つの版を発行します。皆さんがすでにご存じの紙版と、スマートフォンやタブレット向けのデジタル版です。紙の発行部数はこの3年ゆるやかに伸びていますが、読者の習慣は変化しており、私たちはそれに遅れずについていく必要があります。デジタル版は毎週木曜の午前6時に発行され、紙版が店頭に並ぶ丸1日前に出ます。\n\n編集部の記者は全員、毎週少なくとも1本の記事をデジタル担当デスクに提出してください。デジタル版の締め切りは紙版より早いため、ファイルは火曜の正午までに送ってください。アルバレスさんが週刊の意見コラムを担当し、田中さんが市議会の報道を統括します。読者からの要望に応じて、地元企業に関する四半期報告も追加します。\n\n現在の定期購読者は追加費用なしでデジタル版を受け取れるので、二重に支払う必要はありません。マーケティング部が月曜にこの変更に関する短い発表を公表し、地元の放送局が水曜の朝に私へのインタビューを放送します。\n\n新しい日程について質問がある場合は、金曜までに各セクションの編集者に相談してください。秋が最も忙しい時期であることは承知しています。今月の追加の労力に感謝します。",
  "questions": [
    {"q": "What is the main purpose of the memo?", "choices": ["To announce that the printed paper will be discontinued", "To ask readers to renew their subscriptions", "To explain a new publishing schedule and new duties", "To report the results of a survey of local businesses"], "answer": 2, "expl": "冒頭で「10月1日付けで紙版とデジタル版の2つを発行する」と述べ、続けて提出の締め切りや担当の割り当てを説明しています。したがって「新しい発行日程と業務分担の説明」が目的です。選択肢1（紙版の廃止）は紙版も継続して発行すると書かれているため誤り。選択肢2（購読更新の依頼）は宛先が読者ではなく編集部員であるため合いません。選択肢4の四半期報告は今後追加する予定の企画であり、調査結果の報告ではありません。"},
    {"q": "In the memo, the word \"coverage\" is closest in meaning to", "choices": ["payment", "reporting", "protection", "distance"], "answer": 1, "expl": "our coverage of the city council（市議会の取材・報道）という文脈なので、reporting（報道）が最も近い意味です。coverage は保険の文脈では protection（補償範囲）の意味になりますが、ここは新聞社の業務分担の話なので当てはまりません。payment（支払い）、distance（距離）はいずれも文脈に合いません。"},
    {"q": "The phrase \"come out\" in the memo is closest in meaning to", "choices": ["be delayed", "be corrected", "be returned", "be released"], "answer": 3, "expl": "The digital issue will come out every Thursday at 6:00 A.M.（デジタル版は毎週木曜の午前6時に出る）という文なので、be released（発行・発売される）が最も近い意味です。come out は「刊行物が世に出る」意味で、be published や be released に言い換えられます。be delayed（遅れる）は時刻が明示されている点と合わず、be corrected（訂正される）、be returned（返却される）はいずれも文意になりません。"}
  ]
});
window.__addPassage({
  "date": "2026-08-03",
  "level": "600",
  "theme": "営業・セールス",
  "title": "Q3 Sales Strategy Update",
  "words": ["prospect", "sales", "pitch", "client", "close", "commission", "proposal", "competitive", "margin", "attain", "secure", "incentive", "outreach", "identify", "exceed"],
  "phrases": ["close a deal", "build relationships", "reach out to A", "in line with A", "on track to do"],
  "passage": "Our [[sales]] team has made significant progress toward the third quarter target. To [[identify]] new [[prospects]] in untapped markets, we [[outreach]] to potential [[clients]] through targeted email campaigns and industry events. Our regional manager asked each team member to [[pitch]] a customized [[proposal]] that demonstrates how we can deliver [[competitive]] solutions [[in line with]] each customer's specific budget and requirements.\n\nLast week, we successfully [[closed]] a major deal with Thompson Industries, our largest [[client]] to date. We [[secured]] the contract by emphasizing our superior [[margin]] advantages and proven track record of excellent service. The three team members who helped [[close]] the deal will receive a substantial [[commission]] based on the contract value.\n\nWe continue to [[build relationships]] with key accounts and [[reach out to]] new prospects on a weekly basis. Our enhanced [[incentive]] program motivates everyone to [[exceed]] their individual targets and [[attain]] record-breaking sales figures. We are [[on track to]] finish the quarter with outstanding results and strong customer satisfaction.",
  "passageJa": "当社の営業チームは第3四半期の目標に向けて大きな進展を遂行しています。開拓されていない市場で新規見込み客を特定するために、ターゲットを絞ったメールキャンペーンと業界イベントを通じて見込み顧客に働きかけます。地域マネージャーは各チームメンバーに、当社の競争力のあるソリューションが各顧客の具体的な予算と要件に沿って提供できることを示すカスタマイズされた提案をプレゼンするよう求めました。\n\n先週、当社は最大のクライアントであるThompson Industriesとの大型取引を成功裏に成立させました。優れた利益率の利点と優秀なサービスの実績を強調することで、契約を確保しました。契約成立を支援した3名のチームメンバーは、契約額に基づいた実質的な手数料を受け取ります。\n\n当社は主要顧客との関係構築を継続し、週ベースで新規見込み客に連絡しています。強化されたインセンティブプログラムは、全員が個別目標を超え、売上高の記録的増加を達成するよう動機付けます。当社は四半期を優れた結果と顧客満足度の高さで完了する見通しです。",
  "questions": [
    {
      "q": "What did the sales team do last week?",
      "choices": ["Applied for new positions at a competitor company", "Closed a major deal with Thompson Industries", "Conducted a training session for new employees", "Visited the corporate headquarters in another city"],
      "answer": 1,
      "expl": "本文の2段落目冒頭『Last week, we successfully closed a major deal with Thompson Industries』に明記されています。他の選択肢は本文に記載されていません。"
    },
    {
      "q": "In the passage, the word 'secure' is closest in meaning to which of the following?",
      "choices": ["Make something safe from danger", "Fasten or attach something tightly", "Obtain or acquire through effort", "Lock something with a key or password"],
      "answer": 2,
      "expl": "『We secured the contract』は『契約を確保した・獲得した』の意味。『secure = obtain/acquire』。『make safe』や『fasten』は異なる文脈での意味です。"
    },
    {
      "q": "According to the passage, what does 'in line with' mean?",
      "choices": ["Standing in a queue together with others", "In agreement or accordance with something", "Following someone in a straight path", "Participating in a group activity"],
      "answer": 1,
      "expl": "『in line with each customer's budget and requirements』の文脈から『Aに沿って・Aと一致して』の意味。『in line with = in accordance with/according to』。"
    }
  ]
});
