window.__addPassage({
  "date": "2026-07-29",
  "level": "600",
  "theme": "契約・交渉",
  "title": "Memo: Renewal of the Harborline Logistics Agreement",
  "words": ["contract", "negotiate", "clause", "provision", "amend", "renew", "obligation", "valid", "draft", "extension", "attorney", "binding", "breach", "confidential", "mutual"],
  "phrases": ["on behalf of", "be subject to", "in accordance with", "enter into", "agree to do"],
  "passage": "MEMORANDUM\nTo: All Department Managers\nFrom: Elena Ruiz, Legal Affairs\nDate: 29 July\n\nOur five-year service [[contract]] with Harborline Logistics will expire on 31 October. Since May, the Legal Affairs team has [[negotiated]] new terms [[on behalf of]] the entire company, and last week our outside [[attorney]] finished reviewing the second [[draft]] of the renewal document. The current agreement remains [[valid]] until the expiration date, so daily shipping operations will not be affected in any way this quarter.\n\nThe revised text [[amends]] three areas. First, the delivery [[clause]] now requires Harborline to notify us within two hours of any delay at a port or warehouse. Second, a new [[provision]] limits annual price increases to three percent. Third, all pricing information is treated as [[confidential]] and may not be shared with third parties. These changes reflect a [[mutual]] effort to reduce risk: in return for the price cap, we accept the [[obligation]] to submit shipping forecasts at the start of each quarter.\n\nIf we [[renew]] the agreement, the final text will [[be subject to]] approval by both boards, and every shipment must then be handled [[in accordance with]] the updated safety standards described in Appendix B. Once the document is signed, it becomes legally [[binding]] on both companies, and any [[breach]] may result in termination with thirty days' notice.\n\nIf the board decides not to [[enter into]] another long-term arrangement, we will instead request a six-month [[extension]] of the current terms while we invite bids from other carriers. Managers who [[agree to adopt]] the new forecasting format should send written confirmation to Legal Affairs by 5 August.",
  "passageJa": "社内連絡\n宛先: 各部門管理職各位\n差出人: 法務部 エレナ・ルイス\n日付: 7月29日\n\nハーバーライン物流との5年間の業務契約は10月31日で満了します。5月以降、法務部のチームが全社を代表して新しい条件を交渉してきました。先週には社外の弁護士が更新書類の第2稿の確認を終えています。現行の合意は満了日まで有効ですので、今四半期の日々の出荷業務に影響はありません。\n\n改訂版では3つの箇所が修正されています。第一に、配送条項では、港や倉庫での遅延が生じた場合、ハーバーラインは2時間以内に当社へ通知することが必要になりました。第二に、新しい条項が年間の値上げを3パーセントまでに制限します。第三に、価格情報はすべて機密として扱われ、第三者と共有することはできません。これらの変更はリスクを減らそうとする相互の努力を反映したものです。価格の上限と引き換えに、当社は各四半期の初めに出荷予測を提出する義務を負います。\n\n合意を更新する場合、最終的な文面は両社の取締役会の承認の対象となり、その後はすべての出荷を付属書Bに記載された最新の安全基準に従って扱う必要があります。書類に署名がなされれば、それは両社に対して法的な拘束力を持ち、いかなる違反も30日前の通知による契約解除につながる可能性があります。\n\n取締役会が新たな長期の取り決めを結ばないと決めた場合は、代わりに現行条件の6か月の延長を要請し、その間に他の運送業者から入札を募ります。新しい予測の提出形式の採用に同意する管理職は、8月5日までに法務部へ書面で確認を送ってください。",
  "questions": [
    {"q": "What is the main purpose of the memo?", "choices": ["To announce that a supplier has been replaced", "To explain the status and content of a contract renewal", "To report a safety accident at a warehouse", "To invite managers to a training session on shipping"], "answer": 1, "expl": "第1段落で契約の満了時期と交渉の進捗を伝え、第2段落以降で修正点と今後の手続きを説明しています。よって「契約更新の状況と内容の説明」が目的です。(A)は他社への切り替えは延長時の入札募集として仮定の話に留まるため不可。(C)の事故の記述はありません。(D)の研修の案内もありません。"},
    {"q": "In paragraph 1, the word \"valid\" is closest in meaning to", "choices": ["popular", "in force", "flexible", "expensive"], "answer": 1, "expl": "ここでの valid は「(契約が)効力を持っている」という意味で、満了日まで効力が続くことを述べています。したがって in force(効力がある)が最も近い意味です。(A) popular は「人気がある」、(C) flexible は「柔軟な」、(D) expensive は「高価な」で、いずれも効力の有無を表しません。"},
    {"q": "What does the phrase \"be subject to\" mean in paragraph 3?", "choices": ["to be exempt from something", "to require or depend on something", "to be written in a formal style", "to be delivered ahead of schedule"], "answer": 1, "expl": "be subject to ~ は「～の対象となる、～次第である」の意味で、ここでは最終文面が両社の取締役会の承認を必要とすることを表します。よって「必要とする・依存する」が正解です。(A)は逆の意味の「免除される」。(C)は文体の話で無関係。(D)は納品時期の話で本文に対応しません。"}
  ]
});
