window.__addPassage({
  "date": "2026-07-26",
  "level": "600",
  "theme": "顧客対応・クレーム処理（カスタマーサービス）",
  "title": "Memo: New Steps for Handling Customer Complaints",
  "words": ["complaint", "apologize", "defective", "replacement", "courteous", "representative", "inconvenience", "satisfaction", "resolve", "exchange", "prompt", "compensation", "dissatisfied", "policy", "assistance"],
  "phrases": ["apologize for -ing", "deal with", "get in touch with", "free of charge", "look into"],
  "passage": "To: All Front Desk Staff\nFrom: Daniel Okoye, Customer Care Manager\nSubject: New Steps for Handling Customer Complaints\n\nLast month we received forty-two [[complaints]] about our home appliance line, twice as many as in April. Most callers were [[dissatisfied]] not with the products but with how slowly we answered them. Starting Monday, every [[representative]] will follow the steps below.\n\nFirst, listen to the whole story before you speak, and stay [[courteous]] even when the caller is angry. Always [[apologize]] for the [[inconvenience]] first, since a short apology often [[resolves]] a call before it grows into a bigger problem. If a customer reports a [[defective]] item, do not argue. Offer to [[exchange]] it or send a [[replacement]], and explain that shipping is [[free of charge]] under our warranty [[policy]].\n\nSecond, promise only what you can deliver. If you cannot answer at once, say that you will [[look into]] the matter and then [[get in touch with]] the customer within one business day. A [[prompt]] callback matters more to most people than a long explanation.\n\nThird, record every case in the online system. Our support team [[deals with]] repeat cases each week, and your notes help them decide whether [[compensation]] is appropriate. When we miss a promised delivery date, please also [[apologize for missing]] it in writing, not only by phone.\n\nWe would like your [[assistance]] in testing these steps for one month. The training slides are on the shared drive, and I will visit each floor on Wednesday afternoon. Our goal is a [[satisfaction]] score above ninety percent by December.",
  "passageJa": "宛先: フロント対応スタッフの皆さん\n差出人: ダニエル・オコエ（カスタマーケア部長）\n件名: 顧客からの苦情対応の新しい手順について\n\n先月、当社の家庭用電化製品ラインについて42件の苦情が寄せられました。4月の2倍の件数です。多くのお客様は、製品そのものではなく、こちらの回答が遅いことに不満を持っていました。月曜から、担当者は全員、以下の手順に従ってください。\n\n第一に、話し始める前に事情を最後まで聞き、相手が怒っていても丁寧な態度を保つこと。まず必ずご迷惑をおかけしたことをおわびしてください。短い謝罪の一言で、問題が大きくなる前に解決する電話は少なくありません。お客様が不良品だと伝えてきた場合は、言い返さないこと。交換するか交換品を送ることを申し出て、保証規定により送料は無料である旨を説明してください。\n\n第二に、実行できることだけを約束すること。その場で答えられない場合は、この件は調査したうえで、1営業日以内にこちらから連絡すると伝えてください。多くのお客様にとっては、長い説明よりも迅速な折り返しの連絡のほうが重要です。\n\n第三に、すべての案件をオンラインシステムに記録すること。サポートチームは毎週、繰り返し発生している案件に対処しており、皆さんの記録は補償が妥当かどうかを判断する助けになります。約束した納品日に間に合わなかったときは、電話だけでなく書面でもおわびしてください。\n\n1か月間、この手順の試行に協力をお願いします。研修用のスライドは共有ドライブにあり、水曜の午後に各フロアを回ります。12月までに満足度90パーセント超えを目標とします。",
  "questions": [
    {"q": "What should staff do if they cannot answer a customer's question immediately?", "choices": ["Transfer the call to Mr. Okoye", "Send a written apology the same day", "Contact the customer again within one business day", "Offer compensation right away"], "answer": 2, "expl": "第3段落に「say that you will look into the matter and then get in touch with the customer within one business day」とあり、1営業日以内に折り返し連絡すると伝えるよう指示されている。よって(2)が正解。(0)電話を転送する記述はない。(1)書面でのおわびは納品日に間に合わなかった場合の話で、条件が異なる。(3)補償はサポートチームが記録をもとに判断するものなので、その場で申し出るのは誤り。"},
    {"q": "The word \"prompt\" in paragraph 3 is closest in meaning to", "choices": ["quick", "polite", "detailed", "unexpected"], "answer": 0, "expl": "prompt は「迅速な、即座の」の意味で、ここでは折り返しの連絡が速いことを表す。最も近いのは(0)quick。(1)polite は「礼儀正しい」で、この文では速さが論点なので誤り。(2)detailed は「詳細な」だが、直後で「長い説明よりも重要」と対比されており逆の内容。(3)unexpected は「予期しない」で意味が通らない。"},
    {"q": "The phrase \"look into\" in paragraph 3 is closest in meaning to", "choices": ["glance at", "investigate", "take care of", "postpone"], "answer": 1, "expl": "look into は「～を調査する、詳しく調べる」の意味で、(1)investigate が同義。(0)glance at は「ちらりと見る」で、視線を向ける look at に近く意味が浅い。(2)take care of は「世話をする、処理する」で look after に近く、調査の意味はない。(3)postpone は「延期する」で、1営業日以内に連絡するという文脈と矛盾する。"}
  ]
});
