window.__addPassage({
  "date": "2026-07-21",
  "level": "600",
  "theme": "施設・オフィス管理",
  "title": "Notice: Upcoming Building Renovation",
  "words": ["maintenance","renovation","premises","facility","tenant","occupancy","inspection","lease","vendor","relocate","spacious","adjacent","utility","custodian","corridor"],
  "passage": "To all [[tenant]]s of the Brookfield Business Center:\n\nWe are pleased to announce that a major [[renovation]] of our [[premises]] will begin next month. The goal is to modernize the building and improve every shared [[facility]], from the reception area to the meeting rooms. During this period, our [[custodian]] and a licensed [[vendor]] will work together to complete the upgrades with as little disruption as possible.\n\nPlease note the following. Routine [[maintenance]] of the heating system will take place during the first week, and a safety [[inspection]] of all floors is scheduled for the second week. To keep everyone safe, please do not store any items in the main [[corridor]], since it must remain clear at all times. There may be brief interruptions to certain [[utility]] services, such as water and electricity, but these will be announced in advance.\n\nOnce the work is finished, the building will offer more [[spacious]] offices and a new lounge [[adjacent]] to the lobby. Because [[occupancy]] has grown steadily, several teams will [[relocate]] to the newly opened fifth floor. Tenants who wish to expand their current space should contact the management office before their [[lease]] comes up for renewal. We appreciate your patience and look forward to welcoming you to an improved workplace.",
  "passageJa": "ブルックフィールド・ビジネスセンターの入居者の皆様へ:\n\n当ビルの大規模な改装を来月開始することをお知らせします。目的は建物を近代化し、受付エリアから会議室まで、共用のあらゆる設備を改善することです。この期間中、当ビルの用務員と免許を持つ業者が協力し、できるだけ支障の少ない形で改修を完了させます。\n\n以下にご注意ください。暖房システムの定期保守は第1週に行われ、全フロアの安全点検は第2週に予定されています。皆様の安全のため、正面の廊下には物を置かないでください。常に通路を確保しておく必要があるためです。水道や電気など一部の公共設備サービスに短時間の中断が生じる場合がありますが、これらは事前にお知らせします。\n\n工事が完了すると、ビルはより広々としたオフィスと、ロビーに隣接した新しいラウンジを提供します。入居率が着実に伸びているため、いくつかのチームは新たに開放される5階へ移転します。現在のスペースを拡張したい入居者は、賃貸契約の更新時期を迎える前に管理事務所へご連絡ください。ご辛抱に感謝するとともに、改善された職場に皆様をお迎えできることを楽しみにしています。",
  "questions": [
    {"q": "What is the main purpose of this notice?", "choices": ["To announce a rent increase", "To inform tenants about an upcoming renovation", "To advertise office space for new tenants", "To report the results of a customer survey"], "answer": 1, "expl": "第1段落で「大規模な改装を来月開始する」と告知し、以降で作業内容を説明しています。よって正解は1。0の家賃値上げ、2の新規入居者向けの宣伝、3の顧客調査結果はいずれも本文で触れられていません。"},
    {"q": "The word \"premises\" in paragraph 1 is closest in meaning to", "choices": ["employees", "building", "equipment", "schedule"], "answer": 1, "expl": "premisesは「建物・敷地」を意味し、ここでは改装対象の当ビルを指します。したがってbuilding(建物)が最も近い意味です。0のemployees(従業員)、2のequipment(設備)、3のschedule(予定)は語義が異なります。"},
    {"q": "Why are tenants asked not to store items in the corridor?", "choices": ["It is reserved for the vendor", "It must remain clear at all times", "It is being repainted this week", "It has no lighting during the work"], "answer": 1, "expl": "第2段落に「常に通路を確保しておく必要があるため物を置かないでください」とあり、安全確保が理由です。よって正解は1。0の業者専用、2の塗り直し、3の照明なしは本文に記載がありません。"}
  ]
});
