window.__addPassage({
  "date": "2026-07-30",
  "level": "600",
  "theme": "環境・サステナビリティ",
  "title": "Notice: The Green Desk Program Begins in September",
  "words": ["recycle", "conserve", "sustainable", "initiative", "dispose", "waste", "reduce", "renewable", "efficiency", "packaging", "emission", "container", "awareness", "contribute", "donate"],
  "phrases": ["dispose of A", "be committed to -ing", "cut down on A", "be aware of A", "in an effort to do"],
  "passage": "NOTICE\nTo: All Staff\nFrom: Facilities Management, Halverson Industries\nDate: 30 July\n\nBeginning on 1 September, Halverson Industries will launch a [[sustainable]] office program called Green Desk. This [[initiative]] is designed to [[reduce]] the amount of [[waste]] our offices produce each year and to [[conserve]] energy in all six buildings on the Riverside campus. Senior management [[is committed to lowering]] the company's environmental impact, and every department is expected to take part.\n\nUnder Green Desk, employees will [[recycle]] paper, plastic, and glass in the blue [[containers]] placed on every floor. Batteries and old electronics must not go into these bins. Instead, please [[dispose of used batteries]] at the collection point near the loading dock. Confidential documents will continue to be [[disposed]] of by our shredding service, as they are today. The cafeteria will also [[cut down on the use of]] single-use [[packaging]]; washable dishes and cups will be provided at no cost to staff.\n\nTo improve energy [[efficiency]], the maintenance team will install motion sensors in the meeting rooms and hallways during the last week of August. In addition, the company has signed an agreement to buy forty percent of its electricity from a [[renewable]] source, which should lower our annual carbon [[emissions]] considerably. [[In an effort to raise]] [[awareness]], Facilities Management will hold a thirty-minute briefing on 20 August at 10:00 A.M. in the main auditorium. All staff should [[be aware of the new sorting rules]] before the program begins.\n\nEmployees who want to [[contribute]] more may join the Green Desk committee, which meets on the first Friday of each month. For every department that reaches its yearly target, the company will [[donate]] five hundred dollars to a local tree-planting fund. Please send any questions to facilities@halverson-ind.example.",
  "passageJa": "お知らせ\n宛先: 全職員\n差出人: Halverson Industries 施設管理部\n日付: 7月30日\n\n9月1日より、Halverson Industries は Green Desk という持続可能なオフィスプログラムを開始します。この取り組みは、当社のオフィスが毎年出す廃棄物の量を減らし、Riverside キャンパスの6棟すべてでエネルギーを節約することを目的としています。経営陣は当社の環境負荷を下げることに全力で取り組んでおり、全部署が参加することを想定しています。\n\nGreen Desk のもとで、従業員は各階に置かれた青い容器で紙、プラスチック、ガラスをリサイクルします。電池や古い電子機器はこれらの箱に入れないでください。使用済み電池は、搬入口近くの回収場所で処分してください。機密書類はこれまでどおり当社の細断サービスによって処分されます。カフェテリアも使い捨て包装の使用を減らします。洗って使える食器とカップが職員に無料で提供されます。\n\nエネルギー効率を高めるため、施設管理部は8月最終週に会議室と廊下へ人感センサーを設置します。さらに当社は電力の40パーセントを再生可能な電源から購入する契約を締結しており、これにより年間の炭素排出量が大幅に下がる見込みです。意識を高めようと、施設管理部は8月20日午前10時からメインホールで30分の説明会を開きます。全職員はプログラム開始前に新しい分別ルールを承知しておいてください。\n\nさらに貢献したい従業員は、毎月第1金曜日に開かれる Green Desk 委員会に参加できます。年間目標を達成した部署ごとに、当社は地元の植樹基金へ500ドルを寄付します。質問は facilities@halverson-ind.example までお送りください。",
  "questions": [
    {"q": "What is the main purpose of the notice?", "choices": ["To announce a new environmental program", "To report the results of an energy audit", "To ask employees for donations", "To introduce a new cafeteria menu"], "answer": 0, "expl": "第1段落で「9月1日より Green Desk という持続可能なオフィスプログラムを開始する」と述べ、以降で内容を説明しているため(A)が正解です。(B)監査の結果は述べられていません。(C)寄付をするのは会社であり、従業員に求めてはいません。(D)カフェテリアの記述は包装の削減と食器の提供であり、新メニューの案内ではありません。"},
    {"q": "In paragraph 1, the word \"conserve\" is closest in meaning to", "choices": ["expand", "save", "inspect", "announce"], "answer": 1, "expl": "conserve は「(資源を)節約する」で、ここでは6棟でエネルギーを節約する文脈です。したがって save が最も近い意味になります。(A)expand は「拡大する」で逆方向です。(C)inspect は「点検する」、(D)announce は「発表する」で、いずれもエネルギーを減らすという意味を持ちません。"},
    {"q": "In paragraph 2, the phrase \"cut down on\" is closest in meaning to", "choices": ["pay for", "search for", "reduce the use of", "deliver"], "answer": 2, "expl": "cut down on A は「～を減らす、切り詰める」という意味です。直後に「洗って使える食器を提供する」とあることからも、使い捨て包装の使用を減らす流れだと分かります。(A)pay for は「～の代金を払う」、(B)search for は「～を探す」、(D)deliver は「配達する」で、いずれも削減の意味を持ちません。なお cut down A(木を切り倒す)とは意味が異なる点にも注意します。"}
  ]
});
