window.__addPassage({
  "date": "2026-08-02",
  "level": "600",
  "theme": "メディア・出版（新聞社・編集業務）",
  "title": "Memo: The Riverside Weekly Goes Digital",
  "words": ["publish", "submit", "article", "subscriber", "edition", "editor", "deadline", "issue", "broadcast", "column", "circulation", "journalist", "release", "coverage", "quarterly"],
  "phrases": ["come out", "keep up with A", "as of A", "be responsible for A", "in response to A"],
  "passage": "To: All editorial staff\nFrom: Grace Whitman, Managing [[Editor]]\nSubject: Fall schedule and the new digital [[edition]]\n\n[[As of]] October 1, the Riverside Weekly will [[publish]] two versions of the paper: the printed one you already know, and a digital [[edition]] for phones and tablets. Our print [[circulation]] has grown slowly for three years, but the habits of our readers are changing, and we have to [[keep up with]] them. The digital [[issue]] will [[come out]] every Thursday at 6:00 A.M., a full day before the printed paper reaches stores.\n\nEvery [[journalist]] on staff is asked to [[submit]] at least one [[article]] each week to the digital desk. Because the digital [[deadline]] falls earlier than the print one, please send your files by Tuesday at noon. Ms. Alvarez will [[be responsible for]] the weekly opinion [[column]], and Mr. Tanaka will manage our [[coverage]] of the city council. [[In response to]] requests from readers, we will also add a [[quarterly]] report on local businesses.\n\nCurrent [[subscribers]] will receive the digital [[edition]] at no extra cost, so no one will have to pay twice. The marketing team will [[release]] a short announcement about the change on Monday, and a local station will [[broadcast]] an interview with me on Wednesday morning.\n\nIf you have questions about the new schedule, please speak with your section [[editor]] before Friday. I know that autumn is our busiest season, and I am grateful for the extra effort this month.",
  "passageJa": "宛先: 編集部員各位\n差出人: グレース・ホイットマン（編集長）\n件名: 秋の日程と新しいデジタル版について\n\n10月1日付けで、リバーサイド・ウィークリーは2つの版を発行します。皆さんがすでにご存じの紙版と、スマートフォンやタブレット向けのデジタル版です。紙の発行部数はこの3年ゆるやかに伸びていますが、読者の習慣は変化しており、私たちはそれに遅れずについていく必要があります。デジタル版は毎週木曜の午前6時に発行され、紙版が店頭に並ぶ丸1日前に出ます。\n\n編集部の記者は全員、毎週少なくとも1本の記事をデジタル担当デスクに提出してください。デジタル版の締め切りは紙版より早いため、ファイルは火曜の正午までに送ってください。アルバレスさんが週刊の意見コラムを担当し、田中さんが市議会の報道を統括します。読者からの要望に応じて、地元企業に関する四半期報告も追加します。\n\n現在の定期購読者は追加費用なしでデジタル版を受け取れるので、二重に支払う必要はありません。マーケティング部が月曜にこの変更に関する短い発表を公表し、地元の放送局が水曜の朝に私へのインタビューを放送します。\n\n新しい日程について質問がある場合は、金曜までに各セクションの編集者に相談してください。秋が最も忙しい時期であることは承知しています。今月の追加の労力に感謝します。",
  "questions": [
    {"q": "What is the main purpose of the memo?", "choices": ["To announce that the printed paper will be discontinued", "To ask readers to renew their subscriptions", "To explain a new publishing schedule and new duties", "To report the results of a survey of local businesses"], "answer": 2, "expl": "冒頭で「10月1日付けで紙版とデジタル版の2つを発行する」と述べ、続けて提出の締め切りや担当の割り当てを説明しています。したがって「新しい発行日程と業務分担の説明」が目的です。選択肢1（紙版の廃止）は紙版も継続して発行すると書かれているため誤り。選択肢2（購読更新の依頼）は宛先が読者ではなく編集部員であるため合いません。選択肢4の四半期報告は今後追加する予定の企画であり、調査結果の報告ではありません。"},
    {"q": "In the memo, the word \"coverage\" is closest in meaning to", "choices": ["payment", "reporting", "protection", "distance"], "answer": 1, "expl": "our coverage of the city council（市議会の取材・報道）という文脈なので、reporting（報道）が最も近い意味です。coverage は保険の文脈では protection（補償範囲）の意味になりますが、ここは新聞社の業務分担の話なので当てはまりません。payment（支払い）、distance（距離）はいずれも文脈に合いません。"},
    {"q": "The phrase \"come out\" in the memo is closest in meaning to", "choices": ["be delayed", "be corrected", "be returned", "be released"], "answer": 3, "expl": "The digital issue will come out every Thursday at 6:00 A.M.（デジタル版は毎週木曜の午前6時に出る）という文なので、be released（発行・発売される）が最も近い意味です。come out は「刊行物が世に出る」意味で、be published や be released に言い換えられます。be delayed（遅れる）は時刻が明示されている点と合わず、be corrected（訂正される）、be returned（返却される）はいずれも文意になりません。"}
  ]
});
