window.__addPassage({
  "date": "2026-07-31",
  "level": "600",
  "theme": "研修・能力開発",
  "title": "Memo: The Autumn Skills Program",
  "words": ["seminar", "instructor", "enroll", "mandatory", "curriculum", "proficiency", "evaluate", "assignment", "participant", "lecture", "trainee", "objective", "acquire", "optional", "conduct"],
  "phrases": ["be eligible for A", "take advantage of A", "participate in A", "consist of A", "no later than A"],
  "passage": "MEMORANDUM\nTo: All Branch Staff\nFrom: Rina Delgado, Learning and Development\nDate: 31 July\nSubject: The Autumn Skills Program\n\nLearning and Development will [[conduct]] a new training program at every branch office this autumn. The main [[objective]] of the program is to help staff [[acquire]] the practical skills our clients now expect, especially in written communication and basic data analysis.\n\nThe [[curriculum]] [[consists of]] three parts. The first part is a two-day [[seminar]] led by an outside [[instructor]], Mr. Haruki Sato, who has trained employees at several regional banks. The second part is a series of short online [[lectures]] that each [[participant]] may watch at any time. The third part is a written [[assignment]] based on a real customer case. Every [[trainee]] must submit this work [[no later than]] 30 November, and department managers will [[evaluate]] it using the standard company rubric.\n\nThe two-day [[seminar]] is [[mandatory]] for all client-facing employees. The online [[lectures]] are [[optional]], but we strongly encourage you to [[take advantage of]] them, because they cover the language [[proficiency]] topics that appear most often in customer complaints. Staff members who have completed one full year of service [[are eligible for]] the advanced module in January as well.\n\nTo [[enroll]], please open the Learning Portal and select Autumn Skills from the course menu. Employees who cannot [[participate in]] the November sessions may join the March group instead. Please contact me at extension 4120 if you have any questions.",
  "passageJa": "社内連絡\n宛先: 全支店スタッフ\n差出人: リナ・デルガード(人材開発部)\n日付: 7月31日\n件名: 秋期スキルプログラム\n\n人材開発部は、この秋、全支店で新しい研修プログラムを実施します。このプログラムの主な目標は、とくに文書によるコミュニケーションと基礎的なデータ分析の分野で、顧客が今求めている実務的な技能をスタッフが習得できるようにすることです。\n\nカリキュラムは3つの部分から成ります。第1部は、外部講師の佐藤春樹氏が担当する2日間のセミナーです。同氏は複数の地方銀行で従業員を指導してきました。第2部は短いオンライン講義のシリーズで、各参加者は好きな時間に視聴できます。第3部は、実際の顧客事例に基づく書面の課題です。研修生は全員、遅くとも11月30日までにこの課題を提出しなければならず、部門の管理職が社の標準評価基準を用いて評価します。\n\n2日間のセミナーは、顧客と直接接する従業員全員にとって必須です。オンライン講義は任意ですが、ぜひ活用してください。顧客からの苦情に最も多く現れる言語運用力の項目を扱っているためです。勤続1年を満了したスタッフは、1月の上級モジュールを受講する資格もあります。\n\n登録するには、ラーニングポータルを開き、コースメニューから Autumn Skills を選んでください。11月の回に参加できない従業員は、代わりに3月のグループに加わることができます。質問がある場合は内線4120まで連絡してください。",
  "questions": [
    {"q": "According to the memo, which part of the program is NOT required?", "choices": ["The two-day seminar", "The online lectures", "The written assignment", "The advanced module in January"], "answer": 1, "expl": "第3段落に The online lectures are optional とあり、オンライン講義だけが任意です。(A)のセミナーは同じ段落で mandatory と明記されています。(C)の課題は第2段落で Every trainee must submit と義務が示されています。(D)の1月の上級モジュールは「必須でない」とは書かれておらず、勤続1年という受講資格の条件が述べられているだけなので、本文の記述から必須・任意の判断はできません。"},
    {"q": "In paragraph 1, the word \"acquire\" is closest in meaning to", "choices": ["purchase", "obtain", "replace", "postpone"], "answer": 1, "expl": "ここでは acquire the practical skills(実務的な技能を習得する)の意味なので、obtain(得る)が最も近い言い換えです。(A) purchase は「金銭で購入する」で、acquire に「買収する」の意味はあっても skills には使えません。(C) replace は「取り替える」、(D) postpone は「延期する」で、いずれも文脈に合いません。"},
    {"q": "What does the phrase \"take advantage of\" mean in paragraph 3?", "choices": ["to make use of something", "to complain about something", "to pay extra for something", "to be excused from something"], "answer": 0, "expl": "take advantage of A は「Aを利用する、活用する」で、make use of A と同義です。ここでは任意のオンライン講義を活用するよう勧める文脈です。(B)は苦情を述べる意味で、本文では苦情は講義が扱う話題として触れられているだけです。(C)の追加料金や(D)の免除に相当する記述は本文にありません。"}
  ]
});
