window.__addPassage({
  "date": "2026-08-08",
  "level": "600",
  "theme": "小売店運営",
  "title": "Staff Memo: Weekend Clearance Event",
  "words": ["cashier", "checkout", "clearance", "markdown", "aisle", "shelf", "browse", "storefront", "showroom", "display", "barcode", "scan", "purchase", "shoplifting", "restock"],
  "phrases": ["out of stock", "browse through A", "on display", "at a discount", "run out of A"],
  "passage": "To: All Sales Floor Staff\nFrom: Diane Coleman, Store Manager\nSubject: Weekend Clearance Event\n\nThis Saturday and Sunday, Springfield Home Goods will hold its annual summer [[clearance]] sale, and every [[cashier]] on the sales floor should prepare for a busy weekend. A large banner will hang outside the [[storefront]] on Friday evening, and our best deals will be placed [[on display]] in the [[showroom]] near the main entrance. Most seasonal furniture will carry a [[markdown]] of 30 to 50 percent, so shoppers can expect real savings [[at a discount]] throughout the store.\n\nBefore the doors open at nine o'clock, please [[restock]] the [[shelves]] in every [[aisle]], [[display]] any new arrivals near the front window, and make sure each item has a working [[barcode]] so cashiers can [[scan]] it quickly at the [[checkout]]; delays there only frustrate customers who are eager to finish their [[purchase]]. If a popular item is [[out of stock]], attach a small paper sign to the shelf rather than leaving an empty space, since several product lines are likely to [[run out of stock]] by Sunday afternoon given the size of the discount.\n\nBecause the store will be crowded, please remain alert for [[shoplifting]], particularly near the clearance racks, where small items are easy to slip into a bag unnoticed. Staff members are welcome to [[browse]] the sale during their own break time, but during working hours, please greet any customer who continues to [[browse through the same rack]] for several minutes -- a friendly offer of help prevents most problems before they start.\n\nThank you all for your hard work this quarter. Please arrive fifteen minutes early on Saturday for a short team briefing at the front register, and let me know if you have any questions before the event begins.",
  "passageJa": "宛先:販売フロア担当スタッフ全員\n差出人:ダイアン・コールマン(店長)\n件名:週末クリアランスイベントについて\n\n今週の土曜日と日曜日、スプリングフィールド・ホームグッズは恒例の夏の在庫一掃セールを開催します。フロアの全レジ係を含むスタッフは、混雑する週末に備えてください。金曜日の夜には店頭に大きな横断幕を掲げ、正面入口近くのショールームには目玉商品を展示します。ほとんどの季節商品は30〜50パーセントの値下げとなるため、来店客は店内全体で割引価格による大きな節約を期待できます。\n\n午前9時の開店前に、各通路の棚を補充し、新着商品は正面の窓際に陳列し、各商品に有効なバーコードが付いていることを確認してください。レジ係がそれを素早くスキャンできるようにするためです。レジでの遅れは、購入を早く済ませたい客をいらだたせるだけです。人気商品が品切れの場合は、棚を空のままにせず、小さな紙の案内を貼ってください。割引の規模を考えると、日曜日の午後までに複数の商品ラインが在庫を切らす可能性が高いためです。\n\n店内が混雑するため、特にクリアランスラック付近での万引きには注意を払ってください。小さな商品は気づかれずにバッグに入れられやすいためです。スタッフは休憩時間中であればセール品を自由に見て回って構いませんが、勤務時間中に同じラックを数分間にわたって見て回り続ける客がいたら、声をかけて対応してください。親切に声をかけることで、多くの問題は事前に防げます。\n\n今四半期の頑張りに感謝します。土曜日は短いミーティングのため、レジ前に15分早めに集合してください。イベント開始前に質問があれば教えてください。",
  "questions": [
    {"q": "The word \"markdown\" in the first paragraph is closest in meaning to", "choices": ["an increase in price", "a reduction in price", "a new product line", "a customer complaint"], "answer": 1, "expl": "markdown は「値下げ」を意味し、直後の '30 to 50 percent' という数値や 'real savings' という文脈から price reduction の意味だと判断できます。(A)は反対の意味、(C)(D)は本文の文脈と関係がありません。"},
    {"q": "What does the phrase \"run out of stock\" suggest about several product lines?", "choices": ["They will be delivered late.", "They will likely be completely sold before the sale ends.", "They will be moved to the showroom.", "They will be marked down further."], "answer": 1, "expl": "'run out of stock' は「在庫を切らす、売り切れる」という意味の句動詞です。文脈でも 'several product lines are likely to run out of stock by Sunday afternoon' とあり、売り切れる可能性を述べています。(A)配送遅延、(C)展示への移動、(D)追加値下げについては本文に記載がありません。"},
    {"q": "According to the memo, what should staff do if a popular item is out of stock?", "choices": ["Move it to the showroom immediately.", "Offer the customer a discount voucher.", "Attach a small sign to the empty shelf.", "Call the store manager right away."], "answer": 2, "expl": "本文に 'attach a small paper sign to the shelf rather than leaving an empty space' と明記されており、正解は(C)です。(A)(B)(D)についての指示は本文中に見当たりません。"}
  ]
});
