window.__addPassage({
  "date": "2026-08-07",
  "level": "600",
  "theme": "郵便・配送サービス",
  "title": "New Mailroom Procedures at Briarwood Logistics",
  "words": ["package", "parcel", "postage", "envelope", "mailbox", "tracking", "signature", "recipient", "sender", "deliver", "forward", "weigh", "notify", "undeliverable", "fragile"],
  "phrases": ["in transit", "be addressed to A", "sign for A", "return A to sender", "notify A of B"],
  "passage": "Beginning next Monday, all incoming and outgoing mail at Briarwood Logistics will be handled through the newly renovated mailroom on the second floor. Every [[package]] and [[parcel]] arriving at the front desk will first be logged and then [[weighed]] on the digital scale before being sorted by department. Staff members should check their [[mailbox]] each morning, since letters and small items will no longer be delivered directly to individual desks.\n\nFor outgoing shipments, employees must attach the correct amount of [[postage]] and place documents inside a sealed [[envelope]] before dropping them at the mailroom counter. Every outgoing item will be assigned a [[tracking]] number, and the mailroom staff will [[deliver]] time-sensitive shipments to the courier by 4 p.m. daily. Items that are heavy or [[fragile]] should be marked clearly so that they can be handled with extra care while [[in transit]]. High-value packages will require a [[signature]] from the [[recipient]]; if no one is available to [[sign for the package]], the courier will leave a notice and attempt delivery again the next day.\n\nOccasionally, an item cannot be delivered because it is [[addressed to a former employee]] or an incorrect department. Mail addressed to staff who have relocated to another branch will instead be [[forwarded]] to their new office automatically. When forwarding is not possible, the mailroom will mark the item [[undeliverable]] and [[return it to the sender]] rather than holding it indefinitely. Staff should always write the [[sender]]'s complete address on outgoing items, and the mailroom will [[notify the customer of any delay]] by e-mail whenever the original sender can be identified.\n\nEmployees with questions about the new procedures should contact the facilities office. All packages currently being processed will continue to move through the previous system until the transition is complete.",
  "passageJa": "来週の月曜日から、Briarwood Logisticsで受発信されるすべての郵便物は、2階に新しく改装されたメールルームで取り扱われます。フロントデスクに届いた荷物や小包はすべてまず記録され、部署ごとに仕分けされる前にデジタル秤で重さを量られます。手紙や小さな品物は各自のデスクへ直接配達されなくなるため、社員は毎朝自分の郵便受けを確認するようにしてください。\n\n発送する荷物については、社員は正しい額の郵便料金を貼り、書類を封をした封筒に入れてからメールルームのカウンターに提出しなければなりません。発送するすべての品物には追跡番号が割り当てられ、メールルームの担当者は急ぎの発送物を毎日午後4時までに配送業者に引き渡します。重い品物や壊れやすい品物にはその旨を明確に表示し、輸送中は特に注意して扱われるようにしてください。高額な荷物には受取人の署名が必要で、荷物の受け取りにサインできる人がいない場合、配送業者は不在通知を残して翌日再配達を試みます。\n\nまれに、以前の社員宛てになっていたり部署名が誤っていたりして配達できない品物があります。別の支店に異動した社員宛ての郵便物は、代わりに新しいオフィスへ自動的に転送されます。転送できない場合、メールルームはその品物を配達不能と印を付け、差出人に返送します。社員は発送する品物に差出人の完全な住所を必ず記載するようにしてください。また、元の差出人が特定できる場合、メールルームはメールで遅延について顧客に知らせます。\n\n新しい手続きについて質問がある社員は、施設管理オフィスまでご連絡ください。現在処理中のすべての荷物は、移行が完了するまで従来のシステムで引き続き処理されます。",
  "questions": [
    {"q": "According to the notice, what will happen to high-value packages?", "choices": ["They will be delivered without any special handling procedures.", "They will require a signature from the recipient upon delivery.", "They will be automatically returned to the sender.", "They will be stored permanently in the mailroom."], "answer": 1, "expl": "本文に「High-value packages will require a signature from the recipient」とあるため、正解は高額な荷物には受取人の署名が必要という内容です。Aは特別な取り扱いが不要だとしており本文と矛盾します。Cは配達不能の場合の対応であり高額品全般の話ではありません。Dは転送についての記述で高額品固有の話ではありません。"},
    {"q": "The word \"undeliverable\" in paragraph 3 is closest in meaning to which of the following?", "choices": ["unable to be delivered", "delivered ahead of schedule", "delivered without a signature", "delivered to the wrong branch"], "answer": 0, "expl": "「undeliverable」は接頭辞「un-」(否定)と「deliverable」(配達可能な)から成り、「配達できない」という意味です。他の選択肢はいずれも配達自体は行われることを前提としており、意味が異なります。"},
    {"q": "What does the phrase \"return it to the sender\" in paragraph 3 most likely mean in this context?", "choices": ["Send the item back to the person or company who originally sent it.", "Ask the recipient to come and collect the item in person.", "Forward the item to a new department within the company.", "Keep the item in storage until it can be delivered."], "answer": 0, "expl": "「return A to sender」は「Aを差出人に返送する」という意味の動詞句で、配達不能な郵便物を元の送り主に送り返すことを表します。他の選択肢は本文の「rather than holding it indefinitely(無期限に保管するのではなく)」という記述と矛盾するか、転送や受取人による受け取りという別の内容を表しています。"}
  ]
});
