window.__addPassage({
  "date": "2026-08-05",
  "level": "600",
  "theme": "銀行・金融サービス",
  "title": "Notice to Account Holders: Updates to Personal Banking Services",
  "words": ["withdraw", "teller", "transfer", "currency", "verify", "interest", "mortgage", "loan", "outstanding", "accrue", "portfolio", "dividend", "shareholder", "insurance", "premium"],
  "phrases": ["apply for A", "pay off A", "be entitled to A", "set aside A", "in the event of A"],
  "passage": "Beginning on 1 September, Halton Community Bank will update several services for personal account holders. Customers who [[withdraw]] cash at a branch will no longer need to wait for a [[teller]], because our new machines handle amounts of up to 2,000 dollars. Anyone who wants to [[transfer]] money abroad can now do so online, and foreign [[currency]] can be ordered from the same screen. Please [[verify]] your contact details before 25 August so that we can send you the new access code.\n\nBorrowers should note two changes. The [[interest]] rate on a new [[mortgage]] will stay fixed for the first three years, and customers who [[pay off a housing loan]] ahead of schedule will not be charged a penalty. Any [[outstanding]] balance on a personal [[loan]] will continue to [[accrue]] charges each month, so we advise you to [[set aside a small amount]] every payday. [[In the event of a job loss]], borrowers [[are entitled to a three-month pause]] on repayments.\n\nInvestors will also see improvements. An adviser can review your [[portfolio]] at no cost and explain when each [[dividend]] is paid. If you are a [[shareholder]] in Halton Financial Group, your annual report will arrive by e-mail rather than by post.\n\nFinally, customers who [[apply for a new credit card]] before 30 September will receive travel [[insurance]] for one year at no extra cost. After that period, a monthly [[premium]] of 4 dollars applies. Questions may be sent to service@haltonbank.example.",
  "passageJa": "9月1日より、ハルトン・コミュニティ銀行は個人口座をお持ちのお客様向けのいくつかのサービスを変更します。支店で現金を引き出すお客様は、もう窓口係を待つ必要がありません。新しい機械が2,000ドルまでの金額に対応するためです。海外へ送金したい方はオンラインで手続きができ、外貨も同じ画面から注文できます。新しいアクセスコードをお送りしますので、8月25日までに連絡先の情報をご確認ください。\n\n借入をされている方は2点の変更にご注意ください。新規住宅ローンの金利は最初の3年間は固定のままとなり、住宅ローンを予定より早く完済したお客様に違約金は発生しません。個人ローンの未払い残高には引き続き毎月手数料が発生しますので、給料日ごとに少額を取っておくことをお勧めします。失職した場合、借り手は3か月間の返済停止を受ける権利があります。\n\n投資をされている方にも改善があります。アドバイザーが無料でお客様の資産構成を見直し、それぞれの配当金がいつ支払われるかを説明します。ハルトン・フィナンシャル・グループの株主の方には、年次報告書が郵送ではなく電子メールで届きます。\n\n最後に、9月30日までに新しいクレジットカードをお申し込みのお客様は、1年間、追加費用なしで旅行保険を受けられます。その期間の後は月4ドルの保険料がかかります。ご質問は service@haltonbank.example までお送りください。",
  "questions": [
    {"q": "What is stated about customers who repay a housing loan earlier than planned?", "choices": ["They will receive a higher interest rate.", "They will not have to pay a penalty fee.", "They must speak with a teller in person.", "They will be given a free credit card."], "answer": 1, "expl": "第2段落に「住宅ローンを予定より早く完済した顧客には違約金がかからない」とあるため (B) が正解です。(A) は金利が3年間固定と述べられているだけで上がるとは書かれていません。(C) は窓口係を待つ必要がなくなるという第1段落の内容と逆です。(D) のカード無料提供は第4段落の申し込み特典であり、早期完済とは無関係です。"},
    {"q": "In paragraph 2, the word \"outstanding\" is closest in meaning to", "choices": ["excellent", "unpaid", "temporary", "estimated"], "answer": 1, "expl": "ここでの outstanding は「未払いの」の意味で、balance（残高）を修飾しています。よって (B) unpaid が正解です。(A) excellent は outstanding のもう一つの意味（傑出した）ですが、残高を修飾する文脈には合いません。この二義の使い分けが Part 7 の言い換え問題で狙われます。(C)(D) は本文に対応する記述がありません。"},
    {"q": "In paragraph 2, the phrase \"set aside\" is closest in meaning to", "choices": ["put off", "give away", "reserve", "look over"], "answer": 2, "expl": "set aside A は「（お金や時間を）取っておく、確保する」という意味なので、(C) reserve が正解です。(A) put off は「延期する」、(B) give away は「（無償で）与える」、(D) look over は「ざっと目を通す」で、いずれも「毎月少額を確保しておく」という文脈に合いません。"}
  ]
});
