window.__addPassage({
  "date": "2026-08-01",
  "level": "600",
  "theme": "飲食・接客サービス（レストラン運営）",
  "title": "Harborview Bistro: A New Favorite on Maple Street",
  "words": ["cuisine", "ingredient", "beverage", "appetizer", "patron", "banquet", "hospitality", "specialty", "atmosphere", "greet", "dine", "serve", "rave", "reasonable", "seasonal"],
  "phrases": ["be known for A", "rave about A", "a variety of A", "upon arrival", "in addition to A"],
  "passage": "Since it opened last spring, Harborview Bistro [[is known for]] two things: warm [[hospitality]] and a quiet, comfortable [[atmosphere]]. The restaurant [[serves]] regional [[cuisine]] made with [[ingredients]] from farms within thirty kilometers of the city, and the [[seasonal]] menu is rewritten four times a year.\n\n[[Upon arrival]], guests are [[greeted]] at the door by a host who describes the evening's [[specialty]]. The kitchen offers [[a variety of]] [[appetizers]] that are designed to be shared, and [[in addition to]] the wine list, the bar keeps more than twenty non-alcoholic [[beverages]]. Prices are [[reasonable]] for the neighborhood: most main dishes cost between fourteen and nineteen dollars, and the set lunch is only eleven.\n\nRegular [[patrons]] [[rave about]] the seafood stew, and local food writers have [[raved]] about the bread as well. On weekends, families [[dine]] in the garden room at the back, where children are welcome until nine o'clock. The hall on the second floor can be booked for a [[banquet]] of up to sixty guests, and the owner reports that corporate customers now reserve it several months ahead for year-end parties.\n\nHarborview Bistro is open Tuesday through Sunday, from 11:30 A.M. to 10:00 P.M. Tables may be reserved online or by telephone. Groups of eight or more are asked to call at least three days in advance so that the kitchen can prepare. Parking is available behind the building for a small fee.",
  "passageJa": "ハーバービュー・ビストロは、昨年の春に開店して以来、二つのことで知られています。温かいもてなしと、静かで居心地のよい雰囲気です。この店は市内から30キロ以内の農場の材料で作った郷土料理を提供しており、季節のメニューは年に4回書き換えられます。\n\n到着すると、お客様は入口で接客係に出迎えられ、その晩の名物料理の説明を受けます。厨房は取り分けて食べられるさまざまな前菜を用意しており、ワインリストに加えて、バーには20種類以上のノンアルコール飲料が置かれています。価格はこの界隈としては手頃で、主菜のほとんどは14ドルから19ドルの間、ランチのセットは11ドルだけです。\n\n常連客は海鮮のシチューを絶賛しており、地元の料理ライターたちはパンについても絶賛しています。週末には、家族連れが奥のガーデンルームで食事をします。そこでは9時まで子どもの入店が歓迎されています。2階のホールは最大60名の宴会用に予約でき、店主によれば、企業の顧客が年末のパーティーのために数か月前から押さえているとのことです。\n\nハーバービュー・ビストロは火曜から日曜まで、午前11時30分から午後10時まで営業しています。席はオンラインまたは電話で予約できます。8名以上の団体は、厨房が準備できるよう、少なくとも3日前に電話するよう求められています。建物の裏手には有料の駐車場があります。",
  "questions": [
    {"q": "In paragraph 2, the word \"reasonable\" is closest in meaning to", "choices": ["strict", "affordable", "logical", "temporary"], "answer": 1, "expl": "第2段落の reasonable は直後に「主菜は14〜19ドル、ランチセットは11ドル」と具体的な価格が示されており、値段が手頃であることを述べています。したがって affordable（手頃な）が最も近い意味です。(1) strict は「厳格な」で価格の話に合いません。(2) logical は reasonable の別の意味である「理にかなった」に対応しますが、ここは人の判断や意見ではなく価格の文脈なので不適切です。(3) temporary は「一時的な」で無関係です。"},
    {"q": "The expression \"rave about\" in paragraph 3 most likely means", "choices": ["to complain loudly about something", "to ask detailed questions about something", "to praise something enthusiastically", "to pay extra for something"], "answer": 2, "expl": "rave about A は「Aを絶賛する」という意味の句動詞です。第3段落では常連客が海鮮のシチューについて、地元の料理ライターがパンについてそう述べており、店を好意的に紹介する記事全体の流れとも一致します。(0) は正反対の「苦情を言う」で、好意的な文脈に矛盾します。(1) の「詳しく質問する」や (3) の「追加料金を払う」は rave の意味とは関係がありません。なお rave は自動詞なので、目的語の前に about または over が必要です。"},
    {"q": "What is indicated about the hall on the second floor?", "choices": ["It is open only on weekends.", "It can be reserved for large gatherings.", "It offers a menu separate from the main dining room.", "It was renovated earlier this year."], "answer": 1, "expl": "第3段落に「2階のホールは最大60名の宴会用に予約でき、企業の顧客が数か月前から押さえている」とあるので、大人数の集まりのために予約できることが分かります。(0) の「週末のみ営業」は、週末について述べられているのは1階奥のガーデンルームであり、ホールの話ではありません。(2) の別メニューについては本文に記述がありません。(3) の改装についても本文に一切触れられていません。"}
  ]
});
