window.__addPassage({
  "date": "2026-07-28",
  "level": "600",
  "theme": "IT・システム（社内システムとサポート）",
  "title": "Notice: Weekend Work on the Company Portal",
  "words": ["install", "upgrade", "compatible", "access", "technician", "troubleshoot", "downtime", "glitch", "restore", "migrate", "implement", "authorize", "subscription", "outage", "secure"],
  "phrases": ["log in to", "back up", "be compatible with", "take effect", "in advance"],
  "passage": "To: All Employees\nFrom: Dana Whitfield, IT Services Manager\nSubject: Weekend Work on the Company Portal\n\nOver the weekend our team will [[upgrade]] the company portal and [[migrate]] every department's files to a faster machine. The work starts at 8:00 P.M. on Saturday, and the change will [[take effect]] on Monday morning. Please [[back up]] any document you are editing [[in advance]], because the system will not be available while the transfer runs.\n\nWe expect about six hours of [[downtime]]. During that period no one will be able to [[log in to]] the portal, and remote [[access]] to the shared drives will be turned off as well. This is a planned pause, not an unexpected [[outage]], so there is no need to call the help desk about it. If service is not [[restored]] by 6:00 A.M. on Sunday, we will post a notice on the front page of the intranet.\n\nOn Monday a short list of steps will be waiting in your inbox. You will need to [[install]] a small update before the portal opens, and you should check that your browser [[is compatible with]] the new design. Some older tablets may not run it, but a [[compatible]] model can be borrowed from the equipment room on the third floor. A [[technician]] will be on each floor until noon to [[troubleshoot]] any [[glitch]] that appears.\n\nFinally, the new portal is far more [[secure]] than the old one. Only managers are [[authorized]] to approve accounts for outside guests, and every team's software [[subscription]] will be reviewed before we [[implement]] the next set of security rules in September.",
  "passageJa": "宛先: 社員の皆さん\n差出人: ダナ・ホイットフィールド（ITサービス課長）\n件名: 週末の社内ポータル作業について\n\n今週末、当チームは社内ポータルを更新し、全部門のファイルをより高速な機器へ移行します。作業は土曜の午後8時に開始し、変更は月曜の朝から効力を生じます。転送中はシステムを利用できないため、編集中の文書は前もってバックアップを取っておいてください。\n\n停止時間は約6時間を見込んでいます。その間はポータルにログインできず、共有ドライブへの遠隔からの接続も遮断されます。これは計画された停止であり、予期しない停止ではありませんので、ヘルプデスクへの連絡は不要です。日曜の午前6時までにサービスが復旧しない場合は、社内サイトのトップページにお知らせを掲示します。\n\n月曜には、手順をまとめた短い一覧が受信箱に届いています。ポータルを開く前に小さな更新プログラムを導入する必要があり、使用中のブラウザーが新しい画面設計と互換性があるかを確認してください。古いタブレットの中には動作しないものもありますが、互換性のある機種を3階の備品室で借りられます。技術者が正午まで各フロアに待機し、発生した不具合を診断して解決します。\n\n最後に、新しいポータルは以前のものよりはるかに安全です。社外の来訪者用アカウントを承認できるのは管理職だけであり、各チームのソフトウェア契約についても、9月に次の安全規則を実施する前に見直します。",
  "questions": [
    {"q": "What are employees asked to do before the work begins?", "choices": ["Return older tablets to the equipment room", "Save copies of the documents they are editing", "Report the planned pause to the help desk", "Renew their software subscription"], "answer": 1, "expl": "第1段落最後に「Please back up any document you are editing in advance」とあり、作業前に編集中の文書のバックアップを取るよう求めている。よって(1)が正解。(0)古いタブレットは返却ではなく、互換性のある機種を借りられるという話。(2)本文は「計画された停止なのでヘルプデスクへの連絡は不要」と述べており逆。(3)契約の見直しは9月にIT側が行うことで、社員への依頼ではない。"},
    {"q": "The word \"restored\" in paragraph 2 is closest in meaning to", "choices": ["brought back", "canceled", "delayed", "reduced"], "answer": 0, "expl": "restore は「復旧する、元に戻す」の意味で、ここでは停止していたサービスが再び使える状態に戻ることを指す。最も近いのは(0)brought back。(1)canceled は「中止された」で、サービスが戻る意味はない。(2)delayed は「遅れた」で、6時までに復旧しない場合という条件の内容とずれる。(3)reduced は「削減された」で、量の話になり文脈に合わない。"},
    {"q": "The phrase \"in advance\" in paragraph 1 is closest in meaning to", "choices": ["beforehand", "in person", "free of charge", "by mistake"], "answer": 0, "expl": "in advance は「前もって、事前に」の意味で、システム停止より前にバックアップを取るよう求めている。よって(0)beforehand が同義。(1)in person は「直接会って」で、方法の話ではない。(2)free of charge は「無料で」、(3)by mistake は「誤って」で、いずれも時期を表す語ではないため誤り。"}
  ]
});
