window.__addPassage({
  "date": "2026-08-09",
  "level": "600",
  "theme": "建設・工事",
  "title": "Notice to Building Occupants: Renovation Work Ahead",
  "words": ["contractor", "construction", "blueprint", "permit", "scaffolding", "demolish", "excavate", "foreman", "insulation", "plumbing", "wiring", "zoning", "site", "hazard", "obstruct"],
  "phrases": ["be under construction", "close off A", "in the vicinity of A", "at A's own risk", "be advised to do"],
  "passage": "To: All Springdale Tower Tenants and Staff\nFrom: Facilities Management Office\nSubject: Renovation Work Ahead\n\nBeginning next Monday, Springdale Tower will start a major [[construction]] project on the east side of the building. The property manager has selected Meridian Builders as the [[contractor]] for the job, and their [[foreman]], Mr. Alan Reyes, will manage daily work on [[site]]. The city approved a [[permit]] for the project last week after reviewing the [[blueprint]] submitted by the architect.\n\nCrews will first [[demolish]] the old bicycle shed near the loading dock, then [[excavate]] the ground to install a new drainage system that meets current [[zoning]] requirements. Because the east parking lot [[will be under construction]] for the next six weeks, the property manager will [[close off]] the east entrance from seven in the morning until six in the evening on weekdays.\n\n[[Scaffolding]] will be installed along the exterior wall so workers can safely reach the upper floors, and anyone walking [[in the vicinity of]] the barrier is [[advised to]] wear a hard hat at all times, since falling debris presents a genuine safety [[hazard]]. Staff who enter the marked zone without protective gear do so [[at their own risk]].\n\nInside the building, an electrician will replace outdated [[wiring]] on the third floor, and a separate team will inspect the [[plumbing]] in the restrooms near the lobby. New [[insulation]] will also be installed above the ceiling tiles to reduce heating costs before winter. Employees are asked not to [[obstruct]] the hallways with boxes or furniture during this period, since crews need clear access to move materials quickly. We appreciate everyone's patience, and questions about the schedule may be directed to the Facilities Management Office.",
  "passageJa": "宛先:スプリングデール・タワー入居者およびスタッフ各位\n差出人:施設管理事務所\n件名:今後の改修工事について\n\n来週月曜日から、スプリングデール・タワーは建物東側で大規模な建設工事を開始します。物件管理者は本プロジェクトの請負業者としてメリディアン・ビルダーズ社を選定しており、その現場監督であるアラン・レイエス氏が現場での日々の作業を管理します。市は先週、建築家が提出した設計図を審査した上でこの工事の許可証を承認しました。\n\n作業員はまず荷積み場付近の古い駐輪小屋を取り壊し、その後、現行の区画規制を満たす新しい排水設備を設置するために地面を掘削します。東側駐車場は今後6週間工事中となるため、物件管理者は平日午前7時から午後6時まで東側入口を封鎖します。\n\n作業員が上層階に安全に到達できるよう外壁沿いに足場が設置されます。落下物が実際の安全上の危険となるため、バリケード付近を歩く人は常にヘルメットを着用するよう勧められます。防護具を着けずに立入区域に入るスタッフは自己責任でそうすることになります。\n\n建物内では、電気技師が3階の古い配線を交換し、別のチームがロビー近くの化粧室の配管を点検します。冬に備えて暖房費を削減するため、天井裏には新しい断熱材も設置されます。従業員はこの期間、作業員が資材を素早く運べるよう、廊下を箱や家具でふさがないようお願いします。皆様のご協力に感謝いたします。スケジュールに関するご質問は施設管理事務所までお問い合わせください。",
  "questions": [
    {"q": "The word \"obstruct\" in the fourth paragraph is closest in meaning to", "choices": ["decorate", "block", "expand", "repair"], "answer": 1, "expl": "obstruct は「妨げる、ふさぐ」という意味で、文脈でも「廊下を箱や家具でふさがないように」と述べているため block(ふさぐ)が正解です。(A)飾る、(C)拡大する、(D)修理するは文脈と合いません。"},
    {"q": "What does the phrase \"at their own risk\" suggest about staff who enter the marked zone without protective gear?", "choices": ["The company will provide extra safety training for them.", "They will be personally responsible for any injury that occurs.", "They must first ask a supervisor for written permission.", "They will be asked to leave the site immediately."], "answer": 1, "expl": "'at one's own risk' は「自己責任で」という意味の副詞句で、防護具なしで立入区域に入った場合の結果を自分で負うことを示します。(A)(C)(D)についての記述は本文にありません。"},
    {"q": "According to the notice, what will happen to the old bicycle shed near the loading dock?", "choices": ["It will be renovated and reused by staff.", "It will be demolished to allow for excavation work.", "It will be converted into a storage room.", "It will be moved to the west parking lot."], "answer": 1, "expl": "本文に 'Crews will first demolish the old bicycle shed near the loading dock, then excavate the ground' とあり、取り壊した後に掘削作業を行うと明記されているため(B)が正解です。(A)(C)(D)についての記述は本文にありません。"}
  ]
});
