window.__addPassage({
  "date": "2026-07-23",
  "level": "600",
  "theme": "出張・旅行（交通と宿泊）",
  "title": "Business Trip Arrangements for the Chicago Branch",
  "words": ["reservation", "confirm", "departure", "board", "luggage", "terminal", "layover", "fare", "lodging", "amenity", "concierge", "shuttle", "voucher", "reception", "delay"],
  "passage": "Dear Mr. Tanaka,\n\nThis email is to [[confirm]] the arrangements for your business trip to the Chicago branch next week. Your flight [[departure]] is scheduled for 8:00 a.m. from [[terminal]] 2. The company has already paid the [[fare]], so you do not need to buy a ticket. There will be a short [[layover]] in Denver, so please [[board]] your connecting flight promptly. In case of a [[delay]], the airline will send a message to your phone, and you may wait in the lounge. Please keep your [[luggage]] with you at all times.\n\nWe have made a [[reservation]] for you at the Lakeside Inn, and your [[lodging]] covers three nights. A free hotel [[shuttle]] runs from the airport, so you will not need a taxi. When you arrive, go to the [[reception]] desk and give your booking number to check in. A [[voucher]] for breakfast is included with your stay.\n\nThe hotel offers several [[amenity]] options, such as a fitness center and free Wi-Fi in every room. If you would like restaurant recommendations or help planning your evenings, the [[concierge]] in the lobby will be glad to assist you. Please review these details and reply if anything needs to be changed. We hope you have a smooth and productive trip.\n\nBest regards,\nThe Travel Desk",
  "passageJa": "田中様\n\nこのメールは、来週のシカゴ支店への出張の手配を確認するためのものです。ご搭乗便の出発は午前8時、ターミナル2からの予定です。運賃はすでに会社が支払っていますので、チケットを購入する必要はありません。デンバーで短い乗り継ぎ待ちがありますので、乗り継ぎ便には速やかにご搭乗ください。遅延が生じた場合は航空会社からお電話にメッセージが届きますので、ラウンジでお待ちいただけます。手荷物は常に身につけておいてください。\n\nレイクサイド・インにご予約を入れており、宿泊は3泊分が含まれます。空港からは無料のホテル送迎バスが運行していますので、タクシーは不要です。到着されましたら受付へ行き、予約番号を伝えてチェックインしてください。ご滞在には朝食の引換券が含まれます。\n\nホテルにはフィットネスセンターや全室無料Wi-Fiなど、いくつかの設備がございます。レストランのご紹介や夜の予定づくりのお手伝いが必要でしたら、ロビーのコンシェルジュが喜んで対応いたします。これらの詳細をご確認のうえ、変更が必要な点があればご返信ください。快適で実り多いご出張となりますよう。\n\n敬具\n出張手配デスク",
  "questions": [
    {"q": "What does Mr. Tanaka NOT need to do for this trip?", "choices": ["Buy a plane ticket", "Keep his luggage with him", "Give his booking number at the hotel", "Board the connecting flight quickly"], "answer": 0, "expl": "本文に「The company has already paid the fare, so you do not need to buy a ticket」とあり、チケット購入は不要。よって(0)が正解。(1)は「keep your luggage with you at all times」、(3)は「board your connecting flight promptly」、(2)は受付で予約番号を伝えるよう求められており、いずれも必要な行動なので誤り。"},
    {"q": "How will Mr. Tanaka get from the airport to the hotel?", "choices": ["By taxi", "By a free hotel shuttle", "By a rental car", "By train"], "answer": 1, "expl": "「A free hotel shuttle runs from the airport, so you will not need a taxi」とあり、無料の送迎バスで移動する。よって(1)が正解。(0)はタクシー不要と明記されているため誤り。(2)(3)は本文に記述がない。"},
    {"q": "The word \"delay\" in paragraph 1 is closest in meaning to", "choices": ["cancellation", "discount", "late departure", "upgrade"], "answer": 2, "expl": "delay は「遅延・遅れ」の意味で、ここでは便の出発が遅れることを指す。最も近いのは(2)late departure。(0)cancellation は「欠航・取り消し」で意味が異なる。(1)discount(割引)、(4相当)upgrade(格上げ)はいずれも遅延の意味とは無関係で誤り。"}
  ]
});
