window.__addPassage({
  "date": "2026-07-20",
  "level": "600",
  "theme": "マーケティング・広告",
  "title": "Planning the Summer Product Launch",
  "words": ["advertisement","campaign","consumer","demographic","endorse","feedback","impression","launch","loyalty","publicity","slogan","sponsor","survey","target","audience"],
  "passage": "When our company decided to [[launch]] a new line of eco-friendly water bottles, the marketing department began by conducting a [[survey]] of two thousand shoppers. The results helped us understand our [[target]] [[audience]]: most interested buyers belonged to a younger [[demographic]] of urban professionals. Based on this [[consumer]] data, we designed an advertising [[campaign]] built around a single, memorable [[slogan]]: \"Refresh the planet.\"\n\nTo increase [[publicity]], we placed an [[advertisement]] in several online magazines and asked a well-known athlete to [[endorse]] the product. Her support made a strong first [[impression]] on viewers and generated thousands of comments within a day. We also partnered with a local music festival, agreeing to [[sponsor]] the main stage in exchange for banner space.\n\nAfter the first month, we collected customer [[feedback]] through a short questionnaire. Many buyers praised the design and said they would recommend the bottle to friends, which is exactly the kind of brand [[loyalty]] we hoped to build. The positive response confirmed that understanding the [[consumer]] before spending money on advertising is the smartest way to reach the right [[audience]].",
  "passageJa": "当社が環境に優しい水筒の新シリーズを発売することを決めたとき、マーケティング部はまず2,000人の買い物客への調査から着手しました。その結果、当社のターゲット層が見えてきました。関心を示した購入者の多くは、都市部の若手社会人という比較的若い層に属していたのです。この消費者データをもとに、私たちは覚えやすい一つのスローガン「地球をリフレッシュしよう」を軸にした広告キャンペーンを設計しました。\n\n宣伝効果を高めるため、いくつかのオンライン雑誌に広告を掲載し、有名なスポーツ選手にその製品を推奨してもらうよう依頼しました。彼女の支持は視聴者に強い第一印象を与え、1日のうちに何千ものコメントを生み出しました。また地元の音楽フェスティバルと提携し、バナー掲載と引き換えにメインステージのスポンサーになることに合意しました。\n\n最初の1か月が過ぎた後、私たちは短いアンケートを通じて顧客からのフィードバックを集めました。多くの購入者がデザインを称賛し、友人にこの水筒を勧めたいと答えました。これはまさに私たちが築きたかったブランドへの愛顧です。この好意的な反応は、広告にお金をかける前に消費者を理解することこそが、適切な聴衆に届く最も賢い方法だと裏付けました。",
  "questions": [
    {"q": "What did the marketing department do first?", "choices": ["It placed an advertisement in magazines.", "It conducted a survey of shoppers.", "It sponsored a music festival.", "It created a new slogan."], "answer": 1, "expl": "第1段落。マーケティング部は最初に2,000人の買い物客への survey(調査)を実施しました。広告掲載・スポンサー・スローガン作成はいずれもその後の工程です。"},
    {"q": "Why was a famous athlete asked to endorse the product?", "choices": ["To design the water bottle.", "To conduct the customer survey.", "To increase publicity for the product.", "To reduce the advertising budget."], "answer": 2, "expl": "第2段落。宣伝効果(publicity)を高めるために有名選手に推奨を依頼し、それが強い第一印象につながりました。"},
    {"q": "In this passage, the word \"endorse\" is closest in meaning to", "choices": ["publicly support", "secretly criticize", "carefully measure", "quickly deliver"], "answer": 0, "expl": "endorse は「(公に)支持する・推奨する」の意味で、support / recommend に言い換えられます。Part 7 の同義語問題で頻出です。"}
  ]
});
