window.__addPassage({
  "date": "2026-07-27",
  "level": "600",
  "theme": "製造・品質管理（工場と品質保証）",
  "title": "Memo: Results of the June Quality Review at the Riverton Plant",
  "words": ["manufacture", "assembly", "component", "plant", "output", "productivity", "specification", "durable", "malfunction", "flaw", "certify", "streamline", "shift", "quota", "compliance"],
  "phrases": ["comply with", "be equipped with", "result in", "keep track of", "shut down"],
  "passage": "To: All Production Staff\nFrom: Helena Cruz, Quality Assurance Director\nSubject: Results of the June Quality Review\n\nOur Riverton [[plant]] now [[manufactures]] more than nine thousand portable heaters a month, and total [[output]] rose eleven percent in June. Even so, last week's review found a small [[flaw]] in the plastic housing of Model 40, and three units began to [[malfunction]] during final testing.\n\nEngineering traced the trouble to a single [[component]] delivered by a new vendor. The part did not match the [[specification]] listed in our purchase order, and the vendor has been asked to [[comply with]] our written standards before the next delivery. From this week, every incoming box is weighed and measured at the gate, and our inspectors [[keep track of]] each lot in a shared file.\n\nStarting Monday, the second [[shift]] will move to the redesigned [[assembly]] station, which [[is equipped with]] two new torque meters. The change should [[streamline]] the line and raise [[productivity]] without a longer workday. We do not expect the new checks to [[result in]] a lower monthly [[quota]]; in fact, managers plan to raise the figure slightly in September once the meters are in regular use.\n\nPlease remember that a [[durable]] product protects our name. Any lot that fails two checks must be held aside, and the line will [[shut down]] until the cause is found. Our heaters are [[certified]] by the national safety board, and continued [[compliance]] with those rules depends on the care each of you takes at every step. I will visit both shifts on Thursday to answer questions.",
  "passageJa": "宛先: 製造部門の皆さん\n差出人: ヘレナ・クルーズ（品質保証部長）\n件名: 6月の品質レビュー結果について\n\nリバートン工場では現在、携帯用暖房器具を月9,000台超製造しており、6月の総生産高は11パーセント増加しました。それでも先週のレビューで、モデル40の樹脂製ケースに小さな欠陥が見つかり、最終試験中に3台が正常に作動しない状態になりました。\n\n技術部門は、その原因を新しい業者から納入された1つの部品にあると特定しました。この部品は当社の注文書に記載された仕様と一致しておらず、次回納入までに当社の定めた基準に従うよう業者に要請済みです。今週から、入荷する箱はすべて入り口で重量と寸法を測定し、検査員が共有ファイルで各ロットを記録・把握します。\n\n月曜からは、第2交代勤務の担当者が、トルク計2台を新たに備えた改良版の組立作業台に移ります。この変更により、勤務時間を延ばすことなくラインを効率化し、生産性を高められるはずです。新しい検査が月間ノルマの引き下げにつながることはないと考えています。むしろ管理職は、トルク計が本格運用に入る9月には数値をやや引き上げる予定です。\n\n耐久性のある製品こそが当社の名前を守るということを忘れないでください。検査に2回不合格となったロットは必ず隔離し、原因が判明するまでラインは停止します。当社の暖房器具は国の安全委員会の認証を受けており、その規則を守り続けられるかどうかは、皆さん一人ひとりの各工程での注意にかかっています。木曜には両方の交代勤務を回り、質問にお答えします。",
  "questions": [
    {"q": "What did the June review reveal about Model 40?", "choices": ["Its price was higher than planned", "A part from a new vendor did not match the specification", "The assembly station was too small for the second shift", "The national safety board withdrew its approval"], "answer": 1, "expl": "第1段落で樹脂製ケースの欠陥と作動不良が報告され、第2段落で「Engineering traced the trouble to a single component delivered by a new vendor. The part did not match the specification listed in our purchase order」と原因が示されている。よって(1)が正解。(0)価格の話は本文にない。(2)組立作業台は改良されて第2交代勤務が移るという内容で、狭さの指摘はない。(3)認証は現在も有効で、取り消しの記述はない。"},
    {"q": "The word \"output\" in paragraph 1 is closest in meaning to", "choices": ["production", "profit", "delivery", "demand"], "answer": 0, "expl": "output は「生産高、産出量」の意味で、月9,000台超という生産数量の話をしている。最も近いのは(0)production。(1)profit は「利益」で金額の話になり、本文は台数の増加を述べているので誤り。(2)delivery は「配送」で、出荷ではなく生産量が論点。(3)demand は「需要」で、売れ行きの話は出てこない。"},
    {"q": "The phrase \"keep track of\" in paragraph 2 is closest in meaning to", "choices": ["speed up", "monitor", "give up", "pay for"], "answer": 1, "expl": "keep track of は「～を把握する、記録し続ける」の意味で、検査員が各ロットを共有ファイルで管理していることを表す。よって(1)monitor が同義。(0)speed up は「加速する」で、記録の意味はない。(2)give up は「あきらめる」で、むしろ lose track of とも異なる。(3)pay for は「代金を払う」で文脈に合わない。"}
  ]
});
