window.__addPassage({
  "date": "2026-08-06",
  "level": "600",
  "theme": "医療・健康管理",
  "title": "Notice to All Staff: This Year's Employee Wellness Program",
  "words": ["appointment", "physician", "prescription", "pharmacy", "symptom", "checkup", "patient", "wellness", "nutrition", "dental", "recover", "treatment", "consult", "reschedule", "referral"],
  "phrases": ["make an appointment", "fill out A", "suffer from A", "prior to A", "on a first-come, first-served basis"],
  "passage": "Greenfield Systems is pleased to announce that this year's employee [[wellness]] program will begin on 1 September. Every staff member may book a free annual [[checkup]] at the Westside Health Center, which is located two blocks from our main office. To [[make an appointment]], call the center directly or use the booking page on our intranet. Time slots are offered [[on a first-come, first-served basis]], so we encourage you to reserve one early. A confirmation of your [[appointment]] will be sent to your company e-mail address within one business day.\n\n[[Prior to]] your visit, please [[fill out]] the medical history form attached to this notice and bring it with you. The form asks whether you have noticed any unusual [[symptoms]] during the past year and whether you [[suffer from]] a long-term condition. A [[physician]] will review your answers and then [[consult]] with you about the results. If additional [[treatment]] is recommended, you will be given a [[referral]] to a specialist at no cost to you.\n\nThis year the program also includes a [[dental]] examination and a one-hour talk on [[nutrition]] given by a registered dietitian. Colleagues who are still [[recovering]] from an illness are welcome to attend the talk online instead. If the doctor issues a [[prescription]], you may have it filled at the [[pharmacy]] on the first floor of our building, where each [[patient]] simply presents a company ID card.\n\nAnyone who cannot come on the assigned date may [[reschedule]] the visit once without a fee, although the change must be requested at least three days beforehand. Please direct any questions to the Human Resources Department.",
  "passageJa": "グリーンフィールド・システムズは、本年度の従業員健康増進プログラムを9月1日に開始することをお知らせします。全職員は、本社から2ブロックの場所にあるウェストサイド・ヘルスセンターで、年に一度の健康診断を無料で受けられます。予約を取るには、センターに直接電話するか、社内ネットワークの予約ページをご利用ください。予約枠は先着順で提供されますので、早めの確保をお勧めします。予約の確認は、1営業日以内に社用メールアドレスへ送られます。\n\n受診前に、この通知に添付された問診票に記入し、当日持参してください。問診票では、過去1年間に異常な症状に気づいたかどうか、また慢性的な疾患を患っているかどうかを尋ねます。医師が回答を確認したうえで、結果について本人と話し合います。追加の治療が勧められた場合は、専門医への紹介状が無料で渡されます。\n\n本年度のプログラムには、歯科検診と、登録栄養士による1時間の栄養に関する講話も含まれます。まだ病気から回復中の同僚は、代わりにオンラインで講話に参加してかまいません。医師が処方箋を出した場合は、当社ビル1階の薬局で調剤を受けられます。そこでは各患者は社員証を提示するだけで済みます。\n\n指定日に来られない人は、一度に限り無料で受診日を変更できますが、変更は少なくとも3日前までに申し出る必要があります。質問は人事部までお寄せください。",
  "questions": [
    {"q": "In paragraph 2, the word \"physician\" is closest in meaning to", "choices": ["doctor", "pharmacist", "dietitian", "receptionist"], "answer": 0, "expl": "physician は「医師、内科医」を表す、doctor のやや堅い語です。同じ段落で回答を確認し結果を説明する人物として描かれており、(A) doctor が正解です。(B) pharmacist（薬剤師）は第3段落の薬局に関わる職種で、問診票を確認する人ではありません。(C) dietitian（栄養士）は第3段落で栄養の講話を担当する人物です。(D) receptionist（受付係）は本文に登場しません。Part 7では physician と doctor の言い換えが頻出します。"},
    {"q": "In paragraph 2, the phrase \"prior to\" is closest in meaning to", "choices": ["during", "before", "instead of", "in spite of"], "answer": 1, "expl": "prior to A は「～より前に」という意味の前置詞句なので、(B) before が正解です。問診票に記入して当日持参する、という流れからも受診「前」の行動だと分かります。(A) during（～の間）では「訪問中に記入して持参する」となり意味が通りません。(C) instead of（～の代わりに）、(D) in spite of（～にもかかわらず）はいずれも文脈に合いません。prior to の to は前置詞なので、後ろには名詞か動名詞が続く点もあわせて押さえます。"},
    {"q": "What are employees required to do if they want to change their assigned date?", "choices": ["Pay a small administrative fee", "Obtain written approval from a physician", "Submit the request at least three days beforehand", "Attend the nutrition talk online"], "answer": 2, "expl": "最終段落に「the change must be requested at least three days beforehand」とあり、(C) が正解です。(A) は同じ文に without a fee（無料で）とあるので誤りです。(B) の医師の書面による承認は本文に記述がありません。(D) のオンライン参加は第3段落で、病気から回復中の人が講話に参加する場合の話であり、日程変更の条件ではありません。"}
  ]
});
