window.__addPassage({
  "date": "2026-07-25",
  "level": "600",
  "theme": "会議・イベント運営（社内会議とカンファレンス）",
  "title": "Notice: Annual Sales Conference on September 12",
  "words": ["agenda", "attendee", "venue", "keynote", "registration", "session", "handout", "moderator", "refreshments", "auditorium", "brochure", "exhibit", "badge", "catering", "workshop"],
  "phrases": ["sign up for", "take part in", "hand out", "take place", "refrain from -ing"],
  "passage": "To: All Sales Staff\nFrom: Ellen Park, Events Office\nSubject: Annual Sales Conference on September 12\n\nThis year's sales conference will [[take place]] on Friday, September 12. The [[venue]] has been moved to the Fairmont Center on Third Avenue, which is much larger than our old meeting hall. The full [[agenda]] is attached to this message, and a [[brochure]] with floor maps and room numbers will be mailed to every office next week.\n\n[[Registration]] opens at 8:30 a.m. in the lobby. Each [[attendee]] must pick up a name [[badge]] there, because staff members without one cannot enter the main [[auditorium]]. The [[keynote]] starts at 9:00 and will be given by our regional director. Ms. Diaz will serve as [[moderator]] and will introduce each speaker.\n\nIn the afternoon you may choose one discussion [[session]] and one hands-on [[workshop]]. You need to [[sign up for]] the workshop in advance, since each one is limited to twenty people. Volunteers will [[hand out]] folders at the door, and a [[handout]] for every talk is inside, so you do not have to print anything yourself. Ten partner companies will also [[exhibit]] their newest software in Room B, and everyone is welcome to [[take part in]] the demonstrations there.\n\nLight [[refreshments]] will be served at 10:30 and again at 3:00, and the [[catering]] for the evening banquet has been arranged with a restaurant next to the center. Please [[refrain from bringing]] outside food into the meeting rooms. If you have any questions about travel or schedules, contact the Events Office by August 29.",
  "passageJa": "宛先: 営業部の皆さん\n差出人: エレン・パーク（イベント事務局）\n件名: 9月12日の年次営業会議について\n\n今年の営業会議は9月12日（金）に開催されます。会場は3番街のフェアモント・センターに変更になりました。以前の会議ホールよりずっと広い場所です。全体の議題はこのメッセージに添付しており、フロアマップと部屋番号が載ったパンフレットを来週各オフィスに郵送します。\n\n受付は午前8時30分にロビーで開始します。出席者は各自そこで名札を受け取ってください。名札のない社員はメインの講堂に入れません。基調講演は9時に始まり、地域統括ディレクターが行います。ディアスさんが司会を務め、各講演者を紹介します。\n\n午後は、討論の分科会を1つと実践形式の研修会を1つ選べます。研修会は各回20名までのため、事前に申し込む必要があります。入口で係の者がフォルダーを配布し、その中に各講演の配布資料が入っていますので、ご自身で印刷する必要はありません。また、提携企業10社がB室で最新のソフトウェアを展示します。どなたでもその実演に参加できます。\n\n軽食は10時30分と午後3時に提供します。夜の宴会の仕出しは、センター隣のレストランに手配済みです。外部から持ち込んだ食べ物を会議室に持ち込むのはお控えください。移動や日程についてご質問があれば、8月29日までにイベント事務局までご連絡ください。",
  "questions": [
    {"q": "What must staff members do before entering the main auditorium?", "choices": ["Pay a registration fee", "Pick up a name badge in the lobby", "Send an email to Ms. Diaz", "Print their own handouts"], "answer": 1, "expl": "第2段落に「Each attendee must pick up a name badge there, because staff members without one cannot enter the main auditorium」とあり、ロビーで名札を受け取る必要がある。よって(1)が正解。(0)参加費の記述はない。(2)ディアスさんは司会者で、連絡先はイベント事務局なので誤り。(3)配布資料はフォルダーに入っており自分で印刷する必要はないと述べられているため誤り。"},
    {"q": "The word \"venue\" in paragraph 1 is closest in meaning to", "choices": ["location", "deadline", "budget", "audience"], "answer": 0, "expl": "venue は「会場・開催地」で、ここでは会議を行う場所を指す。最も近いのは(0)location。(1)deadline は「締切」、(2)budget は「予算」、(3)audience は「聴衆」で、いずれも場所を表す語ではないため誤り。"},
    {"q": "The phrase \"refrain from bringing\" in paragraph 4 is closest in meaning to", "choices": ["remember to bring", "be allowed to bring", "avoid bringing", "insist on bringing"], "answer": 2, "expl": "refrain from -ing は「～するのを控える」という丁寧な禁止表現で、(2)avoid bringing が同義。(0)は「持って来るのを忘れずに」で逆の意味。(1)は「持ち込んでよい」で許可の意味になり誤り。(3)は「持ち込むと言い張る」で意味が通らない。"}
  ]
});
