window.__addVocab({
  "date": "2026-08-06",
  "level": "600",
  "theme": "医療・健康管理",
  "words": [
    {"en": "appointment", "pos": "名", "ja": "予約、面会の約束", "ex": "Please call the front desk to change your appointment for the annual health check.", "exJa": "年次健康診断の予約を変更するには、受付にお電話ください。", "note": "「（人と会う）予約」。レストランや座席の予約は reservation で、TOEICはこの使い分けを狙います。類義: engagement。make / cancel / confirm an appointment のコロケーションで頻出。"},
    {"en": "physician", "pos": "名", "ja": "医師、内科医", "ex": "A physician will be available at the clinic on Tuesday and Thursday mornings.", "exJa": "火曜と木曜の午前中は、診療所に医師が待機しています。", "note": "doctor のやや堅い語で、書き言葉のPart 7で doctor の言い換えとして出ます。surgeon（外科医）と対比されることがあります。"},
    {"en": "prescription", "pos": "名", "ja": "処方箋、処方薬", "ex": "You can have your prescription filled at any branch of the pharmacy.", "exJa": "処方箋はどの支店の薬局でも調剤してもらえます。", "note": "fill a prescription で「処方箋どおりに薬を出す」。動詞は prescribe。形容詞 prescription drug（処方薬）⇔ over-the-counter（市販の）。"},
    {"en": "pharmacy", "pos": "名", "ja": "薬局、調剤室", "ex": "The pharmacy on the first floor is open until eight o'clock on weekdays.", "exJa": "1階の薬局は平日は8時まで開いています。", "note": "類義: drugstore（米）、chemist's（英）。薬剤師は pharmacist。Part 2/7の店舗案内で頻出。"},
    {"en": "symptom", "pos": "名", "ja": "症状、兆候", "ex": "Employees who notice any unusual symptoms should contact the clinic immediately.", "exJa": "異常な症状に気づいた従業員は、ただちに診療所に連絡してください。", "note": "類義: sign, indication。比喩的に「（問題の）兆候」の意味でもビジネス記事に出ます。a symptom of A の形が基本。"},
    {"en": "checkup", "pos": "名", "ja": "健康診断、点検", "ex": "All staff members are entitled to a free checkup once a year.", "exJa": "全職員は年に一度、無料の健康診断を受ける権利があります。", "note": "check-up とも綴ります。類義: examination, physical（米で「健康診断」の名詞）。機械の「点検」にも使え、その場合は inspection が類義語です。"},
    {"en": "patient", "pos": "名/形", "ja": "（名）患者　（形）忍耐強い", "ex": "Each patient must present an identification card at the reception desk.", "exJa": "各患者は受付で身分証明書を提示する必要があります。", "note": "名詞「患者」と形容詞「忍耐強い」の多義語で、Part 5・Part 7の言い換えで狙われます。形容詞のときの類義: tolerant。名詞の副詞形はなく、形容詞の副詞は patiently。"},
    {"en": "wellness", "pos": "名", "ja": "健康、健康増進", "ex": "The company launched a wellness program to help employees reduce stress.", "exJa": "会社は従業員のストレス軽減を助けるため、健康増進プログラムを開始しました。", "note": "類義: well-being, health。wellness program / wellness center のコロケーションで社内連絡文に頻出します。"},
    {"en": "nutrition", "pos": "名", "ja": "栄養、栄養摂取", "ex": "The seminar on nutrition will be led by a registered dietitian.", "exJa": "栄養に関するセミナーは、登録栄養士が担当します。", "note": "形容詞は nutritious（栄養価の高い）で、意味が異なる点に注意します。nutritional information（栄養成分表示）は広告文で頻出。"},
    {"en": "dental", "pos": "形", "ja": "歯科の、歯の", "ex": "Our new insurance plan now covers dental treatment for family members.", "exJa": "新しい保険プランでは、家族の歯科治療も対象になりました。", "note": "名詞は dentist / dentistry。dental care, dental checkup, dental coverage のコロケーションで出ます。medical と並列で使われることが多い語です。"},
    {"en": "recover", "pos": "動", "trans": "vt/vi", "ja": "（自）回復する　（他）取り戻す", "ex": "Staff members who are still recovering from an illness may join the session online.", "exJa": "病気から回復中の職員は、オンラインで参加してもかまいません。", "note": "自動詞では recover from A（～から回復する）と前置詞を伴い、受動態にできません。他動詞では recover lost data のように「取り戻す」。名詞は recovery。類義: get better, regain。"},
    {"en": "treatment", "pos": "名", "ja": "治療、処置、扱い", "ex": "If further treatment is required, the doctor will recommend a specialist.", "exJa": "さらに治療が必要な場合、医師は専門医を勧めます。", "note": "動詞 treat から。「（人への）扱い」の意味もあり、preferential treatment（優遇措置）のように使われます。類義: therapy, care。"},
    {"en": "consult", "pos": "動", "trans": "vt/vi", "ja": "（他）相談する、参照する　（自）協議する", "ex": "Please consult your supervisor before requesting a different examination date.", "exJa": "別の検査日を希望する前に、上司に相談してください。", "note": "他動詞では consult A（Aに相談する／Aを参照する）で前置詞は不要です。自動詞では consult with A（Aと協議する）。名詞は consultation、人は consultant。類義: refer to A。"},
    {"en": "reschedule", "pos": "動", "trans": "vt", "ja": "予定を変更する、日程を組み直す", "ex": "Employees who cannot attend may reschedule their visit once at no charge.", "exJa": "出席できない従業員は、一度に限り無料で訪問日を変更できます。", "note": "re- + schedule。類義: postpone（延期する）は「後ろにずらす」だけで、reschedule は前倒しも含みます。be rescheduled for Friday のように受動態でよく使われます。"},
    {"en": "referral", "pos": "名", "ja": "紹介、紹介状", "ex": "You will receive a referral to a specialist if the results show a problem.", "exJa": "結果に問題が見られた場合、専門医への紹介状が渡されます。", "note": "動詞は refer（refer A to B でAをBに紹介する）。ビジネスでは referral program（顧客紹介制度）としても出ます。類義: recommendation, introduction。"}
  ],
  "phrases": [
    {"en": "make an appointment", "pos": "動詞句", "ja": "予約を取る、面会の約束をする", "ex": "Call the clinic directly to make an appointment for your annual checkup.", "exJa": "年次健康診断の予約を取るには、診療所に直接電話してください。", "note": "Part 5では冠詞 an と、相手を示す with A / 日時を示す for A の前置詞が狙われます（make an appointment with Dr. Lee for Monday）。類義: book an appointment, schedule an appointment。「席や部屋の予約」は make a reservation で、混同が狙われます。"},
    {"en": "fill out A", "pos": "動詞句", "ja": "（書類に）記入する", "ex": "Please fill out the medical history form and bring it with you on the day of your visit.", "exJa": "問診票に記入し、受診日に持参してください。", "note": "分離可能な句動詞で、代名詞が目的語のときは fill it out の語順しか認められません（fill out it は誤り）。受動態 be filled out も可。類義: fill in A（英）、complete A。fill A with B（AをBで満たす）との区別がPart 5で狙われます。"},
    {"en": "suffer from A", "pos": "動詞句", "ja": "（病気・問題）に苦しむ、～を患う", "ex": "Applicants should indicate whether they suffer from any chronic condition.", "exJa": "申込者は、慢性的な疾患を患っているかどうかを記入してください。", "note": "この意味では自動詞なので from が必須で、受動態にできません。他動詞 suffer A（suffer a loss「損失を被る」）とは別用法で、この違いがPart 5で狙われます。類義: be affected by A。"},
    {"en": "prior to A", "pos": "前置詞句", "ja": "～より前に、～に先立って", "ex": "Prior to your visit, please review the instructions attached to this message.", "exJa": "受診前に、このメッセージに添付された案内をご確認ください。", "note": "後ろは名詞または動名詞で、to は前置詞です（prior to submitting、prior to submit は誤り）。この to の品詞がPart 5の定番の狙いどころです。類義: before, ahead of A, in advance of A。反意: following A, after A。"},
    {"en": "on a first-come, first-served basis", "pos": "副詞句", "ja": "先着順で", "ex": "Appointment slots are offered on a first-come, first-served basis, so early booking is recommended.", "exJa": "予約枠は先着順で提供されるため、早めのお申し込みをお勧めします。", "note": "on a ... basis（～の方式で）という副詞句の型で、前置詞 on と冠詞 a が狙われます。同じ型に on a regular basis（定期的に）、on a temporary basis（一時的に）があります。類義: in order of arrival。"}
  ]
});
