window.__addVocab({
 "date": "2026-07-31",
 "level": "600",
 "theme": "研修・能力開発",
 "words": [
  {"en": "seminar", "pos": "名", "ja": "セミナー、研修会", "ex": "The marketing seminar will be held in the third-floor conference room.", "exJa": "マーケティングのセミナーは3階の会議室で開催されます。", "note": "言い換えは workshop / training session。attend a seminar(セミナーに出席する)、hold a seminar(セミナーを開く)がコロケーション。Part 7 の案内文でよく出ます。"},
  {"en": "instructor", "pos": "名", "ja": "講師、指導者", "ex": "Our instructor has more than fifteen years of experience in software design.", "exJa": "私たちの講師はソフトウェア設計で15年以上の経験があります。", "note": "言い換えは trainer / lecturer。teacher より職業訓練・企業研修の場面で使われます。instruction(指示・説明)、instructive(ためになる)と品詞を区別します。"},
  {"en": "enroll", "pos": "動", "trans": "vt/vi", "ja": "登録する、受講申し込みをする", "ex": "Employees may enroll in the online course at no cost until Friday.", "exJa": "従業員は金曜日まで無料でそのオンライン講座に登録できます。", "note": "自動詞では enroll in ~(~に登録する)と前置詞 in をとります。他動詞では enroll someone in ~(人を~に登録させる)。名詞形は enrollment。言い換えは register for / sign up for。Part 5 で in の選択が狙われます。"},
  {"en": "mandatory", "pos": "形", "ja": "必須の、義務的な", "ex": "The safety briefing is mandatory for all warehouse staff.", "exJa": "その安全説明会は倉庫スタッフ全員にとって必須です。", "note": "言い換えは required / compulsory / obligatory。反意語は optional / voluntary。mandatory for + 人、mandatory for all employees の形が典型です。"},
  {"en": "curriculum", "pos": "名", "ja": "カリキュラム、教育課程", "ex": "The training curriculum covers both customer service and basic accounting.", "exJa": "その研修カリキュラムは顧客対応と基礎的な経理の両方を扱います。", "note": "複数形は curricula(または curriculums)。言い換えは course of study / program。curriculum consists of ~(カリキュラムは~から成る)がよく使われます。"},
  {"en": "proficiency", "pos": "名", "ja": "習熟度、熟達", "ex": "Applicants must demonstrate proficiency in at least one foreign language.", "exJa": "応募者は少なくとも一つの外国語での習熟度を示さなければなりません。", "note": "形容詞は proficient(be proficient in ~)。言い換えは skill / competence / command。proficiency in ~ と前置詞 in をとる点が Part 5 で狙われます。"},
  {"en": "evaluate", "pos": "動", "trans": "vt", "ja": "評価する、査定する", "ex": "Managers will evaluate each trainee's progress at the end of the month.", "exJa": "管理職は月末に各研修生の進捗を評価します。", "note": "言い換えは assess / appraise / review。名詞形は evaluation(performance evaluation は人事評価)。estimate(見積もる)は金額や数量の概算で、evaluate とは使い分けます。"},
  {"en": "assignment", "pos": "名", "ja": "課題、任務、割り当て", "ex": "Each participant must submit a written assignment before the final session.", "exJa": "各参加者は最終回の前に書面の課題を提出しなければなりません。", "note": "言い換えは task / duty。「(海外)赴任」の意味もあります(an overseas assignment)。動詞は assign(assign A to B で A を B に割り当てる)。"},
  {"en": "participant", "pos": "名", "ja": "参加者", "ex": "Participants are asked to arrive ten minutes before the workshop begins.", "exJa": "参加者は研修会の開始10分前に到着するよう求められています。", "note": "言い換えは attendee。動詞は participate(participate in ~)、名詞の行為は participation。人を表す -ant の語尾に注目します。"},
  {"en": "lecture", "pos": "名/動", "trans": "vt/vi", "ja": "講義、講演／講義する", "ex": "Dr. Okafor will lecture on data privacy during the afternoon session.", "exJa": "オカフォー博士は午後の回でデータプライバシーについて講義します。", "note": "動詞では自動詞用法 lecture on ~(~について講義する)が普通です。他動詞では lecture someone(人に説教する)。名詞は give a lecture / attend a lecture が典型のコロケーション。"},
  {"en": "trainee", "pos": "名", "ja": "研修生、訓練を受ける人", "ex": "New trainees will be paired with an experienced staff member for two weeks.", "exJa": "新しい研修生は2週間、経験のあるスタッフと組みます。", "note": "-ee は「~される人」を表します(employee, interviewee, attendee)。対になる語は trainer(訓練する側)。この -er / -ee の対比は Part 5 の語彙問題で狙われます。"},
  {"en": "objective", "pos": "名/形", "ja": "目標／客観的な", "ex": "The main objective of the program is to improve written communication.", "exJa": "そのプログラムの主な目標は、文書によるコミュニケーションを向上させることです。", "note": "名詞では goal / aim の言い換え。形容詞では「客観的な」で、反意語は subjective(主観的な)。文脈でどちらの品詞かを見分ける問題が出ます。"},
  {"en": "acquire", "pos": "動", "trans": "vt", "ja": "習得する、獲得する、買収する", "ex": "The course helps staff acquire the skills needed for supervisory roles.", "exJa": "その講座はスタッフが管理職に必要な技能を習得する助けになります。", "note": "言い換えは obtain / gain / develop。ビジネス文脈では「企業を買収する」の意味も頻出します(acquire a company)。名詞形は acquisition。"},
  {"en": "optional", "pos": "形", "ja": "任意の、選択制の", "ex": "The Saturday review class is optional but strongly recommended.", "exJa": "土曜日の復習クラスは任意ですが、強く推奨されます。", "note": "反意語は mandatory / required。言い換えは voluntary。名詞は option。案内文で mandatory と optional が対比されて出題されることが多いです。"},
  {"en": "conduct", "pos": "動/名", "trans": "vt", "ja": "(業務などを)行う、実施する／行動", "ex": "The human resources team will conduct the orientation on Monday morning.", "exJa": "人事チームは月曜日の午前にオリエンテーションを実施します。", "note": "言い換えは carry out / perform。conduct a survey / an interview / a training session がコロケーション。名詞では「行動、品行」(code of conduct 行動規範)で、発音のアクセント位置が動詞と異なります。"}
 ],
 "phrases": [
  {"en": "be eligible for A", "pos": "形容詞句", "ja": "Aの資格がある、Aを受ける資格を満たす", "ex": "Staff members are eligible for the leadership program after one year of service.", "exJa": "スタッフは勤続1年を経ると、そのリーダーシップ研修を受ける資格があります。", "note": "Part 5 では前置詞 for の選択が狙われます。to 不定詞をとる形 be eligible to do も可(be eligible to apply)。類義は be qualified for A / be entitled to A(entitled は to をとる点で対比されます)。"},
  {"en": "take advantage of A", "pos": "動詞句", "ja": "Aを利用する、Aを活用する", "ex": "We encourage you to take advantage of the free language classes offered this fall.", "exJa": "この秋に提供される無料の語学クラスをぜひ利用してください。", "note": "Part 5 では of の選択が問われます。目的語が of の後に来るため、受動態は A be taken advantage of の形になります。類義は make use of A / utilize A。「人につけ込む」という負の意味にもなります。"},
  {"en": "participate in A", "pos": "動詞句", "ja": "Aに参加する", "ex": "More than sixty employees participated in last year's communication workshop.", "exJa": "60名を超える従業員が昨年のコミュニケーション研修に参加しました。", "note": "participate は自動詞なので目的語の前に in が必須です。in を落とす誤りが Part 5 で狙われます。類義は take part in A / join A(join は他動詞で前置詞不要)。名詞は participation in A。"},
  {"en": "consist of A", "pos": "動詞句", "ja": "Aから成る、Aで構成される", "ex": "The curriculum consists of four online modules and one in-person session.", "exJa": "そのカリキュラムは4つのオンライン教材と1回の対面講座から成ります。", "note": "consist は自動詞で、受動態にできません(× is consisted of)。この点が Part 5 の頻出ポイントです。類義は be made up of A / be composed of A(こちらは受動態の形をとります)。"},
  {"en": "no later than A", "pos": "前置詞句/副詞句", "ja": "遅くともAまでに", "ex": "Please submit your registration form no later than 15 August.", "exJa": "登録用紙は遅くとも8月15日までに提出してください。", "note": "期限を示す表現で、案内文やメールに頻出します。類義は by A / on or before A。no later than の後には日付・時刻が来ます。反対に「~より早くなく」は no earlier than。"}
 ]
});
