window.__addVocab({
  "date": "2026-07-28",
  "level": "600",
  "theme": "IT・システム（社内システムとサポート）",
  "words": [
    {"en": "install", "pos": "動", "ja": "導入する、設置する", "ex": "Our technicians will install the new software on every laptop this weekend.", "exJa": "技術者が今週末、全ノートパソコンに新しいソフトウェアを導入します。", "note": "類義語=set up / put in / fit。ソフトだけでなく機器の「設置」にも使います（install an air conditioner）。名詞は installation（導入、設置）で、installment（分割払い）とのつづり違いに注意します"},
    {"en": "upgrade", "pos": "動", "ja": "更新する、性能を上げる", "ex": "The company upgraded its servers to handle more online orders.", "exJa": "同社はより多くのオンライン注文に対応するためサーバーを更新しました。", "note": "類義語=improve / enhance / modernize。反意=downgrade。名詞でも使い a free upgrade（無料アップグレード）は旅行・宿泊の文脈でも頻出します"},
    {"en": "compatible", "pos": "形", "ja": "互換性のある、両立できる", "ex": "The older printers are not compatible with the new operating system.", "exJa": "古いプリンターは新しい基本ソフトと互換性がありません。", "note": "類義語=consistent / suited。前置詞は with で、Part 5で狙われます。名詞は compatibility（互換性）。人について使うと「気が合う」の意味になります"},
    {"en": "access", "pos": "名", "ja": "利用権、接続、入手手段", "ex": "Only team leaders have access to the payroll database.", "exJa": "給与データベースを利用できるのはチームリーダーだけです。", "note": "類義語=entry / admission / availability。have [gain / grant] access to ～ の形が頻出。動詞では他動詞で access the file のように前置詞を取らない点が狙われます。形容詞 accessible（利用しやすい）"},
    {"en": "technician", "pos": "名", "ja": "技術者、技師", "ex": "A technician from the vendor will visit the office on Tuesday morning.", "exJa": "業者の技術者が火曜の午前に事務所を訪問します。", "note": "類義語=engineer / specialist / repairperson。Part 3・4のアナウンスで修理や点検に来る人物として頻出。技術系の形容詞は technical、名詞 technology と混同しないようにします"},
    {"en": "troubleshoot", "pos": "動", "ja": "問題を診断して解決する", "ex": "The help desk can troubleshoot most connection issues by phone.", "exJa": "ヘルプデスクは接続の問題の大半を電話で解決できます。", "note": "類義語=diagnose / fix / resolve。名詞 troubleshooting（障害対応）はマニュアルの見出しで頻出します。原因を突き止めて直す、という手順の意味合いを含みます"},
    {"en": "downtime", "pos": "名", "ja": "（システムの）停止時間、休止時間", "ex": "The upgrade will cause about two hours of downtime on Saturday night.", "exJa": "更新作業により土曜の夜に約2時間の停止時間が発生します。", "note": "類義語=outage / interruption of service。反意=uptime。不可算名詞として使うのが普通で、scheduled downtime（計画停止）が定番。人については「休息時間」の意味にもなります"},
    {"en": "glitch", "pos": "名", "ja": "不具合、小さな故障", "ex": "A glitch in the booking page prevented some customers from paying.", "exJa": "予約ページの不具合により、一部の顧客が支払いできませんでした。", "note": "類義語=bug / minor fault / hitch。深刻ではない一時的な不具合を指し、Part 7では problem や issue と言い換えられます。a technical glitch の形で使うことが多いです"},
    {"en": "restore", "pos": "動", "ja": "復旧する、元に戻す", "ex": "Service was restored less than an hour after the power failure.", "exJa": "停電から1時間足らずでサービスが復旧しました。", "note": "類義語=recover / bring back / reinstate。受動態 be restored が頻出。建物の「修復」（restore a historic building）やデータの「復元」にも使う多義語で言い換え問題の定番です"},
    {"en": "migrate", "pos": "動", "ja": "移行する、移す", "ex": "All customer records will migrate to the new platform by Friday.", "exJa": "顧客記録はすべて金曜までに新しい基盤へ移行します。", "note": "類義語=move / transfer / shift。名詞は migration（移行）。自動詞・他動詞の両方で使え、migrate data to ～ のように to を伴います。生物の「移動する」の意味でも出ます"},
    {"en": "implement", "pos": "動", "ja": "実施する、導入する", "ex": "Management decided to implement the new security rules immediately.", "exJa": "経営陣は新しい安全規則を直ちに実施することを決めました。", "note": "類義語=carry out / put into practice / execute。計画・方針・制度を目的語に取ります。名詞 implementation（実施）。名詞では「道具」の意味もある点に注意します"},
    {"en": "authorize", "pos": "動", "ja": "許可する、権限を与える", "ex": "Only the department head can authorize access to the shared drive.", "exJa": "共有ドライブの利用を許可できるのは部門長だけです。", "note": "類義語=approve / permit / empower。authorize A to do（Aに～する権限を与える）の形が頻出。形容詞 authorized（許可された）、名詞 authorization（許可、承認）"},
    {"en": "subscription", "pos": "名", "ja": "契約、定期購読", "ex": "Your annual subscription to the design tool renews in October.", "exJa": "そのデザインツールの年間契約は10月に更新されます。", "note": "類義語=membership / contract。前置詞は to。renew [cancel] a subscription が定番で、雑誌の定期購読とソフトの利用契約の両方に使います。動詞は subscribe to"},
    {"en": "outage", "pos": "名", "ja": "停止、停電", "ex": "A brief outage affected users in the eastern offices yesterday.", "exJa": "昨日、短時間の停止が東部の事務所の利用者に影響しました。", "note": "類義語=blackout / service interruption / shutdown。power outage（停電）、network outage（通信断）。downtime が「停止していた時間」を指すのに対し、outage は「停止という出来事」を指します"},
    {"en": "secure", "pos": "形", "ja": "安全な、保護された", "ex": "Please send the file through the secure company portal.", "exJa": "そのファイルは安全な社内ポータル経由で送ってください。", "note": "類義語=safe / protected。名詞は security、副詞は securely。動詞では「確保する、獲得する」の意味になり（secure a contract=契約を取る）、この語義がPart 7の言い換えで狙われます"}
  ],
  "phrases": [
    {"en": "log in to", "pos": "句", "ja": "～にログインする、～に接続する", "ex": "Staff must log in to the portal with their new passwords.", "exJa": "社員は新しいパスワードでポータルにログインする必要があります。", "note": "Part 5では前置詞が狙われます。log in は自動詞句なので、目的語を続けるときは to が必要です（log in the portal は誤り。log into と1語にする書き方も可）。反意は log out of。類義=sign in to / access。名詞は1語の login（ログイン情報）で、log in と品詞が違う点も問われます。"},
    {"en": "back up", "pos": "句", "ja": "～のバックアップを取る、～を支援する", "ex": "Please back up your files before the technician arrives.", "exJa": "技術者が到着する前にファイルのバックアップを取ってください。", "note": "分離可能な句動詞で、代名詞は必ず間に置きます（back it up。back up it は誤り）。名詞・形容詞は1語の backup（backup copy=控えのコピー）で、この綴り分けがPart 5で狙われます。「（意見・主張を）裏づける」の意味もあります。類義=save a copy of / duplicate。"},
    {"en": "be compatible with", "pos": "句", "ja": "～と互換性がある、～と両立する", "ex": "The scanner is not compatible with computers made before 2020.", "exJa": "そのスキャナーは2020年より前に製造されたコンピューターとは互換性がありません。", "note": "前置詞 with が狙われます（compatible to は誤り）。work with / run on と言い換えられ、Part 7の同義語問題に出ます。反意は be incompatible with。同じく with を取る be consistent with（～と一致する）、be familiar with（～に精通している）とセットで覚えます。"},
    {"en": "take effect", "pos": "句", "ja": "（規則・変更が）効力を生じる、実施される", "ex": "The new password rules take effect on the first of next month.", "exJa": "新しいパスワード規則は来月1日から効力を生じます。", "note": "effect は無冠詞で、take an effect とはしません（have an effect on ～「～に影響を与える」とは形が違う点が狙われます）。日付には on、期間の開始には as of / starting を添えます。類義=come into effect / go into effect / become effective。affect（動詞）との混同にも注意します。"},
    {"en": "in advance", "pos": "句", "ja": "前もって、事前に", "ex": "Requests for extra storage should be submitted two weeks in advance.", "exJa": "追加容量の申請は2週間前までに提出してください。", "note": "期間を前に置いて two weeks in advance（2週間前に）とする語順がPart 5で狙われます。「～より前に」と対象を示すときは in advance of ～（=prior to / ahead of）とします。類義=beforehand / ahead of time。反意的な表現は on short notice（急に）。"}
  ]
});
