window.__addVocab({
 "date": "2026-07-27",
 "level": "600",
 "theme": "製造・品質管理（工場と品質保証）",
 "words": [
  {"en": "manufacture", "pos": "動", "trans": "vt", "ja": "製造する、生産する", "ex": "The company manufactures kitchen appliances at three sites in Ohio.", "exJa": "その会社はオハイオ州の3拠点で台所用電化製品を製造しています。", "note": "類義語=produce / make / turn out。名詞で「製造」の意味もあります。manufacturer（製造業者、メーカー）と manufacturing（製造業）の使い分けがPart 5で狙われます"},
  {"en": "assembly", "pos": "名", "ja": "組み立て、集会", "ex": "The new assembly line can finish two hundred units per hour.", "exJa": "新しい組立ラインは1時間に200台を仕上げられます。", "note": "類義語=putting together / gathering。assembly line（組立ライン）が最頻出。「組み立て」と「集会」の両方を指す多義語で、動詞は assemble（組み立てる、集まる）"},
  {"en": "component", "pos": "名", "ja": "部品、構成要素", "ex": "One component in the motor was replaced before shipping.", "exJa": "出荷前にモーターの部品を1つ交換しました。", "note": "類義語=part / element / ingredient。key component（重要な構成要素）。抽象的な「要素」にも使え、Part 7の言い換えで part と入れ替わります"},
  {"en": "plant", "pos": "名", "ja": "工場", "ex": "Our Riverton plant operates six days a week.", "exJa": "当社のリバートン工場は週6日稼働しています。", "note": "類義語=factory / mill / facility。「植物」「（動詞で）植える、設置する」の意味もある多義語で、TOEICでは工場の意味が中心。power plant（発電所）"},
  {"en": "output", "pos": "名", "ja": "生産高、産出量", "ex": "Monthly output increased after the second shift was added.", "exJa": "第2交代勤務を追加した後、月間の生産高が増えました。", "note": "類義語=production / yield。反意=input。increase [boost] output（生産高を上げる）。動詞としても使えますが、TOEICでは名詞が中心です"},
  {"en": "productivity", "pos": "名", "ja": "生産性", "ex": "Better lighting in the workshop improved productivity by eight percent.", "exJa": "作業場の照明を改善したことで生産性が8パーセント向上しました。", "note": "類義語=efficiency。形容詞 productive（生産的な）、副詞 productively。productivity と production（生産、生産量）の違いがPart 5で問われます"},
  {"en": "specification", "pos": "名", "ja": "仕様、仕様書", "ex": "The part did not meet the specifications in our order.", "exJa": "その部品は当社の注文書の仕様を満たしていませんでした。", "note": "類義語=requirement / standard。口語では spec と略します。meet [match] the specifications（仕様を満たす）が定番。動詞は specify（明記する）"},
  {"en": "durable", "pos": "形", "ja": "耐久性のある、長持ちする", "ex": "The case is made of a durable plastic that resists heat.", "exJa": "そのケースは熱に強い耐久性のあるプラスチックでできています。", "note": "類義語=long-lasting / sturdy / hard-wearing。反意=fragile。名詞は durability（耐久性）。durable goods（耐久財）は経済記事で頻出"},
  {"en": "malfunction", "pos": "動", "trans": "vi", "ja": "正常に動かない、故障する", "ex": "Two sensors malfunctioned during the final test.", "exJa": "最終試験中にセンサー2個が正常に作動しませんでした。", "note": "類義語=break down / fail / stop working。名詞でも「故障、不具合」の意味で使います（a software malfunction）。自動詞なので目的語は取りません"},
  {"en": "flaw", "pos": "名", "ja": "欠陥、傷、不備", "ex": "Inspectors found a small flaw in the surface coating.", "exJa": "検査員は表面塗装に小さな傷を見つけました。", "note": "類義語=defect / fault / imperfection。形容詞 flawed（欠陥のある）、flawless（完璧な）。計画や議論の「不備」にも使う点がPart 7で狙われます"},
  {"en": "certify", "pos": "動", "trans": "vt", "ja": "認証する、証明する", "ex": "All our heaters are certified by the national safety board.", "exJa": "当社の暖房器具はすべて国の安全委員会の認証を受けています。", "note": "類義語=verify / accredit / approve。受動態 be certified by ～ が頻出。名詞は certificate（証明書）と certification（認証）で、後者は制度そのものを指します"},
  {"en": "streamline", "pos": "動", "trans": "vt", "ja": "効率化する、合理化する", "ex": "The new software streamlines the ordering process.", "exJa": "新しいソフトウェアは発注手続きを効率化します。", "note": "類義語=simplify / make more efficient。「無駄を省いて流れを良くする」意味で、手続き・組織・工程を目的語に取ります。形容詞 streamlined（無駄のない）"},
  {"en": "shift", "pos": "名", "ja": "交代勤務、シフト", "ex": "Workers on the night shift receive an extra allowance.", "exJa": "夜勤の作業員には追加手当が支給されます。", "note": "類義語=work period。night [day] shift、work in shifts（交代で働く）。動詞では「移す、変える」、名詞では「変化」の意味もある多義語で言い換え問題の定番"},
  {"en": "quota", "pos": "名", "ja": "ノルマ、割当量", "ex": "The team met its quota three days before the deadline.", "exJa": "そのチームは期限の3日前にノルマを達成しました。", "note": "類義語=target / allotment / limit。meet [reach] a quota（ノルマを達成する）、sales quota（販売目標）。輸入の「割当枠」の意味でも出ます"},
  {"en": "compliance", "pos": "名", "ja": "順守、遵守", "ex": "Compliance with safety rules is checked every quarter.", "exJa": "安全規則の順守状況は四半期ごとに確認されます。", "note": "類義語=conformity / adherence / observance。前置詞は with。in compliance with（～に従って）の形が頻出。動詞 comply、形容詞 compliant"}
 ],
 "phrases": [
  {"en": "comply with", "pos": "動詞句", "ja": "～に従う、～を順守する", "ex": "All suppliers must comply with our written standards.", "exJa": "すべての納入業者は当社の定めた基準に従わなければなりません。", "note": "Part 5では前置詞 with が狙われます（comply to は誤り）。同義の obey / follow / observe は他動詞なので前置詞を取らない点も対比で問われます。類義=conform to / adhere to / abide by。名詞形の in compliance with も一緒に覚えます。"},
  {"en": "be equipped with", "pos": "動詞句", "ja": "～を備えている、～が装備されている", "ex": "Each station is equipped with two torque meters.", "exJa": "各作業台にはトルク計が2台備えられています。", "note": "equip A with B（AにBを装備する）の受動態で、前置詞 with が狙われます（equipped by は「～によって装備された」と行為者を表す別の意味）。類義=be furnished with / be fitted with / come with。人が主語なら「（能力・知識を）備えている」の意味にもなります。"},
  {"en": "result in", "pos": "動詞句", "ja": "～という結果になる、～をもたらす", "ex": "The delay resulted in a shortage of parts last month.", "exJa": "その遅れが先月の部品不足という結果を招きました。", "note": "result in の後ろは「結果」、result from の後ろは「原因」で、この対比がPart 5の定番です。後ろは名詞か動名詞で、to do は取りません。類義=lead to / bring about / cause。lead to も後ろは名詞・動名詞です。"},
  {"en": "keep track of", "pos": "動詞句", "ja": "～を把握する、～を記録し続ける", "ex": "Inspectors keep track of every lot in a shared file.", "exJa": "検査員は共有ファイルで全ロットを記録し把握しています。", "note": "track は無冠詞の単数で、keep a track of は誤りです。反意は lose track of（見失う、分からなくなる）で、この対比が問われます。類義=monitor / follow / keep a record of / stay on top of。"},
  {"en": "shut down", "pos": "動詞句", "ja": "（機械・工場を）停止する、閉鎖する", "ex": "The line will shut down until the cause is found.", "exJa": "原因が判明するまでラインは停止します。", "note": "自動詞・他動詞の両方で使え、他動詞では分離可能です（shut down the line / shut the line down）。代名詞は必ず間に置き shut it down となる点がPart 5で狙われます。名詞は1語の shutdown（操業停止）。類義=close down / halt / suspend operations。"}
 ]
});
