window.__addVocab({
  "date": "2026-08-02",
  "level": "600",
  "theme": "メディア・出版（新聞社・編集業務）",
  "words": [
    {"en": "publish", "pos": "動", "trans": "vt", "ja": "出版する、掲載する、公表する", "ex": "The magazine will publish the interview in next month's issue.", "exJa": "その雑誌は来月号にそのインタビューを掲載します。", "note": "他動詞なので目的語が直接続きます（publish a book / publish the results）。受動態 be published が記事文で頻出。類義: issue, release, print。名詞は publication（出版物、公表）、publisher（出版社）。"},
    {"en": "submit", "pos": "動", "trans": "vt", "ja": "提出する", "ex": "All writers must submit their articles by Tuesday.", "exJa": "すべての執筆者は火曜日までに記事を提出しなければなりません。", "note": "他動詞。提出先は to で示します（submit the report to the editor）。Part 7で submit ⇔ hand in / turn in の言い換えが狙われます。名詞は submission。応募・申請文書の定番語です。"},
    {"en": "article", "pos": "名", "ja": "記事", "ex": "She wrote a long article about the city's transit plan.", "exJa": "彼女は市の交通計画についての長い記事を書きました。", "note": "可算名詞。an article on/about A（Aに関する記事）の形で出ます。類義: story, piece, report。「品物」（household articles）や文法用語の「冠詞」の意味もあり、文脈で判断します。"},
    {"en": "subscriber", "pos": "名", "ja": "定期購読者、加入者", "ex": "The newspaper has more than fifty thousand subscribers.", "exJa": "その新聞は5万人を超える定期購読者を抱えています。", "note": "動詞 subscribe は自動詞で、対象は to をとります（subscribe to a magazine）。この前置詞 to がPart 5で狙われます。名詞 subscription（定期購読、契約）とセットで覚えます。"},
    {"en": "edition", "pos": "名", "ja": "版、（刊行物の）号", "ex": "The revised edition of the guidebook comes out in May.", "exJa": "そのガイドブックの改訂版は5月に発売されます。", "note": "「版」＝内容や形式の違い（digital edition, revised edition, second edition）。同じ雑誌の「○月号」のような回ごとの発行分は issue を使う点が違いです。editor（編集者）と綴りが似るので注意します。"},
    {"en": "editor", "pos": "名", "ja": "編集者、編集長", "ex": "The editor asked for two more photographs.", "exJa": "編集者は写真をあと2枚求めました。", "note": "動詞 edit（編集する、他動詞）、形容詞 editorial（編集の）、名詞 editorial（社説）。editor in chief（編集長）も出ます。edition（版）との区別がPart 5の語彙問題で狙われます。"},
    {"en": "deadline", "pos": "名", "ja": "締め切り、期限", "ex": "The deadline for the fall issue has been moved to Friday.", "exJa": "秋号の締め切りは金曜日に変更されました。", "note": "meet the deadline（締め切りに間に合わせる）／miss the deadline（間に合わない）／extend the deadline（延長する）のコロケーションで覚えます。類義: due date, cutoff date。"},
    {"en": "issue", "pos": "名/動", "trans": "vt", "ja": "（雑誌などの）号、問題、発行する", "ex": "The company issued a statement about the delay.", "exJa": "その会社は遅延について声明を発表しました。", "note": "多義語でPart 7の言い換えの常連です。名詞は「号」（the July issue）と「問題点」（an important issue）。動詞は他動詞で「発行する、交付する」（issue a permit / issue a refund）＝ release, publish に言い換えられます。"},
    {"en": "broadcast", "pos": "動/名", "trans": "vt/vi", "ja": "放送する、放送（番組）", "ex": "The station will broadcast the interview on Wednesday morning.", "exJa": "その放送局は水曜の朝にそのインタビューを放送します。", "note": "他動詞（broadcast a program）が中心ですが、自動詞用法（The station broadcasts 24 hours a day.）もあります。過去形・過去分詞は broadcast のまま（broadcasted も可だが試験では原形同形が基本）。名詞 broadcaster（放送局、キャスター）。"},
    {"en": "column", "pos": "名", "ja": "コラム、（新聞の）欄、（表の）列、柱", "ex": "His weekly column appears on the opinion page.", "exJa": "彼の週刊コラムは意見欄に掲載されます。", "note": "新聞の「コラム」のほか、表計算の「列」（縦。横は row）、建物の「柱」の意味もあり、Part 7の図表問題では「列」の意味で出ます。書き手は columnist。"},
    {"en": "circulation", "pos": "名", "ja": "発行部数、流通、循環", "ex": "The paper's circulation has grown for three straight years.", "exJa": "その新聞の発行部数は3年連続で伸びています。", "note": "出版では「発行部数」。ほかに「（貨幣などの）流通」「（空気・血液の）循環」。動詞 circulate（自動詞で「出回る、循環する」／他動詞で「回覧する」）も社内文書で頻出です（circulate the memo）。"},
    {"en": "journalist", "pos": "名", "ja": "記者、ジャーナリスト", "ex": "Two journalists were assigned to cover the trade fair.", "exJa": "2人の記者が見本市の取材を担当することになりました。", "note": "類義: reporter, correspondent（特派員）。動詞 cover（取材する、報道する）とセットで出ます。分野の名詞は journalism。"},
    {"en": "release", "pos": "動/名", "trans": "vt", "ja": "公表する、発売する、解放する／発表", "ex": "The company will release its annual report next week.", "exJa": "その会社は来週、年次報告書を公表します。", "note": "他動詞。press release（報道発表）は名詞用法の定番。Part 7の同義語問題で release ⇔ issue / publish / announce の言い換えが狙われます。「解放する」の意味もあります。"},
    {"en": "coverage", "pos": "名", "ja": "報道、取材（範囲）、（保険の）補償範囲", "ex": "The magazine is known for its detailed coverage of local politics.", "exJa": "その雑誌は地方政治の詳細な報道で知られています。", "note": "不可算。動詞 cover（取材する、～に及ぶ、～を賄う）から派生します。保険文書では「補償範囲」（insurance coverage）、通信では「通信可能範囲」の意味になり、Part 7で文脈判断が要ります。類義: reporting。"},
    {"en": "quarterly", "pos": "形/副", "ja": "四半期の、年4回の／四半期ごとに", "ex": "The firm publishes a quarterly report on local businesses.", "exJa": "その会社は地元企業に関する四半期報告書を発行しています。", "note": "quarter（四半期）から。同系列の monthly（毎月の）、biweekly（隔週の／週2回の）、annual（年次の）とまとめて覚えます。形容詞と副詞が同形で、The magazine is published quarterly. のように副詞でも使えます。"}
  ],
  "phrases": [
    {"en": "come out", "pos": "動詞句", "ja": "発売される、出版される、（事実などが）明らかになる", "ex": "The digital issue comes out every Thursday at 6:00 A.M.", "exJa": "デジタル版は毎週木曜の午前6時に発行されます。", "note": "Part 5で狙われる点: come は自動詞なので目的語をとれず、受動態にできません（The book was come out は誤り）。「本が出る」は The book comes out（能動）か The book is published（受動）と表します。類義: be released, be published, appear。"},
    {"en": "keep up with A", "pos": "動詞句", "ja": "Aに遅れずについていく、Aの動きを把握し続ける", "ex": "We must keep up with the changing habits of our readers.", "exJa": "私たちは読者の変化する習慣に遅れずについていかねばなりません。", "note": "Part 5で狙われる点: up と with の2語がセットで、どちらか一方の空所が問われます。keep up A（Aを維持する）とは意味が違い、後ろに目的語が続く場合は with が必要です。類義: catch up with A（遅れを取り戻して追いつく。すでに遅れている点が違う）, stay current with A。"},
    {"en": "as of A", "pos": "前置詞句", "ja": "A（日付）付けで、A現在で", "ex": "As of October 1, the newsletter will be sent by e-mail only.", "exJa": "10月1日付けで、そのニュースレターは電子メールでのみ送られます。", "note": "Part 5で狙われる点: of は前置詞なので後ろは日付・時点を表す名詞です。未来の日付なら「～から（開始）」、過去や現在の日付なら「～時点で（現状）」と訳し分けます。類義: effective A（effective October 1）, beginning A, starting A。"},
    {"en": "be responsible for A", "pos": "動詞句", "ja": "Aに責任がある、Aを担当している", "ex": "Ms. Alvarez is responsible for the weekly opinion column.", "exJa": "アルバレスさんは週刊の意見コラムを担当しています。", "note": "Part 5で狙われる点: 前置詞は for で固定です（to や of は不可）。後ろが動詞のときは動名詞にします（responsible for editing the column）。類義: be in charge of A, handle A, oversee A。名詞は responsibility。"},
    {"en": "in response to A", "pos": "前置詞句", "ja": "Aに応じて、Aに答えて", "ex": "In response to requests from readers, we added a business section.", "exJa": "読者からの要望に応じて、私たちはビジネス欄を追加しました。", "note": "Part 5で狙われる点: response の後ろの前置詞は to で固定です（respond to A の to がそのまま残る形）。後ろは名詞か動名詞になります。類義: in reply to A, in answer to A, following A。"}
  ]
});
